package cloudformation

import (
	_ "embed"
	"encoding/json"
	"sync"
)

// cfn_attributes.json is generated by cmd/cfnattrgen from the CloudFormation
// resource specification; DO NOT EDIT. Regenerate with `make cfn-attrs-gen`.
//
//go:embed cfn_attributes.json
var cfnAttributesJSON []byte

//nolint:gochecknoglobals // lazily populated cache of the embedded attribute table
var (
	cfnResourceAttributes     map[string]map[string]struct{}
	cfnResourceAttributesOnce sync.Once
)

// resourceAttributeTable parses cfnAttributesJSON once. JSON, not Go source,
// keeps attribute-name literals out of goconst's package-wide count.
func resourceAttributeTable() map[string]map[string]struct{} {
	cfnResourceAttributesOnce.Do(func() {
		var raw map[string][]string
		if err := json.Unmarshal(cfnAttributesJSON, &raw); err != nil {
			panic("cloudformation: invalid embedded cfn_attributes.json: " + err.Error())
		}

		table := make(map[string]map[string]struct{}, len(raw))

		for resType, attrs := range raw {
			set := make(map[string]struct{}, len(attrs))
			for _, a := range attrs {
				set[a] = struct{}{}
			}

			table[resType] = set
		}

		cfnResourceAttributes = table
	})

	return cfnResourceAttributes
}
