// Code generated by cmd/cfnattrgen from the CloudFormation resource specification; DO NOT EDIT.
package cloudformation

//nolint:gochecknoglobals // generated static lookup table
var cfnResourceAttributes = map[string]map[string]struct{}{
	resTypeAccessAnalyzerAnalyzer: {
		attrNameArn: {},
	},
	resTypeAccessAnalyzerArchiveRule: {
		attrNameArn: {},
		"CreatedAt": {},
		"UpdatedAt": {},
	},
	resTypeAPIGatewayV2Integ: {
		"IntegrationId": {},
	},
	resTypeAPIGatewayV2Route: {
		"RouteId": {},
	},
	resTypeAPIGatewayV2VpcLink: {
		"VpcLinkId": {},
	},
	resTypeAppConfigEnvironment: {
		"EnvironmentId": {},
	},
	resTypeAppSyncChannelNamespace: {
		"ChannelNamespaceArn": {},
	},
	resTypeAthenaNamedQuery: {
		"NamedQueryId": {},
	},
	resTypeAthenaWorkGroup: {
		"CreationTime": {},
		"WorkGroupConfiguration.EngineVersion.EffectiveEngineVersion": {},
	},
	resTypeASGScheduledActn: {
		"ScheduledActionName": {},
	},
	resTypeBackupFramework: {
		"CreationTime":     {},
		"DeploymentStatus": {},
		"FrameworkArn":     {},
		"FrameworkStatus":  {},
	},
	resTypeBackupReportPlan: {
		"ReportPlanArn": {},
	},
	resTypeBatchSchedulingPolicy: {
		attrNameArn: {},
	},
	resTypeBatchServiceEnvironment: {
		"ServiceEnvironmentArn": {},
	},
	resTypeCloudTrailChannel: {
		"ChannelArn": {},
	},
	resTypeCloudWatchAlarm: {
		attrNameArn: {},
	},
	resTypeCodeArtifactPackageGroup: {
		attrNameArn: {},
	},
	resTypeCodeBuildReportGroup: {
		attrNameArn: {},
	},
	resTypeConfigAggregationAuthorization: {
		"AggregationAuthorizationArn": {},
	},
	resTypeConfigConfigRule: {
		attrNameArn:       {},
		"Compliance.Type": {},
		"ConfigRuleId":    {},
	},
	resTypeConfigConfigurationAggregator: {
		"ConfigurationAggregatorArn": {},
	},
	resTypeConfigConformancePack: {
		"ConformancePackArn": {},
	},
	resTypeConfigStoredQuery: {
		"QueryArn": {},
		"QueryId":  {},
	},
	resTypeDataSyncAgent: {
		"AgentArn":     {},
		"EndpointType": {},
	},
	resTypeDataSyncLocationS3: {
		"LocationArn": {},
		"LocationUri": {},
	},
	resTypeDocDBGlobalCluster: {
		"GlobalClusterArn":        {},
		"GlobalClusterResourceId": {},
	},
	resTypeEC2CustomerGateway: {
		"CustomerGatewayId": {},
	},
	resTypeEC2DHCPOptions: {
		"DhcpOptionsId": {},
	},
	resTypeEC2Host: {
		"HostId": {},
	},
	resTypeEC2IPAMScope: {
		attrNameArn:     {},
		"IpamArn":       {},
		"IpamScopeId":   {},
		"IpamScopeType": {},
		"IsDefault":     {},
		"PoolCount":     {},
	},
	resTypeEC2LaunchTemplate: {
		"DefaultVersionNumber": {},
		"LatestVersionNumber":  {},
		"LaunchTemplateId":     {},
	},
	resTypeEC2PrefixList: {
		attrNameArn:    {},
		"OwnerId":      {},
		"PrefixListId": {},
		"Version":      {},
	},
	resTypeEC2TrafficMirrorFilterRule: {
		"TrafficMirrorFilterRuleId": {},
	},
	resTypeEC2TGWRouteTable: {
		"TransitGatewayRouteTableId": {},
	},
	resTypeEC2VPNConnection: {
		"VpnConnectionId": {},
	},
	resTypeEC2VPNGateway: {
		"VPNGatewayId": {},
	},
	resTypeEC2VerifiedAccessInst: {
		"CidrEndpointsCustomSubDomainNameServers": {},
		"CreationTime":             {},
		"LastUpdatedTime":          {},
		"VerifiedAccessInstanceId": {},
	},
	resTypeECRRegistryPolicy: {
		"RegistryId": {},
	},
	resTypeECRRepositoryCreationTemplate: {
		"CreatedAt": {},
		"UpdatedAt": {},
	},
	resTypeECSCluster: {
		attrNameArn: {},
	},
	resTypeEFSAccessPoint: {
		"AccessPointId": {},
		attrNameArn:     {},
	},
	resTypeEKSAccessEntry: {
		"AccessEntryArn": {},
	},
	resTypeEKSAddon: {
		attrNameArn: {},
	},
	resTypeEKSFargateProfile: {
		attrNameArn: {},
	},
	resTypeEKSIdentityProviderConfig: {
		"IdentityProviderConfigArn": {},
	},
	resTypeElastiCacheParameterGroup: {
		"CacheParameterGroupName": {},
	},
	resTypeGlueClassifier: {
		attrNameName: {},
	},
	resTypeGlueRegistry: {
		attrNameArn: {},
	},
	resTypeGlueSchema: {
		attrNameArn:              {},
		"InitialSchemaVersionId": {},
	},
	resTypeIAMAccessKey: {
		"SecretAccessKey": {},
	},
	resTypeIAMOIDCProvider: {
		attrNameArn: {},
	},
	resTypeIAMRole: {
		attrNameArn: {},
		"RoleId":    {},
	},
	resTypeIAMSAMLProvider: {
		attrNameArn:        {},
		"SamlProviderUUID": {},
	},
	resTypeIAMServerCertificate: {
		attrNameArn: {},
	},
	resTypeIAMVirtualMFADevice: {
		"SerialNumber": {},
	},
	resTypeIoTAuthorizer: {
		attrNameArn: {},
	},
	resTypeIoTDimension: {
		attrNameArn: {},
	},
	resTypeIoTDomainConfiguration: {
		attrNameArn:          {},
		"DomainType":         {},
		"ServerCertificates": {},
	},
	resTypeIoTJobTemplate: {
		attrNameArn: {},
	},
	resTypeIoTMitigationAction: {
		"MitigationActionArn": {},
		"MitigationActionId":  {},
	},
	resTypeIoTProvisioningTemplate: {
		"TemplateArn": {},
	},
	resTypeIoTRoleAlias: {
		"RoleAliasArn": {},
	},
	resTypeIoTScheduledAudit: {
		"ScheduledAuditArn": {},
	},
	resTypeIoTSecurityProfile: {
		"SecurityProfileArn": {},
	},
	resTypeIoTTopicRuleDestination: {
		attrNameArn:    {},
		"StatusReason": {},
	},
	resTypeFirehoseDeliveryStream: {
		attrNameArn: {},
	},
	resTypeLambdaCodeSigningConfig: {
		"CodeSigningConfigArn": {},
		"CodeSigningConfigId":  {},
	},
	resTypeLambdaFunction: {
		attrNameArn:                            {},
		"SnapStartResponse":                    {},
		"SnapStartResponse.ApplyOn":            {},
		"SnapStartResponse.OptimizationStatus": {},
	},
	resTypeLogsDelivery: {
		attrNameArn:               {},
		"DeliveryDestinationType": {},
		"DeliveryId":              {},
	},
	resTypeLogsDeliveryDestination: {
		attrNameArn: {},
	},
	resTypeLogsDestination: {
		attrNameArn: {},
	},
	resTypeLogsIntegration: {
		"IntegrationStatus": {},
	},
	resTypeLogsAnomalyDetector: {
		"AnomalyDetectorArn":    {},
		"AnomalyDetectorStatus": {},
		"CreationTimeStamp":     {},
		"LastModifiedTimeStamp": {},
	},
	resTypeLogGroup: {
		attrNameArn: {},
	},
	resTypeLogsScheduledQuery: {
		"CreationTime":        {},
		"LastExecutionStatus": {},
		"LastTriggeredTime":   {},
		"LastUpdatedTime":     {},
		"ScheduledQueryArn":   {},
	},
	resTypeMemoryDBParameterGroup: {
		"ARN": {},
	},
	resTypeMemoryDBSubnetGroup: {
		"ARN":                   {},
		"SupportedNetworkTypes": {},
	},
	resTypeRedshiftClusterSubnetGroup: {
		"ClusterSubnetGroupName": {},
	},
	resTypeR53RResolverRuleAssoc: {
		attrNameName:                {},
		"ResolverRuleAssociationId": {},
		"ResolverRuleId":            {},
		"VPCId":                     {},
	},
	resTypeSSMMaintenanceWindowTarget: {
		"WindowTargetId": {},
	},
	resTypeSSMMaintenanceWindowTask: {
		"WindowTaskId": {},
	},
	resTypeSSMResourcePolicy: {
		"PolicyHash": {},
		"PolicyId":   {},
	},
	resTypeSageMakerCodeRepository: {
		"CodeRepositoryArn":  {},
		"CodeRepositoryName": {},
	},
	resTypeSageMakerFeatureGroup: {
		"CreationTime":       {},
		"FeatureGroupStatus": {},
	},
	resTypeSageMakerImage: {
		"ImageArn": {},
	},
	resTypeSageMakerImageVersion: {
		"ContainerImage":  {},
		"ImageArn":        {},
		"ImageVersionArn": {},
		"Version":         {},
	},
	resTypeSageMakerModelPackageGroup: {
		"CreationTime":            {},
		"ModelPackageGroupArn":    {},
		"ModelPackageGroupStatus": {},
	},
	resTypeSageMakerNotebookInstance: {
		"NotebookInstanceArn":  {},
		"NotebookInstanceName": {},
	},
	resTypeSageMakerNotebookInstanceLifecycleConfig: {
		"NotebookInstanceLifecycleConfigName": {},
	},
	resTypeSageMakerProject: {
		"CreationTime":  {},
		"ProjectArn":    {},
		"ProjectId":     {},
		"ProjectStatus": {},
	},
	resTypeSageMakerWorkteam: {
		"WorkteamName": {},
	},
	resTypeStepFunctionsActivity: {
		attrNameArn:  {},
		attrNameName: {},
	},
	resTypeStepFunctionsStateMachine: {
		attrNameArn:              {},
		attrNameName:             {},
		"StateMachineRevisionId": {},
	},
	resTypeTransferProfile: {
		attrNameArn: {},
		"ProfileId": {},
	},
	resTypeTransferWorkflow: {
		attrNameArn:  {},
		"WorkflowId": {},
	},
}
