package main

import (
	"fmt"
	"strconv"
	"strings"
)

// deferredPreviewLimit caps how many deferred: items a service README lists
// inline before pointing the reader at the full PARITY.md instead.
const deferredPreviewLimit = 5

// genComment marks every generated services/<svc>/README.md so nobody hand
// edits it and has the edit silently clobbered by the next `make docs`.
const genComment = "<!-- Code generated by cmd/gendocs from PARITY.md. DO NOT EDIT. Run: make docs -->\n"

// renderServiceReadme builds the full Markdown content of a generated
// services/<svc>/README.md from its parsed PARITY.md. hasGuide indicates
// whether docs/services/<svc>.md exists, in which case a link to it is
// included.
func renderServiceReadme(slug string, doc *ParityDoc, hasGuide bool) string {
	var b strings.Builder

	b.WriteString(genComment)
	b.WriteString("# " + displayName(slug) + "\n\n")
	b.WriteString(renderHeaderLine(doc) + "\n\n")
	b.WriteString("## Coverage\n\n")
	b.WriteString("| Metric | Value |\n| --- | --- |\n")
	writeCoverageRows(&b, doc)
	b.WriteString("\n")

	writeKnownGaps(&b, doc.Gaps)
	writeStructuralGaps(&b, doc.StructuralGaps)
	writeDeferredSection(&b, doc.Deferred)

	b.WriteString("## More\n\n")
	b.WriteString("- [Full parity audit](PARITY.md)\n")
	if hasGuide {
		b.WriteString("- [Service guide](../../docs/services/" + slug + ".md)\n")
	}
	b.WriteString("- [All services](../../README.md#services)\n")

	return b.String()
}

// renderHeaderLine builds the "**Parity grade: A** · SDK `...` · last
// audited ... · protocol ..." summary line, omitting any segment whose
// underlying field was empty in PARITY.md.
func renderHeaderLine(doc *ParityDoc) string {
	parts := []string{"**Parity grade: " + doc.Overall + "**"}

	if doc.SDKModule != "" {
		parts = append(parts, "SDK `"+doc.SDKModule+"`")
	}

	if doc.LastAuditDate != "" || doc.LastAuditCommit != "" {
		audit := strings.TrimSpace("last audited " + doc.LastAuditDate)
		if doc.LastAuditCommit != "" {
			audit += " (`" + doc.LastAuditCommit + "`)"
		}
		parts = append(parts, audit)
	}

	if doc.Protocol != "" {
		parts = append(parts, "protocol "+doc.Protocol)
	}

	return strings.Join(parts, " · ")
}

// writeCoverageRows appends the Coverage table body rows. The PARITY
// entries and Feature families rows are each omitted when the source
// PARITY.md has no corresponding block, since some services audit purely
// by op and others purely by family.
func writeCoverageRows(b *strings.Builder, doc *ParityDoc) {
	if len(doc.Ops) > 0 {
		t := doc.opsTally()
		fmt.Fprintf(b, "| PARITY entries audited | %d (%s) |\n", t.total(), t.String())
	}

	if len(doc.Families) > 0 {
		t := doc.familiesTally()
		fmt.Fprintf(b, "| Feature families | %d (%s) |\n", t.total(), t.String())
	}

	gapsCell := "none"
	if len(doc.Gaps) > 0 {
		gapsCell = strconv.Itoa(len(doc.Gaps))
	}
	b.WriteString("| Known gaps | " + gapsCell + " |\n")

	if len(doc.StructuralGaps) > 0 {
		fmt.Fprintf(b, "| Structural gaps (can't be emulated) | %d |\n", len(doc.StructuralGaps))
	}

	fmt.Fprintf(b, "| Deferred items | %d |\n", len(doc.Deferred))

	leaks := doc.LeaksStatus
	if leaks == "" {
		leaks = "unknown"
	}
	b.WriteString("| Resource leaks | " + leaks + " |\n")
}

// writeKnownGaps appends the "### Known gaps" section, omitted entirely when
// there are none.
func writeKnownGaps(b *strings.Builder, gaps []string) {
	if len(gaps) == 0 {
		return
	}

	b.WriteString("### Known gaps\n\n")
	for _, g := range gaps {
		b.WriteString("- " + g + "\n")
	}
	b.WriteString("\n")
}

// writeStructuralGaps appends the "### Structural gaps" section, omitted
// entirely when there are none. Unlike Known gaps, these never block an A
// grade: the underlying data source (real traffic, an ML/AI engine, a
// billing/settlement system, physical hardware) cannot exist in an emulator.
func writeStructuralGaps(b *strings.Builder, gaps []string) {
	if len(gaps) == 0 {
		return
	}

	b.WriteString("### Structural gaps\n\n")
	b.WriteString("These do not block an A grade — no implementation could produce real data " +
		"here because the underlying data source cannot exist in an emulator.\n\n")
	for _, g := range gaps {
		b.WriteString("- " + g + "\n")
	}
	b.WriteString("\n")
}

// writeDeferredSection appends the "### Deferred" section, omitted entirely
// when empty and truncated to deferredPreviewLimit items (plus a pointer to
// PARITY.md for the rest) when long.
func writeDeferredSection(b *strings.Builder, deferred []string) {
	if len(deferred) == 0 {
		return
	}

	b.WriteString("### Deferred\n\n")

	limit := len(deferred)
	truncated := limit > deferredPreviewLimit
	if truncated {
		limit = deferredPreviewLimit
	}

	for _, item := range deferred[:limit] {
		b.WriteString("- " + item + "\n")
	}

	if truncated {
		fmt.Fprintf(b, "- …and %d more — see PARITY.md\n", len(deferred)-limit)
	}

	b.WriteString("\n")
}
