package cloudfrontkeyvaluestore_test

import (
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/labstack/echo/v5"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// sdkRouteCases is the authoritative method+path for every real CloudFront
// KeyValueStore data-plane operation, extracted from
// cloudfrontkeyvaluestore@v1.15.4 serializers.go: each entry's
// "request.Method" and the string passed to httpbinding.SplitURI in that
// op's awsRestjson1_serializeOp<Op>.HandleSerialize. PLACEHOLDER stands in
// for the {KvsARN}/{Key} URI labels -- route() (handler.go) dispatches on
// path depth, the literal "keys" segment, and HTTP method alone, never
// validating either label's shape, so the literal values don't matter here.
// 6 real ops here, matching this service's real op count exactly (also
// matches GetSupportedOperations's own 6 entries one-for-one).
//
// This service was flagged going in as possibly having ops structurally
// unreachable by path alone, the way s3's ListDirectoryBuckets is
// distinguished from ListBuckets by hostname only, with an otherwise
// identical request. That does NOT apply here. Real
// cloudfrontkeyvaluestore's endpoint ruleset (endpoints.go's resolveResult,
// case 3) does prepend a per-*account* virtual host
// ("https://{accountId}.cloudfront-kvs.global.api.aws", derived from the
// KvsARN's account ID -- not a per-store host as initially suspected) when
// no BaseEndpoint override is configured, and even a configured override
// still prefixes that account ID onto the given authority (case 1) -- see
// handler_test.go's staticEndpointResolver and its doc comment, added
// separately from this table, for where that was first worked around. But
// in both cases the operation's full REST path, {KvsARN} label included, is
// still generated by SplitURI and sent unchanged (verified directly above:
// every op's path template already carries {KvsARN}, distinct per op by
// depth/segment/method) -- so unlike ListDirectoryBuckets, no two ops here
// ever share an identical path that only a hostname could disambiguate.
// Every op is reachable by path alone; gopherstack's RouteMatcher ignores
// Host entirely and every case below round-trips correctly.
//
// A systematic check for a shared method+path across all 6 ops found zero
// collisions -- GetKey/PutKey/DeleteKey share a path template (disambiguated
// by method) and ListKeys/UpdateKeys share another (ditto); every other op
// has a unique path. No *required dynamic* (non-template) member -- the
// s3/glacier vacuity-trap class -- was needed to disambiguate any route.
//
// Regenerate by grepping serializers.go for every
// "func (m *awsRestjson1_serializeOp<Op>) HandleSerialize" and pulling
// "request.Method" and the httpbinding.SplitURI(...) argument from its body.
func sdkRouteCases() []struct{ op, method, path string } {
	return []struct{ op, method, path string }{
		{"DeleteKey", "DELETE", "/key-value-stores/PLACEHOLDER/keys/PLACEHOLDER"},
		{"DescribeKeyValueStore", "GET", "/key-value-stores/PLACEHOLDER"},
		{"GetKey", "GET", "/key-value-stores/PLACEHOLDER/keys/PLACEHOLDER"},
		{"ListKeys", "GET", "/key-value-stores/PLACEHOLDER/keys"},
		{"PutKey", "PUT", "/key-value-stores/PLACEHOLDER/keys/PLACEHOLDER"},
		{"UpdateKeys", "POST", "/key-value-stores/PLACEHOLDER/keys"},
	}
}

// TestExtractOperation_SDKRouteTable drives every real CloudFront
// KeyValueStore op's authoritative method+path (see sdkRouteCases) through
// ExtractOperation and asserts route() (handler.go) resolves it to the right
// op, all 6 ops against this service's real op count. It then drives the
// same request through the real Handler() and asserts the response does not
// contain the exact literal "no matching operation" that Handler() emits
// under ResourceNotFoundException with HTTP 404 (handler.go:228 and :254)
// when route() fails to classify the path.
//
// "no matching operation" was grepped across every non-test .go file in
// this package and found nowhere else: every domain error instead routes
// through classifyError, whose messages are err.Error() on the shared
// services/cloudfront sentinels this package borrows (e.g.
// ErrKeyValueStoreNotFound's message is the bare string "EntityNotFound"),
// none of which contain that three-word literal. Since none of these cases'
// KvsARNs resolve to a real store in a fresh backend, every case here
// legitimately 404s on GetKeyValueStore before route() even reaches the
// per-op switch -- the assertion still exercises the routing guard, because
// route() returning "" (the only way to reach the miss sentinel) is
// evaluated before that backend lookup.
func TestExtractOperation_SDKRouteTable(t *testing.T) {
	t.Parallel()

	for _, tc := range sdkRouteCases() {
		t.Run(strings.ToLower(tc.op), func(t *testing.T) {
			t.Parallel()

			h, _ := newTestHandler(t)

			e := echo.New()
			req := httptest.NewRequest(tc.method, tc.path, nil)
			rec := httptest.NewRecorder()
			c := e.NewContext(req, rec)

			got := h.ExtractOperation(c)
			require.Equal(t, tc.op, got, "method=%s path=%s", tc.method, tc.path)

			require.NoError(t, h.Handler()(c))
			assert.NotContains(t, rec.Body.String(), "no matching operation",
				"method=%s path=%s op=%s: dispatched to the unmatched-route default", tc.method, tc.path, tc.op)
		})
	}
}
