package vpclattice

// Code in this file supports Phase 3.3 of the datalayer refactor: every
// map[string]*T resource field on InMemoryBackend is replaced with a
// *store.Table[T], following the pattern established by services/sesv2 /
// services/mediatailor (data-driven, direct/byParent-index registration --
// see pkgs/store's package doc for the underlying primitive).
//
// storedService, storedServiceNetwork, storedTargetGroup, storedSNSA,
// storedSNVA, and storedALS are all keyed by their own real ID field --
// every ID is generated by newID and is globally unique (not merely unique
// within some parent), so all six are direct registrations. storedService,
// storedServiceNetwork, and storedTargetGroup additionally carry a byName
// secondary index, replacing the servicesByName/networksByName/tgsByName
// map[string]string lookup maps the original code used for the
// create-time duplicate-name check.
//
// storedListener and storedRule are parent-nested (a listener belongs to a
// service; a rule belongs to a listener) but their IDs are themselves
// globally unique -- the original code's "serviceID/listenerID" and
// "serviceID/listenerID/ruleID" composite map keys existed only to get
// parent-scoped lookup and cascade-delete, not because the ID needed the
// parent to be unique. That matches the direct-registration-plus-byParent-
// index rule (id unique on its own, so no composite key is needed): each
// keeps its bare ID as the primary key, with an additive
// byService/byListener Index replacing the linear filter-scan (and,
// for DeleteListener's rule cascade, the key-prefix scan) the original
// List*/Delete* methods performed.
//
// Left as plain maps (not store.Table-backed): targets
// (map[string][]*storedTarget, an order-sensitive slice-map -- ListTargets
// iterates it in insertion order with no sort, which store.Index does not
// preserve), authPolicies/resourcePolicies (map[string]string, not *T), and
// tags (map[string]map[string]string, not *T). See persistence.go for how
// each is carried through Snapshot/Restore.
import (
	"github.com/blackbirdworks/gopherstack/pkgs/store"
)

func serviceKeyFn(v *storedService) string          { return v.ID }
func serviceNameIndexKeyFn(v *storedService) string { return v.Name }

func serviceNetworkKeyFn(v *storedServiceNetwork) string          { return v.ID }
func serviceNetworkNameIndexKeyFn(v *storedServiceNetwork) string { return v.Name }

func snsaKeyFn(v *storedSNSA) string { return v.ID }

func snvaKeyFn(v *storedSNVA) string { return v.ID }

func listenerKeyFn(v *storedListener) string             { return v.ID }
func listenerServiceIndexKeyFn(v *storedListener) string { return v.ServiceID }

func ruleKeyFn(v *storedRule) string              { return v.ID }
func ruleListenerIndexKeyFn(v *storedRule) string { return v.ListenerID }

func targetGroupKeyFn(v *storedTargetGroup) string          { return v.ID }
func targetGroupNameIndexKeyFn(v *storedTargetGroup) string { return v.Name }

func alsKeyFn(v *storedALS) string { return v.ID }

// registerAllTables registers every backend resource table (and its
// secondary indexes) exactly once. It must be called during construction
// only, immediately after b.registry is created -- store.Register panics on
// a duplicate name, so runtime resets go through b.registry.ResetAll()
// instead (see InMemoryBackend.Reset in backend.go).
func registerAllTables(b *InMemoryBackend) {
	b.services = store.Register(b.registry, "services", store.New(serviceKeyFn))
	b.servicesByName = b.services.AddIndex("byName", serviceNameIndexKeyFn)

	b.serviceNetworks = store.Register(b.registry, "serviceNetworks", store.New(serviceNetworkKeyFn))
	b.networksByName = b.serviceNetworks.AddIndex("byName", serviceNetworkNameIndexKeyFn)

	b.snsas = store.Register(b.registry, "snsas", store.New(snsaKeyFn))

	b.snvas = store.Register(b.registry, "snvas", store.New(snvaKeyFn))

	b.listeners = store.Register(b.registry, "listeners", store.New(listenerKeyFn))
	b.listenersByService = b.listeners.AddIndex("byService", listenerServiceIndexKeyFn)

	b.rules = store.Register(b.registry, "rules", store.New(ruleKeyFn))
	b.rulesByListener = b.rules.AddIndex("byListener", ruleListenerIndexKeyFn)

	b.targetGroups = store.Register(b.registry, "targetGroups", store.New(targetGroupKeyFn))
	b.tgsByName = b.targetGroups.AddIndex("byName", targetGroupNameIndexKeyFn)

	b.alss = store.Register(b.registry, "alss", store.New(alsKeyFn))
}
