package sagemaker_test

import (
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/labstack/echo/v5"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/blackbirdworks/gopherstack/services/sagemaker"
)

// sdkRouteCases is the authoritative X-Amz-Target for every real SageMaker
// operation, extracted from sagemaker@v1.263.2 serializers.go: each op's
// awsAwsjson11_serializeOp<Op>.HandleSerialize sets
// httpBindingEncoder.SetHeader("X-Amz-Target").String("SageMaker.<Op>") and
// always request.Request.Method = "POST" against path "/" -- SageMaker is
// JSON-RPC 1.1 (services/_PROTOCOLS.md), so unlike a REST-family service
// there is no path template to get wrong: dispatch is entirely by this one
// header. ExtractOperation and Handler() both derive the action the same
// way (TrimPrefix on "SageMaker."), so the class of bug this table can
// catch is a dispatch-table key that doesn't exactly match the real op name
// (typo, wrong case -- SageMaker is case-sensitive JSON-RPC), not a
// route-template mismatch.
//
// This table covers all 403 real SageMaker ops, which is also gopherstack's
// full implemented set (h.GetSupportedOperations(), 403/403) as of
// sagemaker@v1.263.2 -- confirmed by diffing GetSupportedOperations()
// against this exact list, zero mismatches either direction. Unlike glue's
// or cognitoidp's dispatch table, SageMaker's dispatch is a chain of
// per-family switch statements rather than a single map, so it was also
// spot-checked for "case" labels with no corresponding SDK op; the only hit
// was a false positive ("RoleArn" in an unrelated field-decoding switch in
// handler_monitoring_job_definitions.go), not a stray operation case.
//
// Regenerate by grepping serializers.go for every
// `SetHeader("X-Amz-Target").String("SageMaker.` and pulling the suffix
// after the last dot.
func sdkRouteCases() []struct{ op, target string } {
	return []struct{ op, target string }{
		{"AddAssociation", "SageMaker.AddAssociation"},
		{"AddTags", "SageMaker.AddTags"},
		{"AssociateTrialComponent", "SageMaker.AssociateTrialComponent"},
		{"AttachClusterNodeVolume", "SageMaker.AttachClusterNodeVolume"},
		{"BatchAddClusterNodes", "SageMaker.BatchAddClusterNodes"},
		{"BatchDeleteClusterNodes", "SageMaker.BatchDeleteClusterNodes"},
		{"BatchDescribeModelPackage", "SageMaker.BatchDescribeModelPackage"},
		{"BatchRebootClusterNodes", "SageMaker.BatchRebootClusterNodes"},
		{"BatchReplaceClusterNodes", "SageMaker.BatchReplaceClusterNodes"},
		{"CreateAIBenchmarkJob", "SageMaker.CreateAIBenchmarkJob"},
		{"CreateAIRecommendationJob", "SageMaker.CreateAIRecommendationJob"},
		{"CreateAIWorkloadConfig", "SageMaker.CreateAIWorkloadConfig"},
		{"CreateAction", "SageMaker.CreateAction"},
		{"CreateAlgorithm", "SageMaker.CreateAlgorithm"},
		{"CreateApp", "SageMaker.CreateApp"},
		{"CreateAppImageConfig", "SageMaker.CreateAppImageConfig"},
		{"CreateArtifact", "SageMaker.CreateArtifact"},
		{"CreateAutoMLJob", "SageMaker.CreateAutoMLJob"},
		{"CreateAutoMLJobV2", "SageMaker.CreateAutoMLJobV2"},
		{"CreateCluster", "SageMaker.CreateCluster"},
		{"CreateClusterSchedulerConfig", "SageMaker.CreateClusterSchedulerConfig"},
		{"CreateCodeRepository", "SageMaker.CreateCodeRepository"},
		{"CreateCompilationJob", "SageMaker.CreateCompilationJob"},
		{"CreateComputeQuota", "SageMaker.CreateComputeQuota"},
		{"CreateContext", "SageMaker.CreateContext"},
		{"CreateDataQualityJobDefinition", "SageMaker.CreateDataQualityJobDefinition"},
		{"CreateDeviceFleet", "SageMaker.CreateDeviceFleet"},
		{"CreateDomain", "SageMaker.CreateDomain"},
		{"CreateEdgeDeploymentPlan", "SageMaker.CreateEdgeDeploymentPlan"},
		{"CreateEdgeDeploymentStage", "SageMaker.CreateEdgeDeploymentStage"},
		{"CreateEdgePackagingJob", "SageMaker.CreateEdgePackagingJob"},
		{"CreateEndpoint", "SageMaker.CreateEndpoint"},
		{"CreateEndpointConfig", "SageMaker.CreateEndpointConfig"},
		{"CreateExperiment", "SageMaker.CreateExperiment"},
		{"CreateFeatureGroup", "SageMaker.CreateFeatureGroup"},
		{"CreateFlowDefinition", "SageMaker.CreateFlowDefinition"},
		{"CreateHub", "SageMaker.CreateHub"},
		{"CreateHubContentPresignedUrls", "SageMaker.CreateHubContentPresignedUrls"},
		{"CreateHubContentReference", "SageMaker.CreateHubContentReference"},
		{"CreateHumanTaskUi", "SageMaker.CreateHumanTaskUi"},
		{"CreateHyperParameterTuningJob", "SageMaker.CreateHyperParameterTuningJob"},
		{"CreateImage", "SageMaker.CreateImage"},
		{"CreateImageVersion", "SageMaker.CreateImageVersion"},
		{"CreateInferenceComponent", "SageMaker.CreateInferenceComponent"},
		{"CreateInferenceExperiment", "SageMaker.CreateInferenceExperiment"},
		{"CreateInferenceRecommendationsJob", "SageMaker.CreateInferenceRecommendationsJob"},
		{"CreateJob", "SageMaker.CreateJob"},
		{"CreateLabelingJob", "SageMaker.CreateLabelingJob"},
		{"CreateMlflowApp", "SageMaker.CreateMlflowApp"},
		{"CreateMlflowTrackingServer", "SageMaker.CreateMlflowTrackingServer"},
		{"CreateModel", "SageMaker.CreateModel"},
		{"CreateModelBiasJobDefinition", "SageMaker.CreateModelBiasJobDefinition"},
		{"CreateModelCard", "SageMaker.CreateModelCard"},
		{"CreateModelCardExportJob", "SageMaker.CreateModelCardExportJob"},
		{"CreateModelExplainabilityJobDefinition", "SageMaker.CreateModelExplainabilityJobDefinition"},
		{"CreateModelPackage", "SageMaker.CreateModelPackage"},
		{"CreateModelPackageGroup", "SageMaker.CreateModelPackageGroup"},
		{"CreateModelQualityJobDefinition", "SageMaker.CreateModelQualityJobDefinition"},
		{"CreateMonitoringSchedule", "SageMaker.CreateMonitoringSchedule"},
		{"CreateNotebookInstance", "SageMaker.CreateNotebookInstance"},
		{"CreateNotebookInstanceLifecycleConfig", "SageMaker.CreateNotebookInstanceLifecycleConfig"},
		{"CreateOptimizationJob", "SageMaker.CreateOptimizationJob"},
		{"CreatePartnerApp", "SageMaker.CreatePartnerApp"},
		{"CreatePartnerAppPresignedUrl", "SageMaker.CreatePartnerAppPresignedUrl"},
		{"CreatePipeline", "SageMaker.CreatePipeline"},
		{"CreatePresignedDomainUrl", "SageMaker.CreatePresignedDomainUrl"},
		{"CreatePresignedMlflowAppUrl", "SageMaker.CreatePresignedMlflowAppUrl"},
		{"CreatePresignedMlflowTrackingServerUrl", "SageMaker.CreatePresignedMlflowTrackingServerUrl"},
		{"CreatePresignedNotebookInstanceUrl", "SageMaker.CreatePresignedNotebookInstanceUrl"},
		{"CreateProcessingJob", "SageMaker.CreateProcessingJob"},
		{"CreateProject", "SageMaker.CreateProject"},
		{"CreateSpace", "SageMaker.CreateSpace"},
		{"CreateStudioLifecycleConfig", "SageMaker.CreateStudioLifecycleConfig"},
		{"CreateTrainingJob", "SageMaker.CreateTrainingJob"},
		{"CreateTrainingPlan", "SageMaker.CreateTrainingPlan"},
		{"CreateTransformJob", "SageMaker.CreateTransformJob"},
		{"CreateTrial", "SageMaker.CreateTrial"},
		{"CreateTrialComponent", "SageMaker.CreateTrialComponent"},
		{"CreateUserProfile", "SageMaker.CreateUserProfile"},
		{"CreateWorkforce", "SageMaker.CreateWorkforce"},
		{"CreateWorkteam", "SageMaker.CreateWorkteam"},
		{"DeleteAIBenchmarkJob", "SageMaker.DeleteAIBenchmarkJob"},
		{"DeleteAIRecommendationJob", "SageMaker.DeleteAIRecommendationJob"},
		{"DeleteAIWorkloadConfig", "SageMaker.DeleteAIWorkloadConfig"},
		{"DeleteAction", "SageMaker.DeleteAction"},
		{"DeleteAlgorithm", "SageMaker.DeleteAlgorithm"},
		{"DeleteApp", "SageMaker.DeleteApp"},
		{"DeleteAppImageConfig", "SageMaker.DeleteAppImageConfig"},
		{"DeleteArtifact", "SageMaker.DeleteArtifact"},
		{"DeleteAssociation", "SageMaker.DeleteAssociation"},
		{"DeleteCluster", "SageMaker.DeleteCluster"},
		{"DeleteClusterSchedulerConfig", "SageMaker.DeleteClusterSchedulerConfig"},
		{"DeleteCodeRepository", "SageMaker.DeleteCodeRepository"},
		{"DeleteCompilationJob", "SageMaker.DeleteCompilationJob"},
		{"DeleteComputeQuota", "SageMaker.DeleteComputeQuota"},
		{"DeleteContext", "SageMaker.DeleteContext"},
		{"DeleteDataQualityJobDefinition", "SageMaker.DeleteDataQualityJobDefinition"},
		{"DeleteDeviceFleet", "SageMaker.DeleteDeviceFleet"},
		{"DeleteDomain", "SageMaker.DeleteDomain"},
		{"DeleteEdgeDeploymentPlan", "SageMaker.DeleteEdgeDeploymentPlan"},
		{"DeleteEdgeDeploymentStage", "SageMaker.DeleteEdgeDeploymentStage"},
		{"DeleteEndpoint", "SageMaker.DeleteEndpoint"},
		{"DeleteEndpointConfig", "SageMaker.DeleteEndpointConfig"},
		{"DeleteExperiment", "SageMaker.DeleteExperiment"},
		{"DeleteFeatureGroup", "SageMaker.DeleteFeatureGroup"},
		{"DeleteFlowDefinition", "SageMaker.DeleteFlowDefinition"},
		{"DeleteHub", "SageMaker.DeleteHub"},
		{"DeleteHubContent", "SageMaker.DeleteHubContent"},
		{"DeleteHubContentReference", "SageMaker.DeleteHubContentReference"},
		{"DeleteHumanTaskUi", "SageMaker.DeleteHumanTaskUi"},
		{"DeleteHyperParameterTuningJob", "SageMaker.DeleteHyperParameterTuningJob"},
		{"DeleteImage", "SageMaker.DeleteImage"},
		{"DeleteImageVersion", "SageMaker.DeleteImageVersion"},
		{"DeleteInferenceComponent", "SageMaker.DeleteInferenceComponent"},
		{"DeleteInferenceExperiment", "SageMaker.DeleteInferenceExperiment"},
		{"DeleteJob", "SageMaker.DeleteJob"},
		{"DeleteMlflowApp", "SageMaker.DeleteMlflowApp"},
		{"DeleteMlflowTrackingServer", "SageMaker.DeleteMlflowTrackingServer"},
		{"DeleteModel", "SageMaker.DeleteModel"},
		{"DeleteModelBiasJobDefinition", "SageMaker.DeleteModelBiasJobDefinition"},
		{"DeleteModelCard", "SageMaker.DeleteModelCard"},
		{"DeleteModelExplainabilityJobDefinition", "SageMaker.DeleteModelExplainabilityJobDefinition"},
		{"DeleteModelPackage", "SageMaker.DeleteModelPackage"},
		{"DeleteModelPackageGroup", "SageMaker.DeleteModelPackageGroup"},
		{"DeleteModelPackageGroupPolicy", "SageMaker.DeleteModelPackageGroupPolicy"},
		{"DeleteModelQualityJobDefinition", "SageMaker.DeleteModelQualityJobDefinition"},
		{"DeleteMonitoringSchedule", "SageMaker.DeleteMonitoringSchedule"},
		{"DeleteNotebookInstance", "SageMaker.DeleteNotebookInstance"},
		{"DeleteNotebookInstanceLifecycleConfig", "SageMaker.DeleteNotebookInstanceLifecycleConfig"},
		{"DeleteOptimizationJob", "SageMaker.DeleteOptimizationJob"},
		{"DeletePartnerApp", "SageMaker.DeletePartnerApp"},
		{"DeletePipeline", "SageMaker.DeletePipeline"},
		{"DeleteProcessingJob", "SageMaker.DeleteProcessingJob"},
		{"DeleteProject", "SageMaker.DeleteProject"},
		{"DeleteSpace", "SageMaker.DeleteSpace"},
		{"DeleteStudioLifecycleConfig", "SageMaker.DeleteStudioLifecycleConfig"},
		{"DeleteTags", "SageMaker.DeleteTags"},
		{"DeleteTrainingJob", "SageMaker.DeleteTrainingJob"},
		{"DeleteTrial", "SageMaker.DeleteTrial"},
		{"DeleteTrialComponent", "SageMaker.DeleteTrialComponent"},
		{"DeleteUserProfile", "SageMaker.DeleteUserProfile"},
		{"DeleteWorkforce", "SageMaker.DeleteWorkforce"},
		{"DeleteWorkteam", "SageMaker.DeleteWorkteam"},
		{"DeregisterDevices", "SageMaker.DeregisterDevices"},
		{"DescribeAIBenchmarkJob", "SageMaker.DescribeAIBenchmarkJob"},
		{"DescribeAIRecommendationJob", "SageMaker.DescribeAIRecommendationJob"},
		{"DescribeAIWorkloadConfig", "SageMaker.DescribeAIWorkloadConfig"},
		{"DescribeAction", "SageMaker.DescribeAction"},
		{"DescribeAlgorithm", "SageMaker.DescribeAlgorithm"},
		{"DescribeApp", "SageMaker.DescribeApp"},
		{"DescribeAppImageConfig", "SageMaker.DescribeAppImageConfig"},
		{"DescribeArtifact", "SageMaker.DescribeArtifact"},
		{"DescribeAutoMLJob", "SageMaker.DescribeAutoMLJob"},
		{"DescribeAutoMLJobV2", "SageMaker.DescribeAutoMLJobV2"},
		{"DescribeCluster", "SageMaker.DescribeCluster"},
		{"DescribeClusterEvent", "SageMaker.DescribeClusterEvent"},
		{"DescribeClusterNode", "SageMaker.DescribeClusterNode"},
		{"DescribeClusterSchedulerConfig", "SageMaker.DescribeClusterSchedulerConfig"},
		{"DescribeCodeRepository", "SageMaker.DescribeCodeRepository"},
		{"DescribeCompilationJob", "SageMaker.DescribeCompilationJob"},
		{"DescribeComputeQuota", "SageMaker.DescribeComputeQuota"},
		{"DescribeContext", "SageMaker.DescribeContext"},
		{"DescribeDataQualityJobDefinition", "SageMaker.DescribeDataQualityJobDefinition"},
		{"DescribeDevice", "SageMaker.DescribeDevice"},
		{"DescribeDeviceFleet", "SageMaker.DescribeDeviceFleet"},
		{"DescribeDomain", "SageMaker.DescribeDomain"},
		{"DescribeEdgeDeploymentPlan", "SageMaker.DescribeEdgeDeploymentPlan"},
		{"DescribeEdgePackagingJob", "SageMaker.DescribeEdgePackagingJob"},
		{"DescribeEndpoint", "SageMaker.DescribeEndpoint"},
		{"DescribeEndpointConfig", "SageMaker.DescribeEndpointConfig"},
		{"DescribeExperiment", "SageMaker.DescribeExperiment"},
		{"DescribeFeatureGroup", "SageMaker.DescribeFeatureGroup"},
		{"DescribeFeatureMetadata", "SageMaker.DescribeFeatureMetadata"},
		{"DescribeFlowDefinition", "SageMaker.DescribeFlowDefinition"},
		{"DescribeHub", "SageMaker.DescribeHub"},
		{"DescribeHubContent", "SageMaker.DescribeHubContent"},
		{"DescribeHumanTaskUi", "SageMaker.DescribeHumanTaskUi"},
		{"DescribeHyperParameterTuningJob", "SageMaker.DescribeHyperParameterTuningJob"},
		{"DescribeImage", "SageMaker.DescribeImage"},
		{"DescribeImageVersion", "SageMaker.DescribeImageVersion"},
		{"DescribeInferenceComponent", "SageMaker.DescribeInferenceComponent"},
		{"DescribeInferenceExperiment", "SageMaker.DescribeInferenceExperiment"},
		{"DescribeInferenceRecommendationsJob", "SageMaker.DescribeInferenceRecommendationsJob"},
		{"DescribeJob", "SageMaker.DescribeJob"},
		{"DescribeJobSchemaVersion", "SageMaker.DescribeJobSchemaVersion"},
		{"DescribeLabelingJob", "SageMaker.DescribeLabelingJob"},
		{"DescribeLineageGroup", "SageMaker.DescribeLineageGroup"},
		{"DescribeMlflowApp", "SageMaker.DescribeMlflowApp"},
		{"DescribeMlflowTrackingServer", "SageMaker.DescribeMlflowTrackingServer"},
		{"DescribeModel", "SageMaker.DescribeModel"},
		{"DescribeModelBiasJobDefinition", "SageMaker.DescribeModelBiasJobDefinition"},
		{"DescribeModelCard", "SageMaker.DescribeModelCard"},
		{"DescribeModelCardExportJob", "SageMaker.DescribeModelCardExportJob"},
		{"DescribeModelExplainabilityJobDefinition", "SageMaker.DescribeModelExplainabilityJobDefinition"},
		{"DescribeModelPackage", "SageMaker.DescribeModelPackage"},
		{"DescribeModelPackageGroup", "SageMaker.DescribeModelPackageGroup"},
		{"DescribeModelQualityJobDefinition", "SageMaker.DescribeModelQualityJobDefinition"},
		{"DescribeMonitoringSchedule", "SageMaker.DescribeMonitoringSchedule"},
		{"DescribeNotebookInstance", "SageMaker.DescribeNotebookInstance"},
		{"DescribeNotebookInstanceLifecycleConfig", "SageMaker.DescribeNotebookInstanceLifecycleConfig"},
		{"DescribeOptimizationJob", "SageMaker.DescribeOptimizationJob"},
		{"DescribePartnerApp", "SageMaker.DescribePartnerApp"},
		{"DescribePipeline", "SageMaker.DescribePipeline"},
		{"DescribePipelineDefinitionForExecution", "SageMaker.DescribePipelineDefinitionForExecution"},
		{"DescribePipelineExecution", "SageMaker.DescribePipelineExecution"},
		{"DescribeProcessingJob", "SageMaker.DescribeProcessingJob"},
		{"DescribeProject", "SageMaker.DescribeProject"},
		{"DescribeReservedCapacity", "SageMaker.DescribeReservedCapacity"},
		{"DescribeSpace", "SageMaker.DescribeSpace"},
		{"DescribeStudioLifecycleConfig", "SageMaker.DescribeStudioLifecycleConfig"},
		{"DescribeSubscribedWorkteam", "SageMaker.DescribeSubscribedWorkteam"},
		{"DescribeTrainingJob", "SageMaker.DescribeTrainingJob"},
		{"DescribeTrainingPlan", "SageMaker.DescribeTrainingPlan"},
		{"DescribeTrainingPlanExtensionHistory", "SageMaker.DescribeTrainingPlanExtensionHistory"},
		{"DescribeTransformJob", "SageMaker.DescribeTransformJob"},
		{"DescribeTrial", "SageMaker.DescribeTrial"},
		{"DescribeTrialComponent", "SageMaker.DescribeTrialComponent"},
		{"DescribeUserProfile", "SageMaker.DescribeUserProfile"},
		{"DescribeWorkforce", "SageMaker.DescribeWorkforce"},
		{"DescribeWorkteam", "SageMaker.DescribeWorkteam"},
		{"DetachClusterNodeVolume", "SageMaker.DetachClusterNodeVolume"},
		{"DisableSagemakerServicecatalogPortfolio", "SageMaker.DisableSagemakerServicecatalogPortfolio"},
		{"DisassociateTrialComponent", "SageMaker.DisassociateTrialComponent"},
		{"EnableSagemakerServicecatalogPortfolio", "SageMaker.EnableSagemakerServicecatalogPortfolio"},
		{"ExtendTrainingPlan", "SageMaker.ExtendTrainingPlan"},
		{"GetDeviceFleetReport", "SageMaker.GetDeviceFleetReport"},
		{"GetLineageGroupPolicy", "SageMaker.GetLineageGroupPolicy"},
		{"GetModelPackageGroupPolicy", "SageMaker.GetModelPackageGroupPolicy"},
		{"GetSagemakerServicecatalogPortfolioStatus", "SageMaker.GetSagemakerServicecatalogPortfolioStatus"},
		{"GetScalingConfigurationRecommendation", "SageMaker.GetScalingConfigurationRecommendation"},
		{"GetSearchSuggestions", "SageMaker.GetSearchSuggestions"},
		{"ImportHubContent", "SageMaker.ImportHubContent"},
		{"ListAIBenchmarkJobs", "SageMaker.ListAIBenchmarkJobs"},
		{"ListAIRecommendationJobs", "SageMaker.ListAIRecommendationJobs"},
		{"ListAIWorkloadConfigs", "SageMaker.ListAIWorkloadConfigs"},
		{"ListActions", "SageMaker.ListActions"},
		{"ListAlgorithms", "SageMaker.ListAlgorithms"},
		{"ListAliases", "SageMaker.ListAliases"},
		{"ListAppImageConfigs", "SageMaker.ListAppImageConfigs"},
		{"ListApps", "SageMaker.ListApps"},
		{"ListArtifacts", "SageMaker.ListArtifacts"},
		{"ListAssociations", "SageMaker.ListAssociations"},
		{"ListAutoMLJobs", "SageMaker.ListAutoMLJobs"},
		{"ListCandidatesForAutoMLJob", "SageMaker.ListCandidatesForAutoMLJob"},
		{"ListClusterEvents", "SageMaker.ListClusterEvents"},
		{"ListClusterNodes", "SageMaker.ListClusterNodes"},
		{"ListClusterSchedulerConfigs", "SageMaker.ListClusterSchedulerConfigs"},
		{"ListClusters", "SageMaker.ListClusters"},
		{"ListCodeRepositories", "SageMaker.ListCodeRepositories"},
		{"ListCompilationJobs", "SageMaker.ListCompilationJobs"},
		{"ListComputeQuotas", "SageMaker.ListComputeQuotas"},
		{"ListContexts", "SageMaker.ListContexts"},
		{"ListDataQualityJobDefinitions", "SageMaker.ListDataQualityJobDefinitions"},
		{"ListDeviceFleets", "SageMaker.ListDeviceFleets"},
		{"ListDevices", "SageMaker.ListDevices"},
		{"ListDomains", "SageMaker.ListDomains"},
		{"ListEdgeDeploymentPlans", "SageMaker.ListEdgeDeploymentPlans"},
		{"ListEdgePackagingJobs", "SageMaker.ListEdgePackagingJobs"},
		{"ListEndpointConfigs", "SageMaker.ListEndpointConfigs"},
		{"ListEndpoints", "SageMaker.ListEndpoints"},
		{"ListExperiments", "SageMaker.ListExperiments"},
		{"ListFeatureGroups", "SageMaker.ListFeatureGroups"},
		{"ListFlowDefinitions", "SageMaker.ListFlowDefinitions"},
		{"ListHubContentVersions", "SageMaker.ListHubContentVersions"},
		{"ListHubContents", "SageMaker.ListHubContents"},
		{"ListHubs", "SageMaker.ListHubs"},
		{"ListHumanTaskUis", "SageMaker.ListHumanTaskUis"},
		{"ListHyperParameterTuningJobs", "SageMaker.ListHyperParameterTuningJobs"},
		{"ListImageVersions", "SageMaker.ListImageVersions"},
		{"ListImages", "SageMaker.ListImages"},
		{"ListInferenceComponents", "SageMaker.ListInferenceComponents"},
		{"ListInferenceExperiments", "SageMaker.ListInferenceExperiments"},
		{"ListInferenceRecommendationsJobSteps", "SageMaker.ListInferenceRecommendationsJobSteps"},
		{"ListInferenceRecommendationsJobs", "SageMaker.ListInferenceRecommendationsJobs"},
		{"ListJobSchemaVersions", "SageMaker.ListJobSchemaVersions"},
		{"ListJobs", "SageMaker.ListJobs"},
		{"ListLabelingJobs", "SageMaker.ListLabelingJobs"},
		{"ListLabelingJobsForWorkteam", "SageMaker.ListLabelingJobsForWorkteam"},
		{"ListLineageGroups", "SageMaker.ListLineageGroups"},
		{"ListMlflowApps", "SageMaker.ListMlflowApps"},
		{"ListMlflowTrackingServers", "SageMaker.ListMlflowTrackingServers"},
		{"ListModelBiasJobDefinitions", "SageMaker.ListModelBiasJobDefinitions"},
		{"ListModelCardExportJobs", "SageMaker.ListModelCardExportJobs"},
		{"ListModelCardVersions", "SageMaker.ListModelCardVersions"},
		{"ListModelCards", "SageMaker.ListModelCards"},
		{"ListModelExplainabilityJobDefinitions", "SageMaker.ListModelExplainabilityJobDefinitions"},
		{"ListModelMetadata", "SageMaker.ListModelMetadata"},
		{"ListModelPackageGroups", "SageMaker.ListModelPackageGroups"},
		{"ListModelPackages", "SageMaker.ListModelPackages"},
		{"ListModelQualityJobDefinitions", "SageMaker.ListModelQualityJobDefinitions"},
		{"ListModels", "SageMaker.ListModels"},
		{"ListMonitoringAlertHistory", "SageMaker.ListMonitoringAlertHistory"},
		{"ListMonitoringAlerts", "SageMaker.ListMonitoringAlerts"},
		{"ListMonitoringExecutions", "SageMaker.ListMonitoringExecutions"},
		{"ListMonitoringSchedules", "SageMaker.ListMonitoringSchedules"},
		{"ListNotebookInstanceLifecycleConfigs", "SageMaker.ListNotebookInstanceLifecycleConfigs"},
		{"ListNotebookInstances", "SageMaker.ListNotebookInstances"},
		{"ListOptimizationJobs", "SageMaker.ListOptimizationJobs"},
		{"ListPartnerApps", "SageMaker.ListPartnerApps"},
		{"ListPipelineExecutionSteps", "SageMaker.ListPipelineExecutionSteps"},
		{"ListPipelineExecutions", "SageMaker.ListPipelineExecutions"},
		{"ListPipelineParametersForExecution", "SageMaker.ListPipelineParametersForExecution"},
		{"ListPipelineVersions", "SageMaker.ListPipelineVersions"},
		{"ListPipelines", "SageMaker.ListPipelines"},
		{"ListProcessingJobs", "SageMaker.ListProcessingJobs"},
		{"ListProjects", "SageMaker.ListProjects"},
		{"ListResourceCatalogs", "SageMaker.ListResourceCatalogs"},
		{"ListSpaces", "SageMaker.ListSpaces"},
		{"ListStageDevices", "SageMaker.ListStageDevices"},
		{"ListStudioLifecycleConfigs", "SageMaker.ListStudioLifecycleConfigs"},
		{"ListSubscribedWorkteams", "SageMaker.ListSubscribedWorkteams"},
		{"ListTags", "SageMaker.ListTags"},
		{"ListTrainingJobs", "SageMaker.ListTrainingJobs"},
		{"ListTrainingJobsForHyperParameterTuningJob", "SageMaker.ListTrainingJobsForHyperParameterTuningJob"},
		{"ListTrainingPlans", "SageMaker.ListTrainingPlans"},
		{"ListTransformJobs", "SageMaker.ListTransformJobs"},
		{"ListTrialComponents", "SageMaker.ListTrialComponents"},
		{"ListTrials", "SageMaker.ListTrials"},
		{"ListUltraServersByReservedCapacity", "SageMaker.ListUltraServersByReservedCapacity"},
		{"ListUserProfiles", "SageMaker.ListUserProfiles"},
		{"ListWorkforces", "SageMaker.ListWorkforces"},
		{"ListWorkteams", "SageMaker.ListWorkteams"},
		{"PutModelPackageGroupPolicy", "SageMaker.PutModelPackageGroupPolicy"},
		{"QueryLineage", "SageMaker.QueryLineage"},
		{"RegisterDevices", "SageMaker.RegisterDevices"},
		{"RenderUiTemplate", "SageMaker.RenderUiTemplate"},
		{"RetryPipelineExecution", "SageMaker.RetryPipelineExecution"},
		{"Search", "SageMaker.Search"},
		{"SearchTrainingPlanOfferings", "SageMaker.SearchTrainingPlanOfferings"},
		{"SendPipelineExecutionStepFailure", "SageMaker.SendPipelineExecutionStepFailure"},
		{"SendPipelineExecutionStepSuccess", "SageMaker.SendPipelineExecutionStepSuccess"},
		{"StartClusterHealthCheck", "SageMaker.StartClusterHealthCheck"},
		{"StartEdgeDeploymentStage", "SageMaker.StartEdgeDeploymentStage"},
		{"StartInferenceExperiment", "SageMaker.StartInferenceExperiment"},
		{"StartMlflowTrackingServer", "SageMaker.StartMlflowTrackingServer"},
		{"StartMonitoringSchedule", "SageMaker.StartMonitoringSchedule"},
		{"StartNotebookInstance", "SageMaker.StartNotebookInstance"},
		{"StartPipelineExecution", "SageMaker.StartPipelineExecution"},
		{"StartSession", "SageMaker.StartSession"},
		{"StopAIBenchmarkJob", "SageMaker.StopAIBenchmarkJob"},
		{"StopAIRecommendationJob", "SageMaker.StopAIRecommendationJob"},
		{"StopAutoMLJob", "SageMaker.StopAutoMLJob"},
		{"StopCompilationJob", "SageMaker.StopCompilationJob"},
		{"StopEdgeDeploymentStage", "SageMaker.StopEdgeDeploymentStage"},
		{"StopEdgePackagingJob", "SageMaker.StopEdgePackagingJob"},
		{"StopHyperParameterTuningJob", "SageMaker.StopHyperParameterTuningJob"},
		{"StopInferenceExperiment", "SageMaker.StopInferenceExperiment"},
		{"StopInferenceRecommendationsJob", "SageMaker.StopInferenceRecommendationsJob"},
		{"StopJob", "SageMaker.StopJob"},
		{"StopLabelingJob", "SageMaker.StopLabelingJob"},
		{"StopMlflowTrackingServer", "SageMaker.StopMlflowTrackingServer"},
		{"StopMonitoringSchedule", "SageMaker.StopMonitoringSchedule"},
		{"StopNotebookInstance", "SageMaker.StopNotebookInstance"},
		{"StopOptimizationJob", "SageMaker.StopOptimizationJob"},
		{"StopPipelineExecution", "SageMaker.StopPipelineExecution"},
		{"StopProcessingJob", "SageMaker.StopProcessingJob"},
		{"StopTrainingJob", "SageMaker.StopTrainingJob"},
		{"StopTransformJob", "SageMaker.StopTransformJob"},
		{"UpdateAction", "SageMaker.UpdateAction"},
		{"UpdateAppImageConfig", "SageMaker.UpdateAppImageConfig"},
		{"UpdateArtifact", "SageMaker.UpdateArtifact"},
		{"UpdateCluster", "SageMaker.UpdateCluster"},
		{"UpdateClusterSchedulerConfig", "SageMaker.UpdateClusterSchedulerConfig"},
		{"UpdateClusterSoftware", "SageMaker.UpdateClusterSoftware"},
		{"UpdateCodeRepository", "SageMaker.UpdateCodeRepository"},
		{"UpdateComputeQuota", "SageMaker.UpdateComputeQuota"},
		{"UpdateContext", "SageMaker.UpdateContext"},
		{"UpdateDeviceFleet", "SageMaker.UpdateDeviceFleet"},
		{"UpdateDevices", "SageMaker.UpdateDevices"},
		{"UpdateDomain", "SageMaker.UpdateDomain"},
		{"UpdateEndpoint", "SageMaker.UpdateEndpoint"},
		{"UpdateEndpointWeightsAndCapacities", "SageMaker.UpdateEndpointWeightsAndCapacities"},
		{"UpdateExperiment", "SageMaker.UpdateExperiment"},
		{"UpdateFeatureGroup", "SageMaker.UpdateFeatureGroup"},
		{"UpdateFeatureMetadata", "SageMaker.UpdateFeatureMetadata"},
		{"UpdateHub", "SageMaker.UpdateHub"},
		{"UpdateHubContent", "SageMaker.UpdateHubContent"},
		{"UpdateHubContentReference", "SageMaker.UpdateHubContentReference"},
		{"UpdateImage", "SageMaker.UpdateImage"},
		{"UpdateImageVersion", "SageMaker.UpdateImageVersion"},
		{"UpdateInferenceComponent", "SageMaker.UpdateInferenceComponent"},
		{"UpdateInferenceComponentRuntimeConfig", "SageMaker.UpdateInferenceComponentRuntimeConfig"},
		{"UpdateInferenceExperiment", "SageMaker.UpdateInferenceExperiment"},
		{"UpdateMlflowApp", "SageMaker.UpdateMlflowApp"},
		{"UpdateMlflowTrackingServer", "SageMaker.UpdateMlflowTrackingServer"},
		{"UpdateModelCard", "SageMaker.UpdateModelCard"},
		{"UpdateModelPackage", "SageMaker.UpdateModelPackage"},
		{"UpdateMonitoringAlert", "SageMaker.UpdateMonitoringAlert"},
		{"UpdateMonitoringSchedule", "SageMaker.UpdateMonitoringSchedule"},
		{"UpdateNotebookInstance", "SageMaker.UpdateNotebookInstance"},
		{"UpdateNotebookInstanceLifecycleConfig", "SageMaker.UpdateNotebookInstanceLifecycleConfig"},
		{"UpdatePartnerApp", "SageMaker.UpdatePartnerApp"},
		{"UpdatePipeline", "SageMaker.UpdatePipeline"},
		{"UpdatePipelineExecution", "SageMaker.UpdatePipelineExecution"},
		{"UpdatePipelineVersion", "SageMaker.UpdatePipelineVersion"},
		{"UpdateProject", "SageMaker.UpdateProject"},
		{"UpdateSpace", "SageMaker.UpdateSpace"},
		{"UpdateTrainingJob", "SageMaker.UpdateTrainingJob"},
		{"UpdateTrial", "SageMaker.UpdateTrial"},
		{"UpdateTrialComponent", "SageMaker.UpdateTrialComponent"},
		{"UpdateUserProfile", "SageMaker.UpdateUserProfile"},
		{"UpdateWorkforce", "SageMaker.UpdateWorkforce"},
		{"UpdateWorkteam", "SageMaker.UpdateWorkteam"},
	}
}

// TestExtractOperation_SDKRouteTable drives every real SageMaker operation's
// authoritative X-Amz-Target through ExtractOperation and Handler(),
// asserting the header resolves to the right op name and that Handler()
// does not fall through to the "unknown action" sentinel that a
// dispatch-table key mismatch would produce. "unknown action" (not
// "UnknownOperationException") is SageMaker's real miss text -- see
// errUnknownAction in handler.go -- and it has exactly one production call
// site (the fallthrough at the end of dispatchNewOps), so it cannot
// collide with a legitimate error on this all-empty-body table.
func TestExtractOperation_SDKRouteTable(t *testing.T) {
	t.Parallel()

	for _, tc := range sdkRouteCases() {
		t.Run(strings.ToLower(tc.op), func(t *testing.T) {
			t.Parallel()

			backend := sagemaker.NewInMemoryBackend("000000000000", "us-east-1")
			h := sagemaker.NewHandler(backend)
			e := echo.New()
			req := httptest.NewRequest(http.MethodPost, "/", strings.NewReader("{}"))
			req.Header.Set("X-Amz-Target", tc.target)
			rec := httptest.NewRecorder()
			c := e.NewContext(req, rec)

			got := h.ExtractOperation(c)
			assert.Equal(t, tc.op, got)

			require.NoError(t, h.Handler()(c))
			assert.NotContains(t, rec.Body.String(), "unknown action",
				"target=%s op=%s: dispatched to the unmatched-route handler", tc.target, tc.op)
		})
	}
}
