package sagemaker

// Shared ARN / status key constants used across response-building code in
// multiple operation families.
const (
	keyAppImageConfigArn           = "AppImageConfigArn"
	keyClusterSchedulerConfigArn   = "ClusterSchedulerConfigArn"
	keyCodeRepositoryArn           = "CodeRepositoryArn"
	keyComputeQuotaArn             = "ComputeQuotaArn"
	keyJobDefinitionArn            = "JobDefinitionArn"
	keyJobDefinitionName           = "JobDefinitionName"
	keyDomainArn                   = "DomainArn"
	keyEdgeDeploymentPlanArn       = "EdgeDeploymentPlanArn"
	keyEdgeDeploymentPlanName      = "EdgeDeploymentPlanName"
	keyDeviceName                  = "DeviceName"
	keyExperimentArn               = "ExperimentArn"
	keyFeatureGroupArn             = "FeatureGroupArn"
	keyFlowDefinitionArn           = "FlowDefinitionArn"
	keyHubArn                      = "HubArn"
	keyHubContentArn               = "HubContentArn"
	keyHumanTaskUIArn              = "HumanTaskUiArn"
	keyImageArn                    = "ImageArn"
	keyImageVersionArn             = "ImageVersionArn"
	keyInferenceComponentArn       = "InferenceComponentArn"
	keyInferenceExperimentArn      = "InferenceExperimentArn"
	keyLabelingJobArn              = "LabelingJobArn"
	keyModelCardArn                = "ModelCardArn"
	keyModelCardExportJobArn       = "ModelCardExportJobArn"
	keyModelPackageArn             = "ModelPackageArn"
	keyModelPackageGroupArn        = "ModelPackageGroupArn"
	keyMonitoringScheduleArn       = "MonitoringScheduleArn"
	keyNotebookLifecycleConfigArn  = "NotebookInstanceLifecycleConfigArn"
	keyOptimizationJobArn          = "OptimizationJobArn"
	keyPipelineArn                 = "PipelineArn"
	keyPipelineExecutionArn        = "PipelineExecutionArn"
	keyProcessingJobArn            = "ProcessingJobArn"
	keyProjectArn                  = "ProjectArn"
	keySpaceArn                    = "SpaceArn"
	keyStudioLifecycleConfigArn    = "StudioLifecycleConfigArn"
	keyTrackingServerArn           = "TrackingServerArn"
	keyTrainingPlanArn             = "TrainingPlanArn"
	keyTrialArn                    = "TrialArn"
	keyTrialComponentArn           = "TrialComponentArn"
	keyUserProfileArn              = "UserProfileArn"
	keyWorkforceArn                = "WorkforceArn"
	keyAuthorizedURL               = "AuthorizedUrl"
	keyGenericArn                  = "Arn"
	keyGenericName                 = "Name"
	keyAppArn                      = "AppArn"
	keyFeatureGroupStatus          = "FeatureGroupStatus"
	keyMonitoringScheduleName      = "MonitoringScheduleName"
	keyPipelineExecutionStatus     = "PipelineExecutionStatus"
	keyModelCardVersion            = "ModelCardVersion"
	keyModelApprovalStatus         = "ModelApprovalStatus"
	keyFeatureGroupName            = "FeatureGroupName"
	keyFeatureDefinitions          = "FeatureDefinitions"
	keyRecordIdentifierFeatureName = "RecordIdentifierFeatureName"
	keyEventTimeFeatureName        = "EventTimeFeatureName"
	keyMonitoringAlertName         = "MonitoringAlertName"
	keyTrainingJobSummaries        = "TrainingJobSummaries"
	keyDeviceFleetName             = "DeviceFleetName"
	keyStatus                      = "Status"
	statusInService                = clusterStatusInService
	statusCreated                  = "Created"
	statusActive                   = "Active"
)
