package rds

import "sort"

// GetSupportedOperations returns supported RDS operations.
func (h *Handler) GetSupportedOperations() []string {
	ops := make([]string, 0, len(supportedOpsBase())+len(supportedOpsExtended()))
	ops = append(ops, supportedOpsBase()...)
	ops = append(ops, supportedOpsExtended()...)
	sort.Strings(ops)

	return ops
}

func supportedOpsBase() []string {
	return []string{
		"AddRoleToDBCluster",
		"AddRoleToDBInstance",
		"AddSourceIdentifierToSubscription",
		"AddTagsToResource",
		"ApplyPendingMaintenanceAction",
		"AuthorizeDBSecurityGroupIngress",
		"BacktrackDBCluster",
		"CancelExportTask",
		"CopyDBClusterParameterGroup",
		"CopyDBClusterSnapshot",
		"CopyDBParameterGroup",
		"CopyDBSnapshot",
		"CopyOptionGroup",
		"CreateBlueGreenDeployment",
		"CreateDBCluster",
		"CreateDBClusterEndpoint",
		"CreateDBClusterParameterGroup",
		"CreateDBClusterSnapshot",
		"CreateDBInstance",
		"CreateDBInstanceReadReplica",
		"CreateDBParameterGroup",
		"CreateDBProxy",
		"CreateDBProxyEndpoint",
		"CreateDBSecurityGroup",
		"CreateDBSnapshot",
		"CreateDBSubnetGroup",
		"CreateEventSubscription",
		"CreateGlobalCluster",
		"CreateOptionGroup",
		"DeleteBlueGreenDeployment",
		"DeleteDBCluster",
		"DeleteDBClusterEndpoint",
		"DeleteDBClusterParameterGroup",
		"DeleteDBClusterSnapshot",
		"DeleteDBInstance",
		"DeleteDBParameterGroup",
		"DeleteDBProxy",
		"DeleteDBProxyEndpoint",
		"DeleteDBSecurityGroup",
		"DeleteDBSnapshot",
		"DeleteDBSubnetGroup",
		"DeleteEventSubscription",
		"DeleteGlobalCluster",
		"DeleteOptionGroup",
		"DeregisterDBProxyTargets",
		"DescribeAccountAttributes",
		"DescribeBlueGreenDeployments",
		"DescribeCertificates",
		"DescribeDBClusterBacktracks",
		"DescribeDBClusterEndpoints",
		"DescribeDBClusterParameterGroups",
		"DescribeDBClusterParameters",
		"DescribeDBClusterSnapshotAttributes",
		"DescribeDBClusterSnapshots",
		"DescribeCustomDBEngineVersions",
		"DescribeDBClusters",
		"DescribeDBEngineVersions",
		"DescribeDBInstances",
		"DescribeDBLogFiles",
		"DescribeDBMajorEngineVersions",
		"DescribeDBParameterGroups",
		"DescribeDBParameters",
		"DescribeDBProxies",
		"DescribeDBProxyEndpoints",
		"DescribeDBProxyTargetGroups",
		"DescribeDBProxyTargets",
		"DescribeDBRecommendations",
		"DescribeDBSecurityGroups",
		"DescribeDBSnapshotAttributes",
		"DescribeDBSnapshots",
		"DescribeDBSubnetGroups",
	}
}

func supportedOpsExtended() []string {
	return []string{
		"DescribeEngineDefaultClusterParameters",
		"DescribeEngineDefaultParameters",
		"DescribeEventCategories",
		"DescribeEventSubscriptions",
		"DescribeEvents",
		"DescribeExportTasks",
		opDescribeGlobalClusters,
		"DescribeOptionGroupOptions",
		"DescribeOptionGroups",
		"DescribeOrderableDBInstanceOptions",
		"DescribePendingMaintenanceActions",
		"DescribeReservedDBInstances",
		"DescribeReservedDBInstancesOfferings",
		"DescribeSourceRegions",
		"DescribeValidDBInstanceModifications",
		"DisableHttpEndpoint",
		"DownloadDBLogFilePortion",
		"EnableHttpEndpoint",
		"FailoverDBCluster",
		"FailoverGlobalCluster",
		"ListTagsForResource",
		"ModifyActivityStream",
		"ModifyCertificates",
		"ModifyCurrentDBClusterCapacity",
		"ModifyDBCluster",
		"ModifyDBClusterEndpoint",
		"ModifyDBClusterParameterGroup",
		"ModifyDBClusterSnapshotAttribute",
		"ModifyDBInstance",
		"ModifyDBParameterGroup",
		"ModifyDBProxy",
		"ModifyDBProxyEndpoint",
		"ModifyDBProxyTargetGroup",
		"ModifyDBRecommendation",
		"ModifyDBSnapshot",
		"ModifyDBSnapshotAttribute",
		"ModifyDBSubnetGroup",
		"ModifyEventSubscription",
		"ModifyGlobalCluster",
		"ModifyOptionGroup",
		"PromoteReadReplica",
		"PromoteReadReplicaDBCluster",
		"PurchaseReservedDBInstancesOffering",
		"RebootDBCluster",
		"RebootDBInstance",
		"RegisterDBProxyTargets",
		"RemoveFromGlobalCluster",
		"RemoveRoleFromDBCluster",
		"RemoveRoleFromDBInstance",
		"RemoveSourceIdentifierFromSubscription",
		"RemoveTagsFromResource",
		"ResetDBClusterParameterGroup",
		"ResetDBParameterGroup",
		"RestoreDBClusterFromS3",
		"RestoreDBClusterFromSnapshot",
		"RestoreDBClusterToPointInTime",
		"RestoreDBInstanceFromDBSnapshot",
		"RestoreDBInstanceFromS3",
		"RestoreDBInstanceToPointInTime",
		"RevokeDBSecurityGroupIngress",
		"StartActivityStream",
		"StartDBCluster",
		"StartDBInstance",
		"StartExportTask",
		"StopActivityStream",
		"StopDBCluster",
		"StopDBInstance",
		"SwitchoverBlueGreenDeployment",
		"SwitchoverGlobalCluster",
		"SwitchoverReadReplica",
		// Custom DB engine versions.
		"CreateCustomDBEngineVersion",
		"DeleteCustomDBEngineVersion",
		"ModifyCustomDBEngineVersion",
		// DB shard groups.
		"CreateDBShardGroup",
		"DeleteDBShardGroup",
		"DescribeDBShardGroups",
		"ModifyDBShardGroup",
		"RebootDBShardGroup",
		// Integrations.
		"CreateIntegration",
		"DeleteIntegration",
		"DescribeIntegrations",
		"ModifyIntegration",
		// Tenant databases.
		"CreateTenantDatabase",
		"DeleteTenantDatabase",
		"DescribeTenantDatabases",
		"ModifyTenantDatabase",
		// Automated backups.
		"DeleteDBClusterAutomatedBackup",
		"DeleteDBInstanceAutomatedBackup",
		"DescribeDBClusterAutomatedBackups",
		"DescribeDBInstanceAutomatedBackups",
		"StartDBInstanceAutomatedBackupsReplication",
		"StopDBInstanceAutomatedBackupsReplication",
		// Snapshot tenant databases.
		"DescribeDBSnapshotTenantDatabases",
		// Performance Insights.
		"GetPerformanceInsightsMetrics",
	}
}
