package cloudfront_test

import (
	"testing"

	cloudfrontsdk "github.com/aws/aws-sdk-go-v2/service/cloudfront"
	"github.com/blackbirdworks/gopherstack/pkgs/sdkcheck"
	"github.com/blackbirdworks/gopherstack/services/cloudfront"
)

// TestSDKCompleteness verifies that every operation exposed by the AWS SDK v2
// cloudfront client is either listed in GetSupportedOperations() or explicitly
// acknowledged in the notImplemented slice.  The test fails when the upstream
// SDK adds a new operation that gopherstack has not yet handled.
func TestSDKCompleteness(t *testing.T) {
	t.Parallel()

	backend := cloudfront.NewInMemoryBackend("000000000000", "us-east-1")
	h := cloudfront.NewHandler(backend)
	sdkcheck.CheckCompleteness(t, &cloudfrontsdk.Client{}, h.GetSupportedOperations(), []string{
		"CreateDistributionTenant",
		"CreateDistributionWithTags",
		"CreateFieldLevelEncryptionConfig",
		"CreateFieldLevelEncryptionProfile",
		"CreateInvalidationForDistributionTenant",
		"CreateKeyGroup",
		"CreateKeyValueStore",
		"CreateMonitoringSubscription",
		"CreatePublicKey",
		"CreateRealtimeLogConfig",
		"CreateStreamingDistribution",
		"CreateStreamingDistributionWithTags",
		"CreateTrustStore",
		"CreateVpcOrigin",
		"DeleteAnycastIpList",
		"DeleteCloudFrontOriginAccessIdentity",
		"DeleteConnectionFunction",
		"DeleteConnectionGroup",
		"DeleteContinuousDeploymentPolicy",
		"DeleteDistributionTenant",
		"DeleteFieldLevelEncryptionConfig",
		"DeleteFieldLevelEncryptionProfile",
		"DeleteKeyGroup",
		"DeleteKeyValueStore",
		"DeleteMonitoringSubscription",
		"DeletePublicKey",
		"DeleteRealtimeLogConfig",
		"DeleteResourcePolicy",
		"DeleteStreamingDistribution",
		"DeleteTrustStore",
		"DeleteVpcOrigin",
		"DescribeConnectionFunction",
		"DescribeKeyValueStore",
		"DisassociateDistributionTenantWebACL",
		"DisassociateDistributionWebACL",
		"GetAnycastIpList",
		"GetCloudFrontOriginAccessIdentity",
		"GetCloudFrontOriginAccessIdentityConfig",
		"GetConnectionFunction",
		"GetConnectionGroup",
		"GetConnectionGroupByRoutingEndpoint",
		"GetContinuousDeploymentPolicy",
		"GetContinuousDeploymentPolicyConfig",
		"GetDistributionTenant",
		"GetDistributionTenantByDomain",
		"GetFieldLevelEncryption",
		"GetFieldLevelEncryptionConfig",
		"GetFieldLevelEncryptionProfile",
		"GetFieldLevelEncryptionProfileConfig",
		"GetInvalidationForDistributionTenant",
		"GetKeyGroup",
		"GetKeyGroupConfig",
		"GetManagedCertificateDetails",
		"GetMonitoringSubscription",
		"GetPublicKey",
		"GetPublicKeyConfig",
		"GetRealtimeLogConfig",
		"GetResourcePolicy",
		"GetStreamingDistribution",
		"GetStreamingDistributionConfig",
		"GetTrustStore",
		"GetVpcOrigin",
		"ListAnycastIpLists",
		"ListCloudFrontOriginAccessIdentities",
		"ListConflictingAliases",
		"ListConnectionFunctions",
		"ListConnectionGroups",
		"ListContinuousDeploymentPolicies",
		"ListDistributionTenants",
		"ListDistributionTenantsByCustomization",
		"ListDistributionsByAnycastIpListId",
		"ListDistributionsByCachePolicyId",
		"ListDistributionsByConnectionFunction",
		"ListDistributionsByConnectionMode",
		"ListDistributionsByKeyGroup",
		"ListDistributionsByOriginRequestPolicyId",
		"ListDistributionsByOwnedResource",
		"ListDistributionsByRealtimeLogConfig",
		"ListDistributionsByResponseHeadersPolicyId",
		"ListDistributionsByTrustStore",
		"ListDistributionsByVpcOriginId",
		"ListDistributionsByWebACLId",
		"ListDomainConflicts",
		"ListFieldLevelEncryptionConfigs",
		"ListFieldLevelEncryptionProfiles",
		"ListInvalidationsForDistributionTenant",
		"ListKeyGroups",
		"ListKeyValueStores",
		"ListPublicKeys",
		"ListRealtimeLogConfigs",
		"ListStreamingDistributions",
		"ListTrustStores",
		"ListVpcOrigins",
		"PublishConnectionFunction",
		"PutResourcePolicy",
		"TestConnectionFunction",
		"UpdateAnycastIpList",
		"UpdateCloudFrontOriginAccessIdentity",
		"UpdateConnectionFunction",
		"UpdateConnectionGroup",
		"UpdateContinuousDeploymentPolicy",
		"UpdateDistributionTenant",
		"UpdateDistributionWithStagingConfig",
		"UpdateDomainAssociation",
		"UpdateFieldLevelEncryptionConfig",
		"UpdateFieldLevelEncryptionProfile",
		"UpdateKeyGroup",
		"UpdateKeyValueStore",
		"UpdatePublicKey",
		"UpdateRealtimeLogConfig",
		"UpdateStreamingDistribution",
		"UpdateTrustStore",
		"UpdateVpcOrigin",
		"VerifyDnsConfiguration",
	})
}
