// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: gopherstack/dashboard/v1/dashboard.proto

package dashboardv1connect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect "connectrpc.com/connect"

	v1 "github.com/blackbirdworks/gopherstack/dashboard/api/v1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DashboardServiceName is the fully-qualified name of the DashboardService service.
	DashboardServiceName = "gopherstack.dashboard.v1.DashboardService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DashboardServiceStreamConsoleProcedure is the fully-qualified name of the DashboardService's
	// StreamConsole RPC.
	DashboardServiceStreamConsoleProcedure = "/gopherstack.dashboard.v1.DashboardService/StreamConsole"
	// DashboardServiceStreamMetricsProcedure is the fully-qualified name of the DashboardService's
	// StreamMetrics RPC.
	DashboardServiceStreamMetricsProcedure = "/gopherstack.dashboard.v1.DashboardService/StreamMetrics"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	dashboardServiceServiceDescriptor             = v1.File_gopherstack_dashboard_v1_dashboard_proto.Services().ByName("DashboardService")
	dashboardServiceStreamConsoleMethodDescriptor = dashboardServiceServiceDescriptor.Methods().ByName("StreamConsole")
	dashboardServiceStreamMetricsMethodDescriptor = dashboardServiceServiceDescriptor.Methods().ByName("StreamMetrics")
)

// DashboardServiceClient is a client for the gopherstack.dashboard.v1.DashboardService service.
type DashboardServiceClient interface {
	StreamConsole(context.Context, *connect.Request[v1.StreamConsoleRequest]) (*connect.ServerStreamForClient[v1.StreamConsoleResponse], error)
	StreamMetrics(context.Context, *connect.Request[v1.StreamMetricsRequest]) (*connect.ServerStreamForClient[v1.StreamMetricsResponse], error)
}

// NewDashboardServiceClient constructs a client for the gopherstack.dashboard.v1.DashboardService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDashboardServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DashboardServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &dashboardServiceClient{
		streamConsole: connect.NewClient[v1.StreamConsoleRequest, v1.StreamConsoleResponse](
			httpClient,
			baseURL+DashboardServiceStreamConsoleProcedure,
			connect.WithSchema(dashboardServiceStreamConsoleMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		streamMetrics: connect.NewClient[v1.StreamMetricsRequest, v1.StreamMetricsResponse](
			httpClient,
			baseURL+DashboardServiceStreamMetricsProcedure,
			connect.WithSchema(dashboardServiceStreamMetricsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// dashboardServiceClient implements DashboardServiceClient.
type dashboardServiceClient struct {
	streamConsole *connect.Client[v1.StreamConsoleRequest, v1.StreamConsoleResponse]
	streamMetrics *connect.Client[v1.StreamMetricsRequest, v1.StreamMetricsResponse]
}

// StreamConsole calls gopherstack.dashboard.v1.DashboardService.StreamConsole.
func (c *dashboardServiceClient) StreamConsole(ctx context.Context, req *connect.Request[v1.StreamConsoleRequest]) (*connect.ServerStreamForClient[v1.StreamConsoleResponse], error) {
	return c.streamConsole.CallServerStream(ctx, req)
}

// StreamMetrics calls gopherstack.dashboard.v1.DashboardService.StreamMetrics.
func (c *dashboardServiceClient) StreamMetrics(ctx context.Context, req *connect.Request[v1.StreamMetricsRequest]) (*connect.ServerStreamForClient[v1.StreamMetricsResponse], error) {
	return c.streamMetrics.CallServerStream(ctx, req)
}

// DashboardServiceHandler is an implementation of the gopherstack.dashboard.v1.DashboardService
// service.
type DashboardServiceHandler interface {
	StreamConsole(context.Context, *connect.Request[v1.StreamConsoleRequest], *connect.ServerStream[v1.StreamConsoleResponse]) error
	StreamMetrics(context.Context, *connect.Request[v1.StreamMetricsRequest], *connect.ServerStream[v1.StreamMetricsResponse]) error
}

// NewDashboardServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDashboardServiceHandler(svc DashboardServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	dashboardServiceStreamConsoleHandler := connect.NewServerStreamHandler(
		DashboardServiceStreamConsoleProcedure,
		svc.StreamConsole,
		connect.WithSchema(dashboardServiceStreamConsoleMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	dashboardServiceStreamMetricsHandler := connect.NewServerStreamHandler(
		DashboardServiceStreamMetricsProcedure,
		svc.StreamMetrics,
		connect.WithSchema(dashboardServiceStreamMetricsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/gopherstack.dashboard.v1.DashboardService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DashboardServiceStreamConsoleProcedure:
			dashboardServiceStreamConsoleHandler.ServeHTTP(w, r)
		case DashboardServiceStreamMetricsProcedure:
			dashboardServiceStreamMetricsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDashboardServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDashboardServiceHandler struct{}

func (UnimplementedDashboardServiceHandler) StreamConsole(context.Context, *connect.Request[v1.StreamConsoleRequest], *connect.ServerStream[v1.StreamConsoleResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("gopherstack.dashboard.v1.DashboardService.StreamConsole is not implemented"))
}

func (UnimplementedDashboardServiceHandler) StreamMetrics(context.Context, *connect.Request[v1.StreamMetricsRequest], *connect.ServerStream[v1.StreamMetricsResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("gopherstack.dashboard.v1.DashboardService.StreamMetrics is not implemented"))
}
