// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file gopherstack/dashboard/v1/dashboard.proto (package gopherstack.dashboard.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from "@bufbuild/protobuf";
import { Message, proto3, protoInt64, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from message gopherstack.dashboard.v1.StreamConsoleRequest
 */
export class StreamConsoleRequest extends Message<StreamConsoleRequest> {
  constructor(data?: PartialMessage<StreamConsoleRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "gopherstack.dashboard.v1.StreamConsoleRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => []);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StreamConsoleRequest {
    return new StreamConsoleRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StreamConsoleRequest {
    return new StreamConsoleRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): StreamConsoleRequest {
    return new StreamConsoleRequest().fromJsonString(jsonString, options);
  }

  static equals(
    a: StreamConsoleRequest | PlainMessage<StreamConsoleRequest> | undefined,
    b: StreamConsoleRequest | PlainMessage<StreamConsoleRequest> | undefined,
  ): boolean {
    return proto3.util.equals(StreamConsoleRequest, a, b);
  }
}

/**
 * @generated from message gopherstack.dashboard.v1.StreamConsoleResponse
 */
export class StreamConsoleResponse extends Message<StreamConsoleResponse> {
  /**
   * @generated from field: gopherstack.dashboard.v1.CapturedRequest request = 1;
   */
  request?: CapturedRequest;

  constructor(data?: PartialMessage<StreamConsoleResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "gopherstack.dashboard.v1.StreamConsoleResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "request", kind: "message", T: CapturedRequest },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): StreamConsoleResponse {
    return new StreamConsoleResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StreamConsoleResponse {
    return new StreamConsoleResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): StreamConsoleResponse {
    return new StreamConsoleResponse().fromJsonString(jsonString, options);
  }

  static equals(
    a: StreamConsoleResponse | PlainMessage<StreamConsoleResponse> | undefined,
    b: StreamConsoleResponse | PlainMessage<StreamConsoleResponse> | undefined,
  ): boolean {
    return proto3.util.equals(StreamConsoleResponse, a, b);
  }
}

/**
 * @generated from message gopherstack.dashboard.v1.CapturedRequest
 */
export class CapturedRequest extends Message<CapturedRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string method = 2;
   */
  method = "";

  /**
   * @generated from field: string path = 3;
   */
  path = "";

  /**
   * @generated from field: map<string, string> headers = 4;
   */
  headers: { [key: string]: string } = {};

  /**
   * @generated from field: string body = 5;
   */
  body = "";

  /**
   * @generated from field: int32 status = 6;
   */
  status = 0;

  /**
   * @generated from field: int64 duration_ms = 7;
   */
  durationMs = protoInt64.zero;

  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 8;
   */
  timestamp?: Timestamp;

  constructor(data?: PartialMessage<CapturedRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "gopherstack.dashboard.v1.CapturedRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "method", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    {
      no: 4,
      name: "headers",
      kind: "map",
      K: 9 /* ScalarType.STRING */,
      V: { kind: "scalar", T: 9 /* ScalarType.STRING */ },
    },
    { no: 5, name: "body", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "status", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 7, name: "duration_ms", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 8, name: "timestamp", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CapturedRequest {
    return new CapturedRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CapturedRequest {
    return new CapturedRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CapturedRequest {
    return new CapturedRequest().fromJsonString(jsonString, options);
  }

  static equals(
    a: CapturedRequest | PlainMessage<CapturedRequest> | undefined,
    b: CapturedRequest | PlainMessage<CapturedRequest> | undefined,
  ): boolean {
    return proto3.util.equals(CapturedRequest, a, b);
  }
}

/**
 * @generated from message gopherstack.dashboard.v1.StreamMetricsRequest
 */
export class StreamMetricsRequest extends Message<StreamMetricsRequest> {
  constructor(data?: PartialMessage<StreamMetricsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "gopherstack.dashboard.v1.StreamMetricsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => []);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StreamMetricsRequest {
    return new StreamMetricsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StreamMetricsRequest {
    return new StreamMetricsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): StreamMetricsRequest {
    return new StreamMetricsRequest().fromJsonString(jsonString, options);
  }

  static equals(
    a: StreamMetricsRequest | PlainMessage<StreamMetricsRequest> | undefined,
    b: StreamMetricsRequest | PlainMessage<StreamMetricsRequest> | undefined,
  ): boolean {
    return proto3.util.equals(StreamMetricsRequest, a, b);
  }
}

/**
 * @generated from message gopherstack.dashboard.v1.StreamMetricsResponse
 */
export class StreamMetricsResponse extends Message<StreamMetricsResponse> {
  /**
   * @generated from field: gopherstack.dashboard.v1.DashboardMetrics dashboard = 1;
   */
  dashboard?: DashboardMetrics;

  constructor(data?: PartialMessage<StreamMetricsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "gopherstack.dashboard.v1.StreamMetricsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "dashboard", kind: "message", T: DashboardMetrics },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): StreamMetricsResponse {
    return new StreamMetricsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StreamMetricsResponse {
    return new StreamMetricsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): StreamMetricsResponse {
    return new StreamMetricsResponse().fromJsonString(jsonString, options);
  }

  static equals(
    a: StreamMetricsResponse | PlainMessage<StreamMetricsResponse> | undefined,
    b: StreamMetricsResponse | PlainMessage<StreamMetricsResponse> | undefined,
  ): boolean {
    return proto3.util.equals(StreamMetricsResponse, a, b);
  }
}

/**
 * @generated from message gopherstack.dashboard.v1.DashboardMetrics
 */
export class DashboardMetrics extends Message<DashboardMetrics> {
  /**
   * @generated from field: gopherstack.dashboard.v1.RuntimeMetrics runtime = 1;
   */
  runtime?: RuntimeMetrics;

  /**
   * @generated from field: repeated gopherstack.dashboard.v1.OperationSummary operations = 2;
   */
  operations: OperationSummary[] = [];

  /**
   * @generated from field: repeated gopherstack.dashboard.v1.DeadlockInfo deadlocks = 3;
   */
  deadlocks: DeadlockInfo[] = [];

  /**
   * @generated from field: repeated gopherstack.dashboard.v1.WorkerStats workers = 4;
   */
  workers: WorkerStats[] = [];

  constructor(data?: PartialMessage<DashboardMetrics>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "gopherstack.dashboard.v1.DashboardMetrics";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "runtime", kind: "message", T: RuntimeMetrics },
    { no: 2, name: "operations", kind: "message", T: OperationSummary, repeated: true },
    { no: 3, name: "deadlocks", kind: "message", T: DeadlockInfo, repeated: true },
    { no: 4, name: "workers", kind: "message", T: WorkerStats, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DashboardMetrics {
    return new DashboardMetrics().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DashboardMetrics {
    return new DashboardMetrics().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DashboardMetrics {
    return new DashboardMetrics().fromJsonString(jsonString, options);
  }

  static equals(
    a: DashboardMetrics | PlainMessage<DashboardMetrics> | undefined,
    b: DashboardMetrics | PlainMessage<DashboardMetrics> | undefined,
  ): boolean {
    return proto3.util.equals(DashboardMetrics, a, b);
  }
}

/**
 * @generated from message gopherstack.dashboard.v1.RuntimeMetrics
 */
export class RuntimeMetrics extends Message<RuntimeMetrics> {
  /**
   * @generated from field: int32 goroutines = 1;
   */
  goroutines = 0;

  /**
   * @generated from field: double heap_alloc_mb = 2;
   */
  heapAllocMb = 0;

  /**
   * @generated from field: double heap_inuse_mb = 3;
   */
  heapInuseMb = 0;

  /**
   * @generated from field: double heap_sys_mb = 4;
   */
  heapSysMb = 0;

  /**
   * @generated from field: uint32 num_gc = 5;
   */
  numGc = 0;

  /**
   * @generated from field: double last_gc_pause_ms = 6;
   */
  lastGcPauseMs = 0;

  /**
   * @generated from field: double total_alloc_mb = 7;
   */
  totalAllocMb = 0;

  /**
   * @generated from field: int32 num_services = 8;
   */
  numServices = 0;

  constructor(data?: PartialMessage<RuntimeMetrics>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "gopherstack.dashboard.v1.RuntimeMetrics";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "goroutines", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "heap_alloc_mb", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 3, name: "heap_inuse_mb", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 4, name: "heap_sys_mb", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 5, name: "num_gc", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 6, name: "last_gc_pause_ms", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 7, name: "total_alloc_mb", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 8, name: "num_services", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RuntimeMetrics {
    return new RuntimeMetrics().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RuntimeMetrics {
    return new RuntimeMetrics().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RuntimeMetrics {
    return new RuntimeMetrics().fromJsonString(jsonString, options);
  }

  static equals(
    a: RuntimeMetrics | PlainMessage<RuntimeMetrics> | undefined,
    b: RuntimeMetrics | PlainMessage<RuntimeMetrics> | undefined,
  ): boolean {
    return proto3.util.equals(RuntimeMetrics, a, b);
  }
}

/**
 * @generated from message gopherstack.dashboard.v1.OperationSummary
 */
export class OperationSummary extends Message<OperationSummary> {
  /**
   * @generated from field: string operation = 1;
   */
  operation = "";

  /**
   * @generated from field: int64 count = 2;
   */
  count = protoInt64.zero;

  /**
   * @generated from field: int64 error_count = 3;
   */
  errorCount = protoInt64.zero;

  /**
   * @generated from field: double p50_ms = 4;
   */
  p50Ms = 0;

  /**
   * @generated from field: double p95_ms = 5;
   */
  p95Ms = 0;

  /**
   * @generated from field: double p99_ms = 6;
   */
  p99Ms = 0;

  /**
   * @generated from field: double avg_ms = 7;
   */
  avgMs = 0;

  /**
   * @generated from field: double max_ms = 8;
   */
  maxMs = 0;

  constructor(data?: PartialMessage<OperationSummary>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "gopherstack.dashboard.v1.OperationSummary";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "operation", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "count", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "error_count", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "p50_ms", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 5, name: "p95_ms", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 6, name: "p99_ms", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 7, name: "avg_ms", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 8, name: "max_ms", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OperationSummary {
    return new OperationSummary().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OperationSummary {
    return new OperationSummary().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OperationSummary {
    return new OperationSummary().fromJsonString(jsonString, options);
  }

  static equals(
    a: OperationSummary | PlainMessage<OperationSummary> | undefined,
    b: OperationSummary | PlainMessage<OperationSummary> | undefined,
  ): boolean {
    return proto3.util.equals(OperationSummary, a, b);
  }
}

/**
 * @generated from message gopherstack.dashboard.v1.DeadlockInfo
 */
export class DeadlockInfo extends Message<DeadlockInfo> {
  /**
   * @generated from field: string lock = 1;
   */
  lock = "";

  /**
   * @generated from field: string operation = 2;
   */
  operation = "";

  /**
   * @generated from field: double held_sec = 3;
   */
  heldSec = 0;

  /**
   * @generated from field: int32 waiters = 4;
   */
  waiters = 0;

  constructor(data?: PartialMessage<DeadlockInfo>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "gopherstack.dashboard.v1.DeadlockInfo";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "lock", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "operation", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "held_sec", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 4, name: "waiters", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeadlockInfo {
    return new DeadlockInfo().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeadlockInfo {
    return new DeadlockInfo().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeadlockInfo {
    return new DeadlockInfo().fromJsonString(jsonString, options);
  }

  static equals(
    a: DeadlockInfo | PlainMessage<DeadlockInfo> | undefined,
    b: DeadlockInfo | PlainMessage<DeadlockInfo> | undefined,
  ): boolean {
    return proto3.util.equals(DeadlockInfo, a, b);
  }
}

/**
 * @generated from message gopherstack.dashboard.v1.WorkerStats
 */
export class WorkerStats extends Message<WorkerStats> {
  /**
   * @generated from field: string service = 1;
   */
  service = "";

  /**
   * @generated from field: string worker = 2;
   */
  worker = "";

  /**
   * @generated from field: int32 queue_depth = 3;
   */
  queueDepth = 0;

  /**
   * @generated from field: int64 tasks_total = 4;
   */
  tasksTotal = protoInt64.zero;

  /**
   * @generated from field: int64 errors_total = 5;
   */
  errorsTotal = protoInt64.zero;

  /**
   * @generated from field: int64 items_processed_total = 6;
   */
  itemsProcessedTotal = protoInt64.zero;

  constructor(data?: PartialMessage<WorkerStats>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "gopherstack.dashboard.v1.WorkerStats";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "service", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "worker", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "queue_depth", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "tasks_total", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "errors_total", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 6, name: "items_processed_total", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WorkerStats {
    return new WorkerStats().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WorkerStats {
    return new WorkerStats().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WorkerStats {
    return new WorkerStats().fromJsonString(jsonString, options);
  }

  static equals(
    a: WorkerStats | PlainMessage<WorkerStats> | undefined,
    b: WorkerStats | PlainMessage<WorkerStats> | undefined,
  ): boolean {
    return proto3.util.equals(WorkerStats, a, b);
  }
}
