// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file gopherstack/dashboard/v1/dashboard.proto (package gopherstack.dashboard.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import {
  StreamConsoleRequest,
  StreamConsoleResponse,
  StreamMetricsRequest,
  StreamMetricsResponse,
} from "./dashboard_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service gopherstack.dashboard.v1.DashboardService
 */
export const DashboardService = {
  typeName: "gopherstack.dashboard.v1.DashboardService",
  methods: {
    /**
     * @generated from rpc gopherstack.dashboard.v1.DashboardService.StreamConsole
     */
    streamConsole: {
      name: "StreamConsole",
      I: StreamConsoleRequest,
      O: StreamConsoleResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc gopherstack.dashboard.v1.DashboardService.StreamMetrics
     */
    streamMetrics: {
      name: "StreamMetrics",
      I: StreamMetricsRequest,
      O: StreamMetricsResponse,
      kind: MethodKind.ServerStreaming,
    },
  },
} as const;
