package s3

func s3CoreOperations() []string {
	return []string{
		"CreateBucket",
		"DeleteBucket",
		"ListBuckets",
		"HeadBucket",
		"GetBucketVersioning",
		"GetBucketLocation",
		"PutBucketVersioning",
		"PutBucketTagging",
		"GetBucketTagging",
		"DeleteBucketTagging",
		"PutObject",
		"GetObject",
		"HeadObject",
		"DeleteObject",
		"DeleteObjects",
		"CopyObject",
		"ListObjects",
		"ListObjectsV2",
		"ListObjectVersions",
		"PutObjectTagging",
		"GetObjectTagging",
		"DeleteObjectTagging",
		"PutObjectAcl",
		"GetObjectAcl",
		"CreateMultipartUpload",
		"UploadPart",
		"UploadPartCopy",
		opCompleteMultipartUpload,
		"AbortMultipartUpload",
		"ListMultipartUploads",
		"ListParts",
		"PresignedGetObject",
		"PresignedPutObject",
		"GetBucketAcl",
		"PutBucketAcl",
		"PutBucketPolicy",
		"GetBucketPolicy",
		"DeleteBucketPolicy",
		"PutBucketCors",
		"GetBucketCors",
		"DeleteBucketCors",
		"PutBucketLifecycleConfiguration",
		"GetBucketLifecycleConfiguration",
		"DeleteBucketLifecycleConfiguration",
		"PutBucketNotificationConfiguration",
		"GetBucketNotificationConfiguration",
		"PutBucketWebsite",
		"GetBucketWebsite",
		"DeleteBucketWebsite",
		"PutBucketEncryption",
		"GetBucketEncryption",
		"DeleteBucketEncryption",
		"PutObjectLockConfiguration",
		"GetObjectLockConfiguration",
		"PutObjectRetention",
		"GetObjectRetention",
		"PutObjectLegalHold",
		"GetObjectLegalHold",
		"PutPublicAccessBlock",
		"GetPublicAccessBlock",
		"DeletePublicAccessBlock",
		"PutBucketOwnershipControls",
		"GetBucketOwnershipControls",
		"DeleteBucketOwnershipControls",
		"PutBucketLogging",
		"GetBucketLogging",
		"PutBucketReplication",
		"GetBucketReplication",
		"DeleteBucketReplication",
		"SelectObjectContent",
		"CreateBucketMetadataConfiguration",
		"GetBucketMetadataConfiguration",
		"DeleteBucketMetadataConfiguration",
		"CreateBucketMetadataTableConfiguration",
		"GetBucketMetadataTableConfiguration",
		"DeleteBucketMetadataTableConfiguration",
		"CreateSession",
		"PutBucketAnalyticsConfiguration",
		"GetBucketAnalyticsConfiguration",
		"DeleteBucketAnalyticsConfiguration",
		"ListBucketAnalyticsConfigurations",
		"PutBucketIntelligentTieringConfiguration",
		"GetBucketIntelligentTieringConfiguration",
		"DeleteBucketIntelligentTieringConfiguration",
		"ListBucketIntelligentTieringConfigurations",
		"PutBucketInventoryConfiguration",
		"GetBucketInventoryConfiguration",
		"DeleteBucketInventoryConfiguration",
		"ListBucketInventoryConfigurations",
		"DeleteBucketLifecycle",
		"PutBucketMetricsConfiguration",
		"GetBucketMetricsConfiguration",
		"DeleteBucketMetricsConfiguration",
		"ListBucketMetricsConfigurations",
	}
}

// s3ExtendedOperations returns S3 operations that are fully implemented but
// historically tracked separately from the primary CRUD/config surface in
// s3CoreOperations (mostly SDK-completeness-only or later-added corners:
// directory buckets, ABAC, request-payment, torrent, restore, metadata-table
// journal/inventory updates, WriteGetObjectResponse). Every operation here
// performs real state mutation/reads against the backend — none of them
// return a canned/no-op response (verified: RestoreObject, Get/PutBucketAccelerateConfiguration,
// Get/PutBucketRequestPayment, GetObjectAttributes, ListDirectoryBuckets,
// PostObject, WriteGetObjectResponse, RenameObject, UpdateObjectEncryption,
// GetBucketPolicyStatus, Get/PutBucketAbac, and both
// UpdateBucketMetadata{Inventory,Journal}TableConfiguration all do real state
// mutation/reads). GetSupportedOperations merges this with s3CoreOperations
// into a single flat list; the split exists only for readability of this
// file — this function was previously (and misleadingly) named
// s3StubOperations, which implied unimplemented/canned handlers; it was
// renamed because every operation in it is fully implemented.
func s3ExtendedOperations() []string {
	return []string{
		"GetBucketAbac",
		"GetBucketAccelerateConfiguration",
		"GetBucketPolicyStatus",
		"GetBucketRequestPayment",
		"GetObjectAttributes",
		"GetObjectTorrent",
		"ListDirectoryBuckets",
		"PutBucketAbac",
		"PutBucketAccelerateConfiguration",
		"PutBucketRequestPayment",
		"RenameObject",
		"RestoreObject",
		"PostObject",
		"UpdateBucketMetadataInventoryTableConfiguration",
		"UpdateBucketMetadataJournalTableConfiguration",
		"UpdateObjectEncryption",
		"WriteGetObjectResponse",
	}
}
