package emrserverless

// Code in this file supports Phase 3.3 of the datalayer refactor: every
// map[string]*T (or nested map[string]map[string]*T) resource field on
// InMemoryBackend is replaced with a *store.Table[T], following the pattern
// established by services/sesv2 / services/vpclattice (data-driven,
// direct/byParent-index registration -- see pkgs/store's package doc for the
// underlying primitive).
//
// applications, jobRuns, and sessions all key off a real, non-json:"-"
// identity field the value type already carries (Application.ApplicationID,
// JobRun.JobRunID, Session.SessionID) -- every ID is generated by newID and
// is globally unique (not merely unique within some parent application), so
// all three register directly on b.registry. jobRuns and sessions are
// parent-nested (a job run / session belongs to an application) but their
// IDs are themselves globally unique -- the original code's
// "applicationID -> childID" nested-map keys existed only to get
// parent-scoped lookup and cascade-delete on DeleteApplication, not because
// the ID needed the parent to be unique. That matches the
// direct-registration-plus-byApplication-index rule: each keeps its bare ID
// as the primary key, with an additive byApplication Index replacing the
// nested-map lookup and the DeleteApplication cascade scan.
//
// Each of the three tables additionally carries a byARN secondary index,
// replacing the old hand-rolled reverse-lookup maps (applicationARNs,
// jobRunARNs, sessionARNs) that findTagsByARN used to walk by hand.
//
// Left as a plain map (not store.Table-backed): sessionTokens
// (map[string]map[string]string, keyed by applicationID then clientToken --
// values are plain strings, not *T, so it does not fit store.Table's
// keyed-by-identity-value shape). See persistence.go for how it round-trips
// alongside the registered tables.
import (
	"github.com/blackbirdworks/gopherstack/pkgs/store"
)

func applicationKeyFn(v *Application) string         { return v.ApplicationID }
func applicationARNIndexKeyFn(v *Application) string { return v.Arn }

func jobRunKeyFn(v *JobRun) string                 { return v.JobRunID }
func jobRunApplicationIndexKeyFn(v *JobRun) string { return v.ApplicationID }
func jobRunARNIndexKeyFn(v *JobRun) string         { return v.Arn }

func sessionKeyFn(v *Session) string                 { return v.SessionID }
func sessionApplicationIndexKeyFn(v *Session) string { return v.ApplicationID }
func sessionARNIndexKeyFn(v *Session) string         { return v.Arn }

// registerAllTables registers every backend resource table (and its
// secondary indexes) exactly once. It must be called during construction
// only, immediately after b.registry is created -- store.Register panics on
// a duplicate name, so runtime resets go through b.registry.ResetAll()
// instead (see InMemoryBackend.Reset in backend.go).
func registerAllTables(b *InMemoryBackend) {
	b.applications = store.Register(b.registry, "applications", store.New(applicationKeyFn))
	b.applicationsByARN = b.applications.AddIndex("byARN", applicationARNIndexKeyFn)

	b.jobRuns = store.Register(b.registry, "jobRuns", store.New(jobRunKeyFn))
	b.jobRunsByApplication = b.jobRuns.AddIndex("byApplication", jobRunApplicationIndexKeyFn)
	b.jobRunsByARN = b.jobRuns.AddIndex("byARN", jobRunARNIndexKeyFn)

	b.sessions = store.Register(b.registry, "sessions", store.New(sessionKeyFn))
	b.sessionsByApplication = b.sessions.AddIndex("byApplication", sessionApplicationIndexKeyFn)
	b.sessionsByARN = b.sessions.AddIndex("byARN", sessionARNIndexKeyFn)
}
