services:
  gopherstack:
    image: blackbirdworks/gopherstack:latest
    ports:
      - "8000:8000"
    environment:
      - ENFORCE_IAM=true
      - AWS_DEFAULT_REGION=us-east-1
      - ACCOUNT_ID=000000000000
