package glue

import (
	"context"
	"fmt"
	"strings"
)

// generateETLScript produces a Python or Scala Glue ETL script from DagNodes/DagEdges.
// language should be "Python" or "Scala"; defaults to Python.
func generateETLScript(nodes []dagNode, edges []dagEdge, language string) (string, string) {
	if strings.ToUpper(language) == "SCALA" {
		return "", buildScalaScript(nodes, edges)
	}

	return buildPythonScript(nodes, edges), ""
}

// nodeArg returns the value of the named argument from a dagNode, or "" if absent.
func nodeArg(n dagNode, name string) string {
	for _, a := range n.Args {
		if a.Name == name {
			return a.Value
		}
	}

	return ""
}

func buildPythonScript(nodes []dagNode, edges []dagEdge) string {
	var sb strings.Builder

	sb.WriteString("import sys\n")
	sb.WriteString("from awsglue.transforms import *\n")
	sb.WriteString("from awsglue.utils import getResolvedOptions\n")
	sb.WriteString("from pyspark.context import SparkContext\n")
	sb.WriteString("from awsglue.context import GlueContext\n")
	sb.WriteString("from awsglue.job import Job\n")
	sb.WriteString("args = getResolvedOptions(sys.argv, [\"JOB_NAME\"])\n")
	sb.WriteString("sc = SparkContext()\n")
	sb.WriteString("glueContext = GlueContext(sc)\n")
	sb.WriteString("spark = glueContext.spark_session\n")
	sb.WriteString("job = Job(glueContext)\n")
	sb.WriteString("job.init(args[\"JOB_NAME\"], args)\n")

	// Build edge target→source index for variable references.
	targetSource := make(map[string]string, len(edges))
	for _, e := range edges {
		targetSource[e.Target] = e.Source
	}

	for _, n := range nodes {
		switch strings.ToUpper(n.NodeType) {
		case "DATASOURCE":
			db := nodeArg(n, "database")
			tbl := nodeArg(n, "table_name")
			fmt.Fprintf(&sb,
				"%s = glueContext.create_dynamic_frame.from_catalog("+
					"database=\"%s\", table_name=\"%s\", transformation_ctx=\"%s\")\n",
				n.ID, db, tbl, n.ID)
		case "DATASINK":
			src := targetSource[n.ID]
			db := nodeArg(n, "database")
			tbl := nodeArg(n, "table_name")
			fmt.Fprintf(&sb,
				"glueContext.write_dynamic_frame.from_catalog("+
					"frame=%s, database=\"%s\", table_name=\"%s\", transformation_ctx=\"%s\")\n",
				src, db, tbl, n.ID)
		case "APPLYMAPPING":
			src := targetSource[n.ID]
			fmt.Fprintf(
				&sb,
				"%s = ApplyMapping.apply(frame=%s, mappings=[], transformation_ctx=\"%s\")\n",
				n.ID,
				src,
				n.ID,
			)
		default:
			src := targetSource[n.ID]
			if src == "" {
				src = "None"
			}

			fmt.Fprintf(&sb, "%s = %s.apply(frame=%s, transformation_ctx=\"%s\")\n",
				n.ID, n.NodeType, src, n.ID)
		}
	}

	sb.WriteString("job.commit()\n")

	return sb.String()
}

func buildScalaScript(nodes []dagNode, edges []dagEdge) string {
	var sb strings.Builder

	sb.WriteString("import com.amazonaws.services.glue.GlueContext\n")
	sb.WriteString("import com.amazonaws.services.glue.util.{Job, JsonOptions}\n")
	sb.WriteString("import org.apache.spark.SparkContext\n")
	sb.WriteString("object GlueApp {\n")
	sb.WriteString("  def main(sysArgs: Array[String]): Unit = {\n")
	sb.WriteString("    val sc: SparkContext = new SparkContext()\n")
	sb.WriteString("    val glueContext: GlueContext = new GlueContext(sc)\n")
	sb.WriteString("    Job.init(\"glue_job\", glueContext, Map.empty)\n")

	targetSource := make(map[string]string, len(edges))
	for _, e := range edges {
		targetSource[e.Target] = e.Source
	}

	for _, n := range nodes {
		switch strings.ToUpper(n.NodeType) {
		case "DATASOURCE":
			db := nodeArg(n, "database")
			tbl := nodeArg(n, "table_name")
			fmt.Fprintf(&sb,
				"    val %s = glueContext.getCatalogSource("+
					"database=\"%s\", tableName=\"%s\", transformationContext=\"%s\").getDynamicFrame()\n",
				n.ID, db, tbl, n.ID)
		case "DATASINK":
			src := targetSource[n.ID]
			db := nodeArg(n, "database")
			tbl := nodeArg(n, "table_name")
			fmt.Fprintf(&sb,
				"    glueContext.getCatalogSink("+
					"database=\"%s\", tableName=\"%s\", transformationContext=\"%s\").writeDynamicFrame(%s)\n",
				db, tbl, n.ID, src)
		default:
			src := targetSource[n.ID]
			if src == "" {
				src = "null"
			}

			fmt.Fprintf(&sb, "    val %s = %s.apply(%s, transformationContext=\"%s\")\n",
				n.ID, n.NodeType, src, n.ID)
		}
	}

	sb.WriteString("    Job.commit()\n")
	sb.WriteString("  }\n")
	sb.WriteString("}\n")

	return sb.String()
}

// parseETLScriptDAG extracts DagNodes and DagEdges from a Glue ETL Python script.
// Recognises create_dynamic_frame.from_catalog (DataSource), ApplyMapping.apply,
// and write_dynamic_frame (DataSink) patterns generated by generateETLScript.
func parseETLScriptDAG(script string) ([]dagNode, []dagEdge) {
	if script == "" {
		return []dagNode{}, []dagEdge{}
	}

	var nodes []dagNode
	var edges []dagEdge

	for lineNum, line := range strings.Split(script, "\n") {
		n, e := parseETLLine(strings.TrimSpace(line), lineNum+1)
		nodes = append(nodes, n...)
		edges = append(edges, e...)
	}

	if nodes == nil {
		nodes = []dagNode{}
	}

	if edges == nil {
		edges = []dagEdge{}
	}

	return nodes, edges
}

// parseETLLine parses a single line of a Glue ETL Python script, returning any
// DagNodes and DagEdges found on that line.
func parseETLLine(line string, lineNum int) ([]dagNode, []dagEdge) {
	switch {
	case strings.Contains(line, "create_dynamic_frame.from_catalog"):
		return parseDataSourceLine(line, lineNum)

	case strings.Contains(line, "ApplyMapping.apply"):
		return parseApplyMappingLine(line, lineNum)

	case strings.Contains(line, "write_dynamic_frame"):
		return parseDataSinkLine(line, lineNum)
	}

	return nil, nil
}

func parseDataSourceLine(line string, lineNum int) ([]dagNode, []dagEdge) {
	id, db, tbl := parsePythonDataSource(line)
	if id == "" {
		return nil, nil
	}

	return []dagNode{{
		ID:         id,
		NodeType:   "DataSource",
		LineNumber: lineNum,
		Args: []dagNodeArg{
			{Name: "database", Value: db},
			{Name: "table_name", Value: tbl},
		},
	}}, nil
}

func parseApplyMappingLine(line string, lineNum int) ([]dagNode, []dagEdge) {
	id, src := parsePythonApplyMapping(line)
	if id == "" {
		return nil, nil
	}

	nodes := []dagNode{{ID: id, NodeType: "ApplyMapping", LineNumber: lineNum}}

	var edges []dagEdge
	if src != "" {
		edges = []dagEdge{{Source: src, Target: id, TargetParameter: "frame"}}
	}

	return nodes, edges
}

func parseDataSinkLine(line string, lineNum int) ([]dagNode, []dagEdge) {
	id, src, db, tbl := parsePythonDataSink(line)
	if id == "" {
		return nil, nil
	}

	nodes := []dagNode{{
		ID:         id,
		NodeType:   "DataSink",
		LineNumber: lineNum,
		Args: []dagNodeArg{
			{Name: "database", Value: db},
			{Name: "table_name", Value: tbl},
		},
	}}

	var edges []dagEdge
	if src != "" {
		edges = []dagEdge{{Source: src, Target: id, TargetParameter: "frame"}}
	}

	return nodes, edges
}

// parsePythonDataSource extracts (id, database, table_name) from a
// create_dynamic_frame.from_catalog assignment line.
func parsePythonDataSource(line string) (string, string, string) {
	// Pattern: {id} = glueContext.create_dynamic_frame.from_catalog(...)
	var id string
	if before, _, ok := strings.Cut(line, " = "); ok {
		id = strings.TrimSpace(before)
	}

	return id, extractQuotedArg(line, "database"), extractQuotedArg(line, "table_name")
}

// parsePythonApplyMapping extracts (id, sourceFrame) from an ApplyMapping.apply line.
func parsePythonApplyMapping(line string) (string, string) {
	var id string
	if before, _, ok := strings.Cut(line, " = "); ok {
		id = strings.TrimSpace(before)
	}

	src := extractQuotedArg(line, "frame")
	if src == "" {
		// frame arg is an identifier, not a quoted string.
		src = extractIdentifierArg(line, "frame")
	}

	return id, src
}

// parsePythonDataSink extracts (id, sourceFrame, db, table) from a write_dynamic_frame line.
func parsePythonDataSink(line string) (string, string, string, string) {
	// Pattern: write_dynamic_frame.from_catalog(frame={src}, database="{db}", table_name="{tbl}", ...)
	return extractQuotedArg(line, "transformation_ctx"),
		extractIdentifierArg(line, "frame"),
		extractQuotedArg(line, "database"),
		extractQuotedArg(line, "table_name")
}

// extractQuotedArg finds key="value" in s and returns value.
func extractQuotedArg(s, key string) string {
	_, after, ok := strings.Cut(s, key+"=\"")
	if !ok {
		return ""
	}

	val, _, _ := strings.Cut(after, "\"")

	return val
}

// extractIdentifierArg finds key=identifier (no quotes) in s and returns the identifier.
func extractIdentifierArg(s, key string) string {
	_, after, ok := strings.Cut(s, key+"=")
	if !ok {
		return ""
	}

	// identifier ends at ',' or ')' or end of string.
	end := strings.IndexAny(after, ",)")
	if end < 0 {
		end = len(after)
	}

	val := strings.TrimSpace(after[:end])
	// Strip surrounding quotes if present.
	if len(val) >= 2 && val[0] == '"' && val[len(val)-1] == '"' {
		return val[1 : len(val)-1]
	}

	return val
}

// dagNodeArg is an argument for a DAG node.
type dagNodeArg struct {
	Name  string `json:"Name"`
	Value string `json:"Value"`
	Param bool   `json:"Param,omitempty"`
}

// dagNode represents a node in a Glue ETL DAG.
type dagNode struct {
	ID         string       `json:"Id"`
	NodeType   string       `json:"NodeType"`
	Args       []dagNodeArg `json:"Args"`
	LineNumber int          `json:"LineNumber,omitempty"`
}

// dagEdge represents a directed edge in a Glue ETL DAG.
type dagEdge struct {
	Source          string `json:"Source"`
	Target          string `json:"Target"`
	TargetParameter string `json:"TargetParameter,omitempty"`
}

// createScriptInput holds input for CreateScript.
type createScriptInput struct {
	Language string    `json:"Language"`
	DagEdges []dagEdge `json:"DagEdges"`
	DagNodes []dagNode `json:"DagNodes"`
}

// createScriptOutput holds the result for CreateScript.
type createScriptOutput struct {
	PythonScript string `json:"PythonScript"`
	ScalaCode    string `json:"ScalaCode"`
}

func (h *Handler) handleCreateScript(
	_ context.Context,
	in *createScriptInput,
) (*createScriptOutput, error) {
	py, sc := generateETLScript(in.DagNodes, in.DagEdges, in.Language)

	return &createScriptOutput{PythonScript: py, ScalaCode: sc}, nil
}

// getDataflowGraphInput holds input for GetDataflowGraph. The real
// GetDataflowGraphInput has no Language member at all (api_op_GetDataflowGraph.go)
// -- a prior pass fabricated one; removed rather than left unread.
type getDataflowGraphInput struct {
	PythonScript string `json:"PythonScript,omitempty"`
}

// getDataflowGraphOutput holds the result for GetDataflowGraph.
type getDataflowGraphOutput struct {
	DagNodes []dagNode `json:"DagNodes"`
	DagEdges []dagEdge `json:"DagEdges"`
}

func (h *Handler) handleGetDataflowGraph(
	_ context.Context,
	in *getDataflowGraphInput,
) (*getDataflowGraphOutput, error) {
	nodes, edges := parseETLScriptDAG(in.PythonScript)

	return &getDataflowGraphOutput{DagNodes: nodes, DagEdges: edges}, nil
}

// catalogEntryRef identifies a table by database and table name, matching the
// wire shape of the Glue CatalogEntry type.
type catalogEntryRef struct {
	DatabaseName string `json:"DatabaseName"`
	TableName    string `json:"TableName"`
}

// getMappingInput holds input for GetMapping.
type getMappingInput struct {
	Location any               `json:"Location,omitempty"`
	Source   catalogEntryRef   `json:"Source"`
	Sinks    []catalogEntryRef `json:"Sinks,omitempty"`
}

// mappingEntryOut is a single source-to-target column mapping.
type mappingEntryOut struct {
	SourcePath  string `json:"SourcePath,omitempty"`
	SourceTable string `json:"SourceTable,omitempty"`
	SourceType  string `json:"SourceType,omitempty"`
	TargetPath  string `json:"TargetPath,omitempty"`
	TargetTable string `json:"TargetTable,omitempty"`
	TargetType  string `json:"TargetType,omitempty"`
}

// getMappingOutput holds the result for GetMapping.
type getMappingOutput struct {
	Mapping []mappingEntryOut `json:"Mapping"`
}

// columnByName returns the column with the given name, or nil if absent.
func columnByName(columns []Column, name string) *Column {
	for i := range columns {
		if columns[i].Name == name {
			return &columns[i]
		}
	}

	return nil
}

// handleGetMapping derives a column mapping from the source table's stored
// schema to the first sink table's schema (or back to itself when no sink is
// given, matching AWS's "suggest a mapping" behavior for an unspecified target).
func (h *Handler) handleGetMapping(_ context.Context, in *getMappingInput) (*getMappingOutput, error) {
	if in.Source.DatabaseName == "" || in.Source.TableName == "" {
		return nil, fmt.Errorf("%w: Source is required", ErrValidation)
	}

	srcTable, err := h.Backend.GetTable(in.Source.DatabaseName, in.Source.TableName)
	if err != nil {
		return nil, err
	}

	sinkTable := srcTable
	sinkTableName := in.Source.TableName

	if len(in.Sinks) > 0 {
		sink := in.Sinks[0]

		sinkT, sinkErr := h.Backend.GetTable(sink.DatabaseName, sink.TableName)
		if sinkErr != nil {
			return nil, sinkErr
		}

		sinkTable = sinkT
		sinkTableName = sink.TableName
	}

	mapping := make([]mappingEntryOut, 0, len(srcTable.StorageDescriptor.Columns))

	for _, col := range srcTable.StorageDescriptor.Columns {
		entry := mappingEntryOut{
			SourceTable: in.Source.TableName,
			SourcePath:  col.Name,
			SourceType:  col.Type,
			TargetTable: sinkTableName,
			TargetPath:  col.Name,
			TargetType:  col.Type,
		}

		if tc := columnByName(sinkTable.StorageDescriptor.Columns, col.Name); tc != nil {
			entry.TargetType = tc.Type
		}

		mapping = append(mapping, entry)
	}

	return &getMappingOutput{Mapping: mapping}, nil
}

// getPlanCatalogEntry holds a catalog source/sink reference.
type getPlanCatalogEntry struct {
	DatabaseName string `json:"DatabaseName,omitempty"`
	TableName    string `json:"TableName,omitempty"`
}

// getPlanInput holds input for GetPlan.
type getPlanInput struct {
	Source   *getPlanCatalogEntry `json:"Source,omitempty"`
	Language string               `json:"Language"`
	Mapping  []MappingEntry       `json:"Mapping"`
}

// getPlanOutput holds the result for GetPlan.
type getPlanOutput struct {
	PythonScript string `json:"PythonScript"`
	ScalaCode    string `json:"ScalaCode"`
}

func (h *Handler) handleGetPlan(_ context.Context, in *getPlanInput) (*getPlanOutput, error) {
	python, scala := h.Backend.GetPlan(in.Language)
	if in.Source != nil && in.Source.TableName != "" {
		if python != "" {
			python += fmt.Sprintf("# Source: %s\n", in.Source.TableName)
		}
		if scala != "" {
			scala += fmt.Sprintf("// Source: %s\n", in.Source.TableName)
		}
	}

	return &getPlanOutput{PythonScript: python, ScalaCode: scala}, nil
}
