package glue_test

import (
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/labstack/echo/v5"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/blackbirdworks/gopherstack/services/glue"
)

// sdkRouteCases is the authoritative X-Amz-Target for every real Glue
// operation, extracted from glue@v1.152.0 serializers.go: each op's
// awsAwsjson11_serializeOp<Op>.HandleSerialize sets
// httpBindingEncoder.SetHeader("X-Amz-Target").String("AWSGlue.<Op>") and
// always request.Request.Method = "POST" against path "/" -- Glue is
// JSON-RPC 1.1 (services/_PROTOCOLS.md), so unlike a REST-family service
// there is no path template to get wrong: dispatch is entirely by this one
// header. ExtractOperation and Handler() both derive the action the same
// way (TrimPrefix on "AWSGlue."), so the class of bug this table can catch
// is a dispatch-table key that doesn't exactly match the real op name
// (typo, wrong case -- Glue is case-sensitive JSON-RPC), not a
// route-template mismatch.
//
// This table covers all 299 real Glue ops, which is also gopherstack's
// full implemented set (h.GetSupportedOperations(), 299/299) as of
// glue@v1.152.0 -- confirmed by diffing glueOpBindings (the single
// data-driven source of truth for both GetSupportedOperations and the
// dispatch map, in handler_routing.go) against this exact list, zero
// mismatches either direction.
//
// Regenerate by grepping serializers.go for every
// `SetHeader("X-Amz-Target").String("AWSGlue.` and pulling the suffix
// after the last dot.
func sdkRouteCases() []struct{ op, target string } {
	return []struct{ op, target string }{
		{"AssociateGlossaryTerms", "AWSGlue.AssociateGlossaryTerms"},
		{"BatchCreatePartition", "AWSGlue.BatchCreatePartition"},
		{"BatchDeleteConnection", "AWSGlue.BatchDeleteConnection"},
		{"BatchDeletePartition", "AWSGlue.BatchDeletePartition"},
		{"BatchDeleteTable", "AWSGlue.BatchDeleteTable"},
		{"BatchDeleteTableVersion", "AWSGlue.BatchDeleteTableVersion"},
		{"BatchGetBlueprints", "AWSGlue.BatchGetBlueprints"},
		{"BatchGetCrawlers", "AWSGlue.BatchGetCrawlers"},
		{"BatchGetCustomEntityTypes", "AWSGlue.BatchGetCustomEntityTypes"},
		{"BatchGetDataQualityResult", "AWSGlue.BatchGetDataQualityResult"},
		{"BatchGetDataQualityRulesetEvaluationRun", "AWSGlue.BatchGetDataQualityRulesetEvaluationRun"},
		{"BatchGetDevEndpoints", "AWSGlue.BatchGetDevEndpoints"},
		{"BatchGetIterableForms", "AWSGlue.BatchGetIterableForms"},
		{"BatchGetJobs", "AWSGlue.BatchGetJobs"},
		{"BatchGetPartition", "AWSGlue.BatchGetPartition"},
		{"BatchGetTableOptimizer", "AWSGlue.BatchGetTableOptimizer"},
		{"BatchGetTriggers", "AWSGlue.BatchGetTriggers"},
		{"BatchGetWorkflows", "AWSGlue.BatchGetWorkflows"},
		{"BatchPutDataQualityStatisticAnnotation", "AWSGlue.BatchPutDataQualityStatisticAnnotation"},
		{"BatchStopJobRun", "AWSGlue.BatchStopJobRun"},
		{"BatchUpdatePartition", "AWSGlue.BatchUpdatePartition"},
		{"CancelDataQualityRuleRecommendationRun", "AWSGlue.CancelDataQualityRuleRecommendationRun"},
		{"CancelDataQualityRulesetEvaluationRun", "AWSGlue.CancelDataQualityRulesetEvaluationRun"},
		{"CancelMLTaskRun", "AWSGlue.CancelMLTaskRun"},
		{"CancelStatement", "AWSGlue.CancelStatement"},
		{"CheckSchemaVersionValidity", "AWSGlue.CheckSchemaVersionValidity"},
		{"CreateBlueprint", "AWSGlue.CreateBlueprint"},
		{"CreateCatalog", "AWSGlue.CreateCatalog"},
		{"CreateClassifier", "AWSGlue.CreateClassifier"},
		{"CreateColumnStatisticsTaskSettings", "AWSGlue.CreateColumnStatisticsTaskSettings"},
		{"CreateConnection", "AWSGlue.CreateConnection"},
		{"CreateCrawler", "AWSGlue.CreateCrawler"},
		{"CreateCustomEntityType", "AWSGlue.CreateCustomEntityType"},
		{"CreateDataQualityRuleset", "AWSGlue.CreateDataQualityRuleset"},
		{"CreateDatabase", "AWSGlue.CreateDatabase"},
		{"CreateDevEndpoint", "AWSGlue.CreateDevEndpoint"},
		{"CreateGlossary", "AWSGlue.CreateGlossary"},
		{"CreateGlossaryTerm", "AWSGlue.CreateGlossaryTerm"},
		{"CreateGlueIdentityCenterConfiguration", "AWSGlue.CreateGlueIdentityCenterConfiguration"},
		{"CreateIntegration", "AWSGlue.CreateIntegration"},
		{"CreateIntegrationResourceProperty", "AWSGlue.CreateIntegrationResourceProperty"},
		{"CreateIntegrationTableProperties", "AWSGlue.CreateIntegrationTableProperties"},
		{"CreateJob", "AWSGlue.CreateJob"},
		{"CreateMLTransform", "AWSGlue.CreateMLTransform"},
		{"CreatePartition", "AWSGlue.CreatePartition"},
		{"CreatePartitionIndex", "AWSGlue.CreatePartitionIndex"},
		{"CreateRegistry", "AWSGlue.CreateRegistry"},
		{"CreateSchema", "AWSGlue.CreateSchema"},
		{"CreateScript", "AWSGlue.CreateScript"},
		{"CreateSecurityConfiguration", "AWSGlue.CreateSecurityConfiguration"},
		{"CreateSession", "AWSGlue.CreateSession"},
		{"CreateTable", "AWSGlue.CreateTable"},
		{"CreateTableOptimizer", "AWSGlue.CreateTableOptimizer"},
		{"CreateTrigger", "AWSGlue.CreateTrigger"},
		{"CreateUsageProfile", "AWSGlue.CreateUsageProfile"},
		{"CreateUserDefinedFunction", "AWSGlue.CreateUserDefinedFunction"},
		{"CreateWorkflow", "AWSGlue.CreateWorkflow"},
		{"DeleteAsset", "AWSGlue.DeleteAsset"},
		{"DeleteAssetType", "AWSGlue.DeleteAssetType"},
		{"DeleteAttachment", "AWSGlue.DeleteAttachment"},
		{"DeleteBlueprint", "AWSGlue.DeleteBlueprint"},
		{"DeleteCatalog", "AWSGlue.DeleteCatalog"},
		{"DeleteClassifier", "AWSGlue.DeleteClassifier"},
		{"DeleteColumnStatisticsForPartition", "AWSGlue.DeleteColumnStatisticsForPartition"},
		{"DeleteColumnStatisticsForTable", "AWSGlue.DeleteColumnStatisticsForTable"},
		{"DeleteColumnStatisticsTaskSettings", "AWSGlue.DeleteColumnStatisticsTaskSettings"},
		{"DeleteConnection", "AWSGlue.DeleteConnection"},
		{"DeleteConnectionType", "AWSGlue.DeleteConnectionType"},
		{"DeleteCrawler", "AWSGlue.DeleteCrawler"},
		{"DeleteCustomEntityType", "AWSGlue.DeleteCustomEntityType"},
		{"DeleteDataQualityRuleset", "AWSGlue.DeleteDataQualityRuleset"},
		{"DeleteDatabase", "AWSGlue.DeleteDatabase"},
		{"DeleteDevEndpoint", "AWSGlue.DeleteDevEndpoint"},
		{"DeleteFormType", "AWSGlue.DeleteFormType"},
		{"DeleteGlossary", "AWSGlue.DeleteGlossary"},
		{"DeleteGlossaryTerm", "AWSGlue.DeleteGlossaryTerm"},
		{"DeleteGlueIdentityCenterConfiguration", "AWSGlue.DeleteGlueIdentityCenterConfiguration"},
		{"DeleteIntegration", "AWSGlue.DeleteIntegration"},
		{"DeleteIntegrationResourceProperty", "AWSGlue.DeleteIntegrationResourceProperty"},
		{"DeleteIntegrationTableProperties", "AWSGlue.DeleteIntegrationTableProperties"},
		{"DeleteJob", "AWSGlue.DeleteJob"},
		{"DeleteMLTransform", "AWSGlue.DeleteMLTransform"},
		{"DeletePartition", "AWSGlue.DeletePartition"},
		{"DeletePartitionIndex", "AWSGlue.DeletePartitionIndex"},
		{"DeleteRegistry", "AWSGlue.DeleteRegistry"},
		{"DeleteResourcePolicy", "AWSGlue.DeleteResourcePolicy"},
		{"DeleteSchema", "AWSGlue.DeleteSchema"},
		{"DeleteSchemaVersions", "AWSGlue.DeleteSchemaVersions"},
		{"DeleteSecurityConfiguration", "AWSGlue.DeleteSecurityConfiguration"},
		{"DeleteSession", "AWSGlue.DeleteSession"},
		{"DeleteTable", "AWSGlue.DeleteTable"},
		{"DeleteTableOptimizer", "AWSGlue.DeleteTableOptimizer"},
		{"DeleteTableVersion", "AWSGlue.DeleteTableVersion"},
		{"DeleteTrigger", "AWSGlue.DeleteTrigger"},
		{"DeleteUsageProfile", "AWSGlue.DeleteUsageProfile"},
		{"DeleteUserDefinedFunction", "AWSGlue.DeleteUserDefinedFunction"},
		{"DeleteWorkflow", "AWSGlue.DeleteWorkflow"},
		{"DescribeConnectionType", "AWSGlue.DescribeConnectionType"},
		{"DescribeEntity", "AWSGlue.DescribeEntity"},
		{"DescribeInboundIntegrations", "AWSGlue.DescribeInboundIntegrations"},
		{"DescribeIntegrations", "AWSGlue.DescribeIntegrations"},
		{"DisassociateGlossaryTerms", "AWSGlue.DisassociateGlossaryTerms"},
		{"GetAsset", "AWSGlue.GetAsset"},
		{"GetAssetType", "AWSGlue.GetAssetType"},
		{"GetBlueprint", "AWSGlue.GetBlueprint"},
		{"GetBlueprintRun", "AWSGlue.GetBlueprintRun"},
		{"GetBlueprintRuns", "AWSGlue.GetBlueprintRuns"},
		{"GetCatalog", "AWSGlue.GetCatalog"},
		{"GetCatalogImportStatus", "AWSGlue.GetCatalogImportStatus"},
		{"GetCatalogs", "AWSGlue.GetCatalogs"},
		{"GetClassifier", "AWSGlue.GetClassifier"},
		{"GetClassifiers", "AWSGlue.GetClassifiers"},
		{"GetColumnStatisticsForPartition", "AWSGlue.GetColumnStatisticsForPartition"},
		{"GetColumnStatisticsForTable", "AWSGlue.GetColumnStatisticsForTable"},
		{"GetColumnStatisticsTaskRun", "AWSGlue.GetColumnStatisticsTaskRun"},
		{"GetColumnStatisticsTaskRuns", "AWSGlue.GetColumnStatisticsTaskRuns"},
		{"GetColumnStatisticsTaskSettings", "AWSGlue.GetColumnStatisticsTaskSettings"},
		{"GetConnection", "AWSGlue.GetConnection"},
		{"GetConnections", "AWSGlue.GetConnections"},
		{"GetCrawler", "AWSGlue.GetCrawler"},
		{"GetCrawlerMetrics", "AWSGlue.GetCrawlerMetrics"},
		{"GetCrawlers", "AWSGlue.GetCrawlers"},
		{"GetCustomEntityType", "AWSGlue.GetCustomEntityType"},
		{"GetDashboardUrl", "AWSGlue.GetDashboardUrl"},
		{"GetDataCatalogEncryptionSettings", "AWSGlue.GetDataCatalogEncryptionSettings"},
		{"GetDataCatalogExportConfiguration", "AWSGlue.GetDataCatalogExportConfiguration"},
		{"GetDataQualityModel", "AWSGlue.GetDataQualityModel"},
		{"GetDataQualityModelResult", "AWSGlue.GetDataQualityModelResult"},
		{"GetDataQualityResult", "AWSGlue.GetDataQualityResult"},
		{"GetDataQualityRuleRecommendationRun", "AWSGlue.GetDataQualityRuleRecommendationRun"},
		{"GetDataQualityRuleset", "AWSGlue.GetDataQualityRuleset"},
		{"GetDataQualityRulesetEvaluationRun", "AWSGlue.GetDataQualityRulesetEvaluationRun"},
		{"GetDatabase", "AWSGlue.GetDatabase"},
		{"GetDatabases", "AWSGlue.GetDatabases"},
		{"GetDataflowGraph", "AWSGlue.GetDataflowGraph"},
		{"GetDevEndpoint", "AWSGlue.GetDevEndpoint"},
		{"GetDevEndpoints", "AWSGlue.GetDevEndpoints"},
		{"GetEntityRecords", "AWSGlue.GetEntityRecords"},
		{"GetFormType", "AWSGlue.GetFormType"},
		{"GetGlossary", "AWSGlue.GetGlossary"},
		{"GetGlossaryTerm", "AWSGlue.GetGlossaryTerm"},
		{"GetGlueIdentityCenterConfiguration", "AWSGlue.GetGlueIdentityCenterConfiguration"},
		{"GetIntegrationResourceProperty", "AWSGlue.GetIntegrationResourceProperty"},
		{"GetIntegrationTableProperties", "AWSGlue.GetIntegrationTableProperties"},
		{"GetJob", "AWSGlue.GetJob"},
		{"GetJobBookmark", "AWSGlue.GetJobBookmark"},
		{"GetJobRun", "AWSGlue.GetJobRun"},
		{"GetJobRuns", "AWSGlue.GetJobRuns"},
		{"GetJobs", "AWSGlue.GetJobs"},
		{"GetMLTaskRun", "AWSGlue.GetMLTaskRun"},
		{"GetMLTaskRuns", "AWSGlue.GetMLTaskRuns"},
		{"GetMLTransform", "AWSGlue.GetMLTransform"},
		{"GetMLTransforms", "AWSGlue.GetMLTransforms"},
		{"GetMapping", "AWSGlue.GetMapping"},
		{"GetMaterializedViewRefreshTaskRun", "AWSGlue.GetMaterializedViewRefreshTaskRun"},
		{"GetPartition", "AWSGlue.GetPartition"},
		{"GetPartitionIndexes", "AWSGlue.GetPartitionIndexes"},
		{"GetPartitions", "AWSGlue.GetPartitions"},
		{"GetPlan", "AWSGlue.GetPlan"},
		{"GetRegistry", "AWSGlue.GetRegistry"},
		{"GetResourcePolicies", "AWSGlue.GetResourcePolicies"},
		{"GetResourcePolicy", "AWSGlue.GetResourcePolicy"},
		{"GetSchema", "AWSGlue.GetSchema"},
		{"GetSchemaByDefinition", "AWSGlue.GetSchemaByDefinition"},
		{"GetSchemaVersion", "AWSGlue.GetSchemaVersion"},
		{"GetSchemaVersionsDiff", "AWSGlue.GetSchemaVersionsDiff"},
		{"GetSecurityConfiguration", "AWSGlue.GetSecurityConfiguration"},
		{"GetSecurityConfigurations", "AWSGlue.GetSecurityConfigurations"},
		{"GetSession", "AWSGlue.GetSession"},
		{"GetSessionEndpoint", "AWSGlue.GetSessionEndpoint"},
		{"GetStatement", "AWSGlue.GetStatement"},
		{"GetTable", "AWSGlue.GetTable"},
		{"GetTableOptimizer", "AWSGlue.GetTableOptimizer"},
		{"GetTableVersion", "AWSGlue.GetTableVersion"},
		{"GetTableVersions", "AWSGlue.GetTableVersions"},
		{"GetTables", "AWSGlue.GetTables"},
		{"GetTags", "AWSGlue.GetTags"},
		{"GetTrigger", "AWSGlue.GetTrigger"},
		{"GetTriggers", "AWSGlue.GetTriggers"},
		{"GetUnfilteredPartitionMetadata", "AWSGlue.GetUnfilteredPartitionMetadata"},
		{"GetUnfilteredPartitionsMetadata", "AWSGlue.GetUnfilteredPartitionsMetadata"},
		{"GetUnfilteredTableMetadata", "AWSGlue.GetUnfilteredTableMetadata"},
		{"GetUsageProfile", "AWSGlue.GetUsageProfile"},
		{"GetUserDefinedFunction", "AWSGlue.GetUserDefinedFunction"},
		{"GetUserDefinedFunctions", "AWSGlue.GetUserDefinedFunctions"},
		{"GetWorkflow", "AWSGlue.GetWorkflow"},
		{"GetWorkflowRun", "AWSGlue.GetWorkflowRun"},
		{"GetWorkflowRunProperties", "AWSGlue.GetWorkflowRunProperties"},
		{"GetWorkflowRuns", "AWSGlue.GetWorkflowRuns"},
		{"ImportCatalogToGlue", "AWSGlue.ImportCatalogToGlue"},
		{"ListAssetTypes", "AWSGlue.ListAssetTypes"},
		{"ListBlueprints", "AWSGlue.ListBlueprints"},
		{"ListColumnStatisticsTaskRuns", "AWSGlue.ListColumnStatisticsTaskRuns"},
		{"ListConnectionTypes", "AWSGlue.ListConnectionTypes"},
		{"ListCrawlers", "AWSGlue.ListCrawlers"},
		{"ListCrawls", "AWSGlue.ListCrawls"},
		{"ListCustomEntityTypes", "AWSGlue.ListCustomEntityTypes"},
		{"ListDataQualityResults", "AWSGlue.ListDataQualityResults"},
		{"ListDataQualityRuleRecommendationRuns", "AWSGlue.ListDataQualityRuleRecommendationRuns"},
		{"ListDataQualityRulesetEvaluationRuns", "AWSGlue.ListDataQualityRulesetEvaluationRuns"},
		{"ListDataQualityRulesets", "AWSGlue.ListDataQualityRulesets"},
		{"ListDataQualityStatisticAnnotations", "AWSGlue.ListDataQualityStatisticAnnotations"},
		{"ListDataQualityStatistics", "AWSGlue.ListDataQualityStatistics"},
		{"ListDevEndpoints", "AWSGlue.ListDevEndpoints"},
		{"ListEntities", "AWSGlue.ListEntities"},
		{"ListFormTypes", "AWSGlue.ListFormTypes"},
		{"ListGlossaries", "AWSGlue.ListGlossaries"},
		{"ListGlossaryTerms", "AWSGlue.ListGlossaryTerms"},
		{"ListIntegrationResourceProperties", "AWSGlue.ListIntegrationResourceProperties"},
		{"ListIterableForms", "AWSGlue.ListIterableForms"},
		{"ListJobs", "AWSGlue.ListJobs"},
		{"ListMLTransforms", "AWSGlue.ListMLTransforms"},
		{"ListMaterializedViewRefreshTaskRuns", "AWSGlue.ListMaterializedViewRefreshTaskRuns"},
		{"ListRegistries", "AWSGlue.ListRegistries"},
		{"ListSchemaVersions", "AWSGlue.ListSchemaVersions"},
		{"ListSchemas", "AWSGlue.ListSchemas"},
		{"ListSessions", "AWSGlue.ListSessions"},
		{"ListStatements", "AWSGlue.ListStatements"},
		{"ListTableOptimizerRuns", "AWSGlue.ListTableOptimizerRuns"},
		{"ListTriggers", "AWSGlue.ListTriggers"},
		{"ListUsageProfiles", "AWSGlue.ListUsageProfiles"},
		{"ListWorkflows", "AWSGlue.ListWorkflows"},
		{"ModifyIntegration", "AWSGlue.ModifyIntegration"},
		{"PutAsset", "AWSGlue.PutAsset"},
		{"PutAssetType", "AWSGlue.PutAssetType"},
		{"PutAttachment", "AWSGlue.PutAttachment"},
		{"PutDataCatalogEncryptionSettings", "AWSGlue.PutDataCatalogEncryptionSettings"},
		{"PutDataCatalogExportConfiguration", "AWSGlue.PutDataCatalogExportConfiguration"},
		{"PutDataQualityProfileAnnotation", "AWSGlue.PutDataQualityProfileAnnotation"},
		{"PutFormType", "AWSGlue.PutFormType"},
		{"PutResourcePolicy", "AWSGlue.PutResourcePolicy"},
		{"PutSchemaVersionMetadata", "AWSGlue.PutSchemaVersionMetadata"},
		{"PutWorkflowRunProperties", "AWSGlue.PutWorkflowRunProperties"},
		{"QuerySchemaVersionMetadata", "AWSGlue.QuerySchemaVersionMetadata"},
		{"RegisterConnectionType", "AWSGlue.RegisterConnectionType"},
		{"RegisterSchemaVersion", "AWSGlue.RegisterSchemaVersion"},
		{"RemoveSchemaVersionMetadata", "AWSGlue.RemoveSchemaVersionMetadata"},
		{"ResetJobBookmark", "AWSGlue.ResetJobBookmark"},
		{"ResumeWorkflowRun", "AWSGlue.ResumeWorkflowRun"},
		{"RunStatement", "AWSGlue.RunStatement"},
		{"SearchAssets", "AWSGlue.SearchAssets"},
		{"SearchTables", "AWSGlue.SearchTables"},
		{"StartBlueprintRun", "AWSGlue.StartBlueprintRun"},
		{"StartColumnStatisticsTaskRun", "AWSGlue.StartColumnStatisticsTaskRun"},
		{"StartColumnStatisticsTaskRunSchedule", "AWSGlue.StartColumnStatisticsTaskRunSchedule"},
		{"StartCrawler", "AWSGlue.StartCrawler"},
		{"StartCrawlerSchedule", "AWSGlue.StartCrawlerSchedule"},
		{"StartDataQualityRuleRecommendationRun", "AWSGlue.StartDataQualityRuleRecommendationRun"},
		{"StartDataQualityRulesetEvaluationRun", "AWSGlue.StartDataQualityRulesetEvaluationRun"},
		{"StartExportLabelsTaskRun", "AWSGlue.StartExportLabelsTaskRun"},
		{"StartImportLabelsTaskRun", "AWSGlue.StartImportLabelsTaskRun"},
		{"StartJobRun", "AWSGlue.StartJobRun"},
		{"StartMLEvaluationTaskRun", "AWSGlue.StartMLEvaluationTaskRun"},
		{"StartMLLabelingSetGenerationTaskRun", "AWSGlue.StartMLLabelingSetGenerationTaskRun"},
		{"StartMaterializedViewRefreshTaskRun", "AWSGlue.StartMaterializedViewRefreshTaskRun"},
		{"StartTrigger", "AWSGlue.StartTrigger"},
		{"StartWorkflowRun", "AWSGlue.StartWorkflowRun"},
		{"StopColumnStatisticsTaskRun", "AWSGlue.StopColumnStatisticsTaskRun"},
		{"StopColumnStatisticsTaskRunSchedule", "AWSGlue.StopColumnStatisticsTaskRunSchedule"},
		{"StopCrawler", "AWSGlue.StopCrawler"},
		{"StopCrawlerSchedule", "AWSGlue.StopCrawlerSchedule"},
		{"StopMaterializedViewRefreshTaskRun", "AWSGlue.StopMaterializedViewRefreshTaskRun"},
		{"StopSession", "AWSGlue.StopSession"},
		{"StopTrigger", "AWSGlue.StopTrigger"},
		{"StopWorkflowRun", "AWSGlue.StopWorkflowRun"},
		{"TagResource", "AWSGlue.TagResource"},
		{"TestConnection", "AWSGlue.TestConnection"},
		{"UntagResource", "AWSGlue.UntagResource"},
		{"UpdateAsset", "AWSGlue.UpdateAsset"},
		{"UpdateBlueprint", "AWSGlue.UpdateBlueprint"},
		{"UpdateCatalog", "AWSGlue.UpdateCatalog"},
		{"UpdateClassifier", "AWSGlue.UpdateClassifier"},
		{"UpdateColumnStatisticsForPartition", "AWSGlue.UpdateColumnStatisticsForPartition"},
		{"UpdateColumnStatisticsForTable", "AWSGlue.UpdateColumnStatisticsForTable"},
		{"UpdateColumnStatisticsTaskSettings", "AWSGlue.UpdateColumnStatisticsTaskSettings"},
		{"UpdateConnection", "AWSGlue.UpdateConnection"},
		{"UpdateCrawler", "AWSGlue.UpdateCrawler"},
		{"UpdateCrawlerSchedule", "AWSGlue.UpdateCrawlerSchedule"},
		{"UpdateDataQualityRuleset", "AWSGlue.UpdateDataQualityRuleset"},
		{"UpdateDatabase", "AWSGlue.UpdateDatabase"},
		{"UpdateDevEndpoint", "AWSGlue.UpdateDevEndpoint"},
		{"UpdateGlossary", "AWSGlue.UpdateGlossary"},
		{"UpdateGlossaryTerm", "AWSGlue.UpdateGlossaryTerm"},
		{"UpdateGlueIdentityCenterConfiguration", "AWSGlue.UpdateGlueIdentityCenterConfiguration"},
		{"UpdateIntegrationResourceProperty", "AWSGlue.UpdateIntegrationResourceProperty"},
		{"UpdateIntegrationTableProperties", "AWSGlue.UpdateIntegrationTableProperties"},
		{"UpdateJob", "AWSGlue.UpdateJob"},
		{"UpdateJobFromSourceControl", "AWSGlue.UpdateJobFromSourceControl"},
		{"UpdateMLTransform", "AWSGlue.UpdateMLTransform"},
		{"UpdatePartition", "AWSGlue.UpdatePartition"},
		{"UpdateRegistry", "AWSGlue.UpdateRegistry"},
		{"UpdateSchema", "AWSGlue.UpdateSchema"},
		{"UpdateSourceControlFromJob", "AWSGlue.UpdateSourceControlFromJob"},
		{"UpdateTable", "AWSGlue.UpdateTable"},
		{"UpdateTableOptimizer", "AWSGlue.UpdateTableOptimizer"},
		{"UpdateTrigger", "AWSGlue.UpdateTrigger"},
		{"UpdateUsageProfile", "AWSGlue.UpdateUsageProfile"},
		{"UpdateUserDefinedFunction", "AWSGlue.UpdateUserDefinedFunction"},
		{"UpdateWorkflow", "AWSGlue.UpdateWorkflow"},
	}
}

// TestExtractOperation_SDKRouteTable drives every real Glue operation's
// authoritative X-Amz-Target through ExtractOperation and Handler(),
// asserting the header resolves to the right op name and that Handler()
// does not fall through to the "UnknownOperationException" sentinel that a
// dispatch-table key mismatch would produce. That sentinel (errUnknownAction
// in handler.go) has exactly one production call site -- the dispatch()
// miss in the h.ops map lookup -- so it cannot collide with a legitimate
// error on this all-empty-body table.
func TestExtractOperation_SDKRouteTable(t *testing.T) {
	t.Parallel()

	for _, tc := range sdkRouteCases() {
		t.Run(strings.ToLower(tc.op), func(t *testing.T) {
			t.Parallel()

			backend := glue.NewInMemoryBackend("000000000000", "us-east-1")
			h := glue.NewHandler(backend)
			e := echo.New()
			req := httptest.NewRequest(http.MethodPost, "/", strings.NewReader("{}"))
			req.Header.Set("X-Amz-Target", tc.target)
			rec := httptest.NewRecorder()
			c := e.NewContext(req, rec)

			got := h.ExtractOperation(c)
			assert.Equal(t, tc.op, got)

			require.NoError(t, h.Handler()(c))
			assert.NotContains(t, rec.Body.String(), "UnknownOperationException",
				"target=%s op=%s: dispatched to the unmatched-route handler", tc.target, tc.op)
		})
	}
}
