package ssm_test

import (
	"testing"

	ssmsdk "github.com/aws/aws-sdk-go-v2/service/ssm"
	"github.com/blackbirdworks/gopherstack/pkgs/sdkcheck"
	"github.com/blackbirdworks/gopherstack/services/ssm"
)

// TestSDKCompleteness verifies that every operation exposed by the AWS SDK v2
// ssm client is either listed in GetSupportedOperations() or explicitly
// acknowledged in the notImplemented slice.  The test fails when the upstream
// SDK adds a new operation that gopherstack has not yet handled.
func TestSDKCompleteness(t *testing.T) {
	t.Parallel()

	backend := ssm.NewInMemoryBackend()
	h := ssm.NewHandler(backend)
	sdkcheck.CheckCompleteness(t, &ssmsdk.Client{}, h.GetSupportedOperations(), []string{
		"AssociateOpsItemRelatedItem",
		"CancelCommand",
		"CancelMaintenanceWindowExecution",
		"CreateActivation",
		"CreateAssociation",
		"CreateAssociationBatch",
		"CreateMaintenanceWindow",
		"CreateOpsItem",
		"CreateOpsMetadata",
		"CreatePatchBaseline",
		"CreateResourceDataSync",
		"DeleteActivation",
		"DeleteAssociation",
		"DeleteInventory",
		"DeleteMaintenanceWindow",
		"DeleteOpsItem",
		"DeleteOpsMetadata",
		"DeletePatchBaseline",
		"DeleteResourceDataSync",
		"DeleteResourcePolicy",
		"DeregisterManagedInstance",
		"DeregisterPatchBaselineForPatchGroup",
		"DeregisterTargetFromMaintenanceWindow",
		"DeregisterTaskFromMaintenanceWindow",
		"DescribeActivations",
		"DescribeAssociation",
		"DescribeAssociationExecutionTargets",
		"DescribeAssociationExecutions",
		"DescribeAutomationExecutions",
		"DescribeAutomationStepExecutions",
		"DescribeAvailablePatches",
		"DescribeEffectiveInstanceAssociations",
		"DescribeEffectivePatchesForPatchBaseline",
		"DescribeInstanceAssociationsStatus",
		"DescribeInstanceInformation",
		"DescribeInstancePatchStates",
		"DescribeInstancePatchStatesForPatchGroup",
		"DescribeInstancePatches",
		"DescribeInstanceProperties",
		"DescribeInventoryDeletions",
		"DescribeMaintenanceWindowExecutionTaskInvocations",
		"DescribeMaintenanceWindowExecutionTasks",
		"DescribeMaintenanceWindowExecutions",
		"DescribeMaintenanceWindowSchedule",
		"DescribeMaintenanceWindowTargets",
		"DescribeMaintenanceWindowTasks",
		"DescribeMaintenanceWindows",
		"DescribeMaintenanceWindowsForTarget",
		"DescribeOpsItems",
		"DescribePatchBaselines",
		"DescribePatchGroupState",
		"DescribePatchGroups",
		"DescribePatchProperties",
		"DescribeSessions",
		"DisassociateOpsItemRelatedItem",
		"GetAccessToken",
		"GetAutomationExecution",
		"GetCalendarState",
		"GetConnectionStatus",
		"GetDefaultPatchBaseline",
		"GetDeployablePatchSnapshotForInstance",
		"GetExecutionPreview",
		"GetInventory",
		"GetInventorySchema",
		"GetMaintenanceWindow",
		"GetMaintenanceWindowExecution",
		"GetMaintenanceWindowExecutionTask",
		"GetMaintenanceWindowExecutionTaskInvocation",
		"GetMaintenanceWindowTask",
		"GetOpsItem",
		"GetOpsMetadata",
		"GetOpsSummary",
		"GetPatchBaseline",
		"GetPatchBaselineForPatchGroup",
		"GetResourcePolicies",
		"GetServiceSetting",
		"LabelParameterVersion",
		"ListAssociationVersions",
		"ListAssociations",
		"ListComplianceItems",
		"ListComplianceSummaries",
		"ListDocumentMetadataHistory",
		"ListInventoryEntries",
		"ListNodes",
		"ListNodesSummary",
		"ListOpsItemEvents",
		"ListOpsItemRelatedItems",
		"ListOpsMetadata",
		"ListResourceComplianceSummaries",
		"ListResourceDataSync",
		"PutComplianceItems",
		"PutInventory",
		"PutResourcePolicy",
		"RegisterDefaultPatchBaseline",
		"RegisterPatchBaselineForPatchGroup",
		"RegisterTargetWithMaintenanceWindow",
		"RegisterTaskWithMaintenanceWindow",
		"ResetServiceSetting",
		"ResumeSession",
		"SendAutomationSignal",
		"StartAccessRequest",
		"StartAssociationsOnce",
		"StartAutomationExecution",
		"StartChangeRequestExecution",
		"StartExecutionPreview",
		"StartSession",
		"StopAutomationExecution",
		"TerminateSession",
		"UnlabelParameterVersion",
		"UpdateAssociation",
		"UpdateAssociationStatus",
		"UpdateDocumentDefaultVersion",
		"UpdateDocumentMetadata",
		"UpdateMaintenanceWindow",
		"UpdateMaintenanceWindowTarget",
		"UpdateMaintenanceWindowTask",
		"UpdateManagedInstanceRole",
		"UpdateOpsItem",
		"UpdateOpsMetadata",
		"UpdatePatchBaseline",
		"UpdateResourceDataSync",
		"UpdateServiceSetting",
	})
}
