package dms_test

import (
	"testing"

	dmssdk "github.com/aws/aws-sdk-go-v2/service/databasemigrationservice"
	"github.com/blackbirdworks/gopherstack/pkgs/sdkcheck"
	"github.com/blackbirdworks/gopherstack/services/dms"
)

// TestSDKCompleteness verifies that every operation exposed by the AWS SDK v2
// databasemigrationservice client is either listed in GetSupportedOperations() or explicitly
// acknowledged in the notImplemented slice.  The test fails when the upstream
// SDK adds a new operation that gopherstack has not yet handled.
func TestSDKCompleteness(t *testing.T) {
	t.Parallel()

	backend := dms.NewInMemoryBackend("000000000000", "us-east-1")
	h := dms.NewHandler(backend)
	sdkcheck.CheckCompleteness(t, &dmssdk.Client{}, h.GetSupportedOperations(), []string{
		"ApplyPendingMaintenanceAction",
		"BatchStartRecommendations",
		"CancelMetadataModelConversion",
		"CancelMetadataModelCreation",
		"CancelReplicationTaskAssessmentRun",
		"CreateDataMigration",
		"CreateDataProvider",
		"CreateEventSubscription",
		"CreateFleetAdvisorCollector",
		"CreateInstanceProfile",
		"CreateMigrationProject",
		"CreateReplicationConfig",
		"CreateReplicationSubnetGroup",
		"DeleteCertificate",
		"DeleteConnection",
		"DeleteDataMigration",
		"DeleteDataProvider",
		"DeleteEventSubscription",
		"DeleteFleetAdvisorCollector",
		"DeleteFleetAdvisorDatabases",
		"DeleteInstanceProfile",
		"DeleteMigrationProject",
		"DeleteReplicationConfig",
		"DeleteReplicationSubnetGroup",
		"DeleteReplicationTaskAssessmentRun",
		"DescribeAccountAttributes",
		"DescribeApplicableIndividualAssessments",
		"DescribeCertificates",
		"DescribeConnections",
		"DescribeConversionConfiguration",
		"DescribeDataMigrations",
		"DescribeDataProviders",
		"DescribeEndpointSettings",
		"DescribeEndpointTypes",
		"DescribeEngineVersions",
		"DescribeEventCategories",
		"DescribeEventSubscriptions",
		"DescribeEvents",
		"DescribeExtensionPackAssociations",
		"DescribeFleetAdvisorCollectors",
		"DescribeFleetAdvisorDatabases",
		"DescribeFleetAdvisorLsaAnalysis",
		"DescribeFleetAdvisorSchemaObjectSummary",
		"DescribeFleetAdvisorSchemas",
		"DescribeInstanceProfiles",
		"DescribeMetadataModel",
		"DescribeMetadataModelAssessments",
		"DescribeMetadataModelChildren",
		"DescribeMetadataModelConversions",
		"DescribeMetadataModelCreations",
		"DescribeMetadataModelExportsAsScript",
		"DescribeMetadataModelExportsToTarget",
		"DescribeMetadataModelImports",
		"DescribeMigrationProjects",
		"DescribeOrderableReplicationInstances",
		"DescribePendingMaintenanceActions",
		"DescribeRecommendationLimitations",
		"DescribeRecommendations",
		"DescribeRefreshSchemasStatus",
		"DescribeReplicationConfigs",
		"DescribeReplicationInstanceTaskLogs",
		"DescribeReplicationSubnetGroups",
		"DescribeReplicationTableStatistics",
		"DescribeReplicationTaskAssessmentResults",
		"DescribeReplicationTaskAssessmentRuns",
		"DescribeReplicationTaskIndividualAssessments",
		"DescribeReplications",
		"DescribeSchemas",
		"DescribeTableStatistics",
		"ExportMetadataModelAssessment",
		"GetTargetSelectionRules",
		"ImportCertificate",
		"ModifyConversionConfiguration",
		"ModifyDataMigration",
		"ModifyDataProvider",
		"ModifyEndpoint",
		"ModifyEventSubscription",
		"ModifyInstanceProfile",
		"ModifyMigrationProject",
		"ModifyReplicationConfig",
		"ModifyReplicationInstance",
		"ModifyReplicationSubnetGroup",
		"ModifyReplicationTask",
		"MoveReplicationTask",
		"RebootReplicationInstance",
		"RefreshSchemas",
		"ReloadReplicationTables",
		"ReloadTables",
		"RemoveTagsFromResource",
		"RunFleetAdvisorLsaAnalysis",
		"StartDataMigration",
		"StartExtensionPackAssociation",
		"StartMetadataModelAssessment",
		"StartMetadataModelConversion",
		"StartMetadataModelCreation",
		"StartMetadataModelExportAsScript",
		"StartMetadataModelExportToTarget",
		"StartMetadataModelImport",
		"StartRecommendations",
		"StartReplication",
		"StartReplicationTaskAssessment",
		"StartReplicationTaskAssessmentRun",
		"StopDataMigration",
		"StopReplication",
		"TestConnection",
		"UpdateSubscriptionsToEventBridge",
	})
}
