package pinpoint_test

import (
	"testing"

	pinpointsdk "github.com/aws/aws-sdk-go-v2/service/pinpoint"
	"github.com/blackbirdworks/gopherstack/pkgs/sdkcheck"
	"github.com/blackbirdworks/gopherstack/services/pinpoint"
)

// TestSDKCompleteness verifies that every operation exposed by the AWS SDK v2
// pinpoint client is either listed in GetSupportedOperations() or explicitly
// acknowledged in the notImplemented slice.  The test fails when the upstream
// SDK adds a new operation that gopherstack has not yet handled.
func TestSDKCompleteness(t *testing.T) {
	t.Parallel()

	backend := pinpoint.NewInMemoryBackend("us-east-1", "000000000000")
	h := pinpoint.NewHandler(backend)
	sdkcheck.CheckCompleteness(t, &pinpointsdk.Client{}, h.GetSupportedOperations(), []string{
		"CreateVoiceTemplate",
		"DeleteAdmChannel",
		"DeleteApnsChannel",
		"DeleteApnsSandboxChannel",
		"DeleteApnsVoipChannel",
		"DeleteApnsVoipSandboxChannel",
		"DeleteBaiduChannel",
		"DeleteCampaign",
		"DeleteEmailChannel",
		"DeleteEmailTemplate",
		"DeleteEndpoint",
		"DeleteEventStream",
		"DeleteGcmChannel",
		"DeleteInAppTemplate",
		"DeleteJourney",
		"DeletePushTemplate",
		"DeleteRecommenderConfiguration",
		"DeleteSegment",
		"DeleteSmsChannel",
		"DeleteSmsTemplate",
		"DeleteUserEndpoints",
		"DeleteVoiceChannel",
		"DeleteVoiceTemplate",
		"GetAdmChannel",
		"GetApnsChannel",
		"GetApnsSandboxChannel",
		"GetApnsVoipChannel",
		"GetApnsVoipSandboxChannel",
		"GetApplicationDateRangeKpi",
		"GetBaiduChannel",
		"GetCampaign",
		"GetCampaignActivities",
		"GetCampaignDateRangeKpi",
		"GetCampaignVersion",
		"GetCampaignVersions",
		"GetCampaigns",
		"GetChannels",
		"GetEmailChannel",
		"GetEmailTemplate",
		"GetEndpoint",
		"GetEventStream",
		"GetExportJob",
		"GetExportJobs",
		"GetGcmChannel",
		"GetImportJob",
		"GetImportJobs",
		"GetInAppMessages",
		"GetInAppTemplate",
		"GetJourney",
		"GetJourneyDateRangeKpi",
		"GetJourneyExecutionActivityMetrics",
		"GetJourneyExecutionMetrics",
		"GetJourneyRunExecutionActivityMetrics",
		"GetJourneyRunExecutionMetrics",
		"GetJourneyRuns",
		"GetPushTemplate",
		"GetRecommenderConfiguration",
		"GetRecommenderConfigurations",
		"GetSegment",
		"GetSegmentExportJobs",
		"GetSegmentImportJobs",
		"GetSegmentVersion",
		"GetSegmentVersions",
		"GetSegments",
		"GetSmsChannel",
		"GetSmsTemplate",
		"GetUserEndpoints",
		"GetVoiceChannel",
		"GetVoiceTemplate",
		"ListJourneys",
		"ListTemplateVersions",
		"ListTemplates",
		"PhoneNumberValidate",
		"PutEventStream",
		"PutEvents",
		"RemoveAttributes",
		"SendMessages",
		"SendOTPMessage",
		"SendUsersMessages",
		"UpdateAdmChannel",
		"UpdateApnsChannel",
		"UpdateApnsSandboxChannel",
		"UpdateApnsVoipChannel",
		"UpdateApnsVoipSandboxChannel",
		"UpdateBaiduChannel",
		"UpdateCampaign",
		"UpdateEmailChannel",
		"UpdateEmailTemplate",
		"UpdateEndpoint",
		"UpdateEndpointsBatch",
		"UpdateGcmChannel",
		"UpdateInAppTemplate",
		"UpdateJourney",
		"UpdateJourneyState",
		"UpdatePushTemplate",
		"UpdateRecommenderConfiguration",
		"UpdateSegment",
		"UpdateSmsChannel",
		"UpdateSmsTemplate",
		"UpdateTemplateActiveVersion",
		"UpdateVoiceChannel",
		"UpdateVoiceTemplate",
		"VerifyOTPMessage",
	})
}
