package cognitoidp

import (
	"crypto/hmac"
	"crypto/rand"
	"encoding/base32"
	"fmt"
	"slices"
	"sort"
	"time"
)

// mfaSessionTTL is the lifetime of an MFA or challenge session token.
const mfaSessionTTL = 3 * time.Minute

// mfaSessionLen is the character length of randomly generated MFA session tokens.
const mfaSessionLen = 64

// totpCodeLen is the expected length of a TOTP code.
const totpCodeLen = 6

// newMFASession stores a new session entry and returns an AuthResult with the challenge.
// For SMS_MFA/EMAIL_OTP a one-time numeric code is generated and stored on the session so
// RespondToMFAChallenge can require an exact match, the same way ForgotPassword/SignUp
// confirmation codes are validated elsewhere in this backend (there is no real SMS/email
// gateway to deliver the code out of band, so simulation is the best available proxy — but
// unlike a bare format check, "any 6 digits" is no longer accepted).
func (b *InMemoryBackend) newMFASession(pool *UserPool, clientID, username, challengeType string) *AuthResult {
	sessionToken := randomAlphanumeric(mfaSessionLen)

	entry := &mfaSessionEntry{
		PoolID:        pool.ID,
		ClientID:      clientID,
		Username:      username,
		ChallengeType: challengeType,
		ExpiresAt:     time.Now().Add(mfaSessionTTL),
	}

	if challengeType == challengeSMSMFA || challengeType == challengeEmailOTP {
		entry.Code = randomNumeric(totpCodeLen)
	}

	b.mfaSessions[sessionToken] = entry

	return &AuthResult{
		MFASession:    sessionToken,
		ChallengeName: challengeType,
	}
}

// mfaChallengeType returns the challenge type to use given pool config and user preference.
func mfaChallengeType(_ *UserPool, user *User) string {
	if user.PreferredMfaSetting != "" {
		return user.PreferredMfaSetting
	}

	return challengeSoftwareTokenMFA
}

// RespondToMFAChallenge validates an MFA session and the user-supplied code, then issues
// tokens. SOFTWARE_TOKEN_MFA is verified as a real RFC 6238 TOTP code against the user's
// AssociateSoftwareToken secret; SMS_MFA/EMAIL_OTP are verified against the one-time code
// generated when the challenge session was created (see newMFASession). A wrong code
// returns CodeMismatchException without consuming the session, so the caller may retry
// until the session expires — matching real Cognito.
func (b *InMemoryBackend) RespondToMFAChallenge(clientID, session, code string) (*TokenResult, error) {
	b.mu.Lock("RespondToMFAChallenge")
	defer b.mu.Unlock()

	if len(code) != totpCodeLen {
		return nil, fmt.Errorf("%w: code must be %d digits", ErrCodeMismatch, totpCodeLen)
	}

	for _, ch := range code {
		if ch < '0' || ch > '9' {
			return nil, fmt.Errorf("%w: code must contain only digits", ErrCodeMismatch)
		}
	}

	entry, ok := b.mfaSessions[session]
	if !ok {
		return nil, fmt.Errorf("%w: MFA session not found or expired", ErrNotAuthorized)
	}

	if !entry.ExpiresAt.IsZero() && time.Now().After(entry.ExpiresAt) {
		delete(b.mfaSessions, session)

		return nil, fmt.Errorf("%w: MFA session not found or expired", ErrNotAuthorized)
	}

	if entry.ClientID != clientID {
		return nil, fmt.Errorf("%w: MFA session was issued for a different client", ErrNotAuthorized)
	}

	pool, ok := b.pools.Get(entry.PoolID)
	if !ok {
		return nil, fmt.Errorf("%w: user pool %q not found", ErrUserPoolNotFound, entry.PoolID)
	}

	user, ok := b.users.Get(userKey(entry.PoolID, entry.Username))
	if !ok {
		return nil, fmt.Errorf("%w: user %q not found", ErrUserNotFound, entry.Username)
	}

	if err := verifyMFAChallengeCode(entry, user, code); err != nil {
		// Do not consume the session on a wrong code: the caller may retry until it expires.
		return nil, err
	}

	// Consume the session (one-time use).
	delete(b.mfaSessions, session)

	result, err := b.issueTokensLocked(pool, clientID, user, triggerSourceTokenGenAuthentication)
	if err != nil {
		return nil, err
	}

	return result.Tokens, nil
}

// verifyMFAChallengeCode validates code against the challenge type recorded on the MFA
// session. SOFTWARE_TOKEN_MFA is verified cryptographically (RFC 6238 TOTP) against the
// user's secret; SMS_MFA/EMAIL_OTP are verified against the code generated by
// newMFASession, since there is no client-held secret to re-derive those from.
func verifyMFAChallengeCode(entry *mfaSessionEntry, user *User, code string) error {
	switch entry.ChallengeType {
	case challengeSoftwareTokenMFA:
		if user.TOTPSecret == "" {
			return fmt.Errorf("%w: no TOTP secret associated; call AssociateSoftwareToken first", ErrNotAuthorized)
		}

		if !verifyTOTPCode(user.TOTPSecret, code, time.Now()) {
			return fmt.Errorf("%w: invalid software token code", ErrCodeMismatch)
		}

		return nil

	case challengeSMSMFA, challengeEmailOTP:
		if entry.Code == "" || !hmac.Equal([]byte(entry.Code), []byte(code)) {
			return fmt.Errorf("%w: invalid MFA code", ErrCodeMismatch)
		}

		return nil

	default:
		return fmt.Errorf("%w: unexpected challenge type %q for MFA response", ErrCodeMismatch, entry.ChallengeType)
	}
}

// Challenge name constants for auth challenge flows.
const (
	challengeSoftwareTokenMFA    = "SOFTWARE_TOKEN_MFA"
	challengeNewPasswordRequired = "NEW_PASSWORD_REQUIRED"
	challengeSMSMFA              = "SMS_MFA"
	challengeEmailOTP            = "EMAIL_OTP"
)

// totpSecretLen is the number of random bytes for a TOTP secret (160-bit secret per RFC 6238).
const totpSecretLen = 20

// AssociateSoftwareToken generates a new TOTP secret for the authenticated user and stores it.
// Returns the base32-encoded secret for use with TOTP authenticator apps (RFC 6238).
func (b *InMemoryBackend) AssociateSoftwareToken(accessToken string) (string, error) {
	b.mu.Lock("AssociateSoftwareToken")
	defer b.mu.Unlock()

	user, err := b.findUserByAccessTokenLocked(accessToken)
	if err != nil {
		return "", err
	}

	secretBytes := make([]byte, totpSecretLen)
	if _, err = rand.Read(secretBytes); err != nil {
		return "", fmt.Errorf("generating TOTP secret: %w", err)
	}

	secret := base32.StdEncoding.WithPadding(base32.NoPadding).EncodeToString(secretBytes)
	user.TOTPSecret = secret
	user.TOTPVerified = false

	return secret, nil
}

// VerifySoftwareToken validates userCode as a real RFC 6238 TOTP code for the secret
// previously issued by AssociateSoftwareToken (HMAC-SHA1, 30s step, +/-1 step clock skew,
// matching an authenticator app such as Google Authenticator/Authy). Only the code that the
// secret actually produces at (approximately) the current time is accepted.
func (b *InMemoryBackend) VerifySoftwareToken(accessToken, userCode string) error {
	b.mu.Lock("VerifySoftwareToken")
	defer b.mu.Unlock()

	user, err := b.findUserByAccessTokenLocked(accessToken)
	if err != nil {
		return err
	}

	if user.TOTPSecret == "" {
		return fmt.Errorf("%w: no TOTP secret associated; call AssociateSoftwareToken first", ErrNotAuthorized)
	}

	if len(userCode) != totpCodeLen {
		return fmt.Errorf("%w: TOTP code must be %d digits", ErrCodeMismatch, totpCodeLen)
	}

	for _, ch := range userCode {
		if ch < '0' || ch > '9' {
			return fmt.Errorf("%w: TOTP code must contain only digits", ErrCodeMismatch)
		}
	}

	if !verifyTOTPCode(user.TOTPSecret, userCode, time.Now()) {
		return fmt.Errorf("%w: invalid software token code", ErrCodeMismatch)
	}

	user.TOTPVerified = true

	return nil
}

// SetUserMFAPreference sets the preferred MFA method for the authenticated user.
func (b *InMemoryBackend) SetUserMFAPreference(
	accessToken string,
	smsMFAEnabled, softwareTokenEnabled bool,
	preferredMFA string,
) error {
	b.mu.Lock("SetUserMFAPreference")
	defer b.mu.Unlock()

	user, err := b.findUserByAccessTokenLocked(accessToken)
	if err != nil {
		return err
	}

	return b.applyMFAPreferenceLocked(user, smsMFAEnabled, softwareTokenEnabled, preferredMFA)
}

// AdminSetUserMFASetting sets the MFA configuration for a specific user (admin operation).
func (b *InMemoryBackend) AdminSetUserMFASetting(
	userPoolID, username string,
	smsMFAEnabled, softwareTokenEnabled bool,
	preferredMFA string,
) error {
	b.mu.Lock("AdminSetUserMFASetting")
	defer b.mu.Unlock()

	if _, ok := b.pools.Get(userPoolID); !ok {
		return fmt.Errorf("%w: pool %q not found", ErrUserPoolNotFound, userPoolID)
	}

	user, ok := b.users.Get(userKey(userPoolID, username))
	if !ok {
		return fmt.Errorf("%w: user %q not found", ErrUserNotFound, username)
	}

	return b.applyMFAPreferenceLocked(user, smsMFAEnabled, softwareTokenEnabled, preferredMFA)
}

// applyMFAPreferenceLocked updates the MFA setting list and preferred MFA on a user.
// Caller must hold the write lock.
func (b *InMemoryBackend) applyMFAPreferenceLocked(
	user *User,
	smsMFAEnabled, softwareTokenEnabled bool,
	preferredMFA string,
) error {
	var settings []string

	if smsMFAEnabled {
		settings = append(settings, challengeSMSMFA)
	}

	if softwareTokenEnabled {
		settings = append(settings, challengeSoftwareTokenMFA)
	}

	sort.Strings(settings)
	user.UserMFASettingList = settings

	if preferredMFA != "" {
		found := slices.Contains(settings, preferredMFA)
		if !found && len(settings) > 0 {
			return fmt.Errorf(
				"%w: preferred MFA %q is not in the enabled MFA list",
				ErrInvalidUserPoolConfig,
				preferredMFA,
			)
		}
		user.PreferredMfaSetting = preferredMFA
	} else if len(settings) == 0 {
		user.PreferredMfaSetting = ""
	}

	user.UpdatedAt = time.Now()

	return nil
}

// EvictExpiredMFASessions removes mfaSession entries that have expired or whose pool or
// user no longer exists. The janitor calls this periodically to prevent unbounded accumulation.
func (b *InMemoryBackend) EvictExpiredMFASessions() {
	b.mu.Lock("EvictExpiredMFASessions")
	defer b.mu.Unlock()

	now := time.Now()

	for token, entry := range b.mfaSessions {
		if !entry.ExpiresAt.IsZero() && now.After(entry.ExpiresAt) {
			delete(b.mfaSessions, token)

			continue
		}

		if _, poolExists := b.pools.Get(entry.PoolID); !poolExists {
			delete(b.mfaSessions, token)

			continue
		}

		if _, userExists := b.users.Get(userKey(entry.PoolID, entry.Username)); !userExists {
			delete(b.mfaSessions, token)
		}
	}
}

// AdminSetUserMFAPreference sets the MFA preferences for a specific user (admin operation).
// This is the modern preferred API (vs AdminSetUserSettings). It delegates to AdminSetUserMFASetting.
func (b *InMemoryBackend) AdminSetUserMFAPreference(
	userPoolID, username string,
	smsMFAEnabled, softwareTokenEnabled bool,
	preferredMFA string,
) error {
	return b.AdminSetUserMFASetting(userPoolID, username, smsMFAEnabled, softwareTokenEnabled, preferredMFA)
}

// mfaConfigOFF is the default MFA configuration value when none is set.
const mfaConfigOFF = "OFF"

// AdminSetUserSettings persists legacy MFAOptions onto a user (admin operation).
func (b *InMemoryBackend) AdminSetUserSettings(userPoolID, username string, mfaOptions []MFAOptionType) error {
	b.mu.Lock("AdminSetUserSettings")
	defer b.mu.Unlock()

	if _, ok := b.pools.Get(userPoolID); !ok {
		return fmt.Errorf("%w: pool %q not found", ErrUserPoolNotFound, userPoolID)
	}

	user, ok := b.users.Get(userKey(userPoolID, username))
	if !ok {
		return fmt.Errorf("%w: user %q not found", ErrUserNotFound, username)
	}

	user.MFAOptions = mfaOptions

	return nil
}

// SetUserSettings persists legacy MFAOptions onto the authenticated user.
func (b *InMemoryBackend) SetUserSettings(accessToken string, mfaOptions []MFAOptionType) error {
	b.mu.Lock("SetUserSettings")
	defer b.mu.Unlock()

	user, err := b.findUserByAccessTokenLocked(accessToken)
	if err != nil {
		return err
	}

	user.MFAOptions = mfaOptions

	return nil
}
