package cognitoidp

import (
	"crypto/hmac"
	"crypto/rand"
	"encoding/base32"
	"fmt"
	"slices"
	"sort"
	"time"
)

// mfaSessionTTL is the lifetime of an MFA or challenge session token.
const mfaSessionTTL = 3 * time.Minute

// mfaSessionLen is the character length of randomly generated MFA session tokens.
const mfaSessionLen = 64

// totpCodeLen is the expected length of a TOTP code.
const totpCodeLen = 6

// newMFASession stores a new session entry and returns an AuthResult with the challenge.
// For SMS_MFA/EMAIL_OTP a one-time numeric code is generated and stored on the session so
// RespondToMFAChallenge can require an exact match, the same way ForgotPassword/SignUp
// confirmation codes are validated elsewhere in this backend (there is no real SMS/email
// gateway to deliver the code out of band, so simulation is the best available proxy — but
// unlike a bare format check, "any 6 digits" is no longer accepted).
func (b *InMemoryBackend) newMFASession(pool *UserPool, clientID, username, challengeType string) *AuthResult {
	sessionToken := randomAlphanumeric(mfaSessionLen)

	entry := &mfaSessionEntry{
		PoolID:        pool.ID,
		ClientID:      clientID,
		Username:      username,
		ChallengeType: challengeType,
		ExpiresAt:     time.Now().Add(mfaSessionTTL),
	}

	if challengeType == challengeSMSMFA || challengeType == challengeEmailOTP {
		entry.Code = randomNumeric(totpCodeLen)
	}

	b.mfaSessions[sessionToken] = entry

	return &AuthResult{
		MFASession:    sessionToken,
		ChallengeName: challengeType,
	}
}

// mfaChallengeType returns the challenge type to use given pool config and user preference.
// A user with no configured preference and no previously verified software token has no MFA
// factor to challenge for at all -- real Cognito returns MFA_SETUP in that case (InitiateAuth
// doc: "For users who are required to setup an MFA factor before they can sign in"), not
// SOFTWARE_TOKEN_MFA, which would be a dead end (RespondToMFAChallenge requires a TOTP secret
// that was never associated).
func mfaChallengeType(_ *UserPool, user *User) string {
	if user.PreferredMfaSetting != "" {
		return user.PreferredMfaSetting
	}

	if user.TOTPVerified {
		return challengeSoftwareTokenMFA
	}

	return challengeMFASetup
}

// RespondToMFAChallenge validates an MFA session and the user-supplied code, then issues
// tokens. SOFTWARE_TOKEN_MFA is verified as a real RFC 6238 TOTP code against the user's
// AssociateSoftwareToken secret; SMS_MFA/EMAIL_OTP are verified against the one-time code
// generated when the challenge session was created (see newMFASession). A wrong code
// returns CodeMismatchException without consuming the session, so the caller may retry
// until the session expires — matching real Cognito.
func (b *InMemoryBackend) RespondToMFAChallenge(clientID, session, code string) (*TokenResult, error) {
	b.mu.Lock("RespondToMFAChallenge")
	defer b.mu.Unlock()

	if len(code) != totpCodeLen {
		return nil, fmt.Errorf("%w: code must be %d digits", ErrCodeMismatch, totpCodeLen)
	}

	for _, ch := range code {
		if ch < '0' || ch > '9' {
			return nil, fmt.Errorf("%w: code must contain only digits", ErrCodeMismatch)
		}
	}

	entry, ok := b.mfaSessions[session]
	if !ok {
		return nil, fmt.Errorf("%w: MFA session not found or expired", ErrNotAuthorized)
	}

	if !entry.ExpiresAt.IsZero() && time.Now().After(entry.ExpiresAt) {
		delete(b.mfaSessions, session)

		return nil, fmt.Errorf("%w: MFA session not found or expired", ErrNotAuthorized)
	}

	if entry.ClientID != clientID {
		return nil, fmt.Errorf("%w: MFA session was issued for a different client", ErrNotAuthorized)
	}

	pool, ok := b.pools.Get(entry.PoolID)
	if !ok {
		return nil, fmt.Errorf("%w: user pool %q not found", ErrUserPoolNotFound, entry.PoolID)
	}

	user, ok := b.users.Get(userKey(entry.PoolID, entry.Username))
	if !ok {
		return nil, fmt.Errorf("%w: user %q not found", ErrUserNotFound, entry.Username)
	}

	if err := verifyMFAChallengeCode(entry, user, code); err != nil {
		// Do not consume the session on a wrong code: the caller may retry until it expires.
		return nil, err
	}

	// Consume the session (one-time use).
	delete(b.mfaSessions, session)

	result, err := b.issueTokensLocked(pool, clientID, user, triggerSourceTokenGenAuthentication)
	if err != nil {
		return nil, err
	}

	return result.Tokens, nil
}

// verifyMFAChallengeCode validates code against the challenge type recorded on the MFA
// session. SOFTWARE_TOKEN_MFA is verified cryptographically (RFC 6238 TOTP) against the
// user's secret; SMS_MFA/EMAIL_OTP are verified against the code generated by
// newMFASession, since there is no client-held secret to re-derive those from.
func verifyMFAChallengeCode(entry *mfaSessionEntry, user *User, code string) error {
	switch entry.ChallengeType {
	case challengeSoftwareTokenMFA:
		if user.TOTPSecret == "" {
			return fmt.Errorf("%w: no TOTP secret associated; call AssociateSoftwareToken first", ErrNotAuthorized)
		}

		if !verifyTOTPCode(user.TOTPSecret, code, time.Now()) {
			return fmt.Errorf("%w: invalid software token code", ErrCodeMismatch)
		}

		return nil

	case challengeSMSMFA, challengeEmailOTP:
		if entry.Code == "" || !hmac.Equal([]byte(entry.Code), []byte(code)) {
			return fmt.Errorf("%w: invalid MFA code", ErrCodeMismatch)
		}

		return nil

	default:
		return fmt.Errorf("%w: unexpected challenge type %q for MFA response", ErrCodeMismatch, entry.ChallengeType)
	}
}

// Challenge name constants for auth challenge flows.
const (
	challengeSoftwareTokenMFA    = "SOFTWARE_TOKEN_MFA"
	challengeNewPasswordRequired = "NEW_PASSWORD_REQUIRED"
	challengeSMSMFA              = "SMS_MFA"
	challengeEmailOTP            = "EMAIL_OTP"
	challengeMFASetup            = "MFA_SETUP"
)

// totpSecretLen is the number of random bytes for a TOTP secret (160-bit secret per RFC 6238).
const totpSecretLen = 20

// resolveMFASetupSubjectLocked resolves the user for AssociateSoftwareToken/
// VerifySoftwareToken, which document Session as an alternate to AccessToken: "You can
// provide either an access token or a session ID in the request"
// (api_op_AssociateSoftwareToken.go); "The request takes an access token or a session
// string, but not both" (api_op_VerifySoftwareToken.go). The session path serves the
// documented MFA_SETUP continuation flow, where InitiateAuth/RespondToAuthChallenge
// returned an MFA_SETUP challenge and no access token exists yet. Returns the resolved
// user and, for the session path, the same session token (echoed back so callers can
// thread it into their output's Session field). Caller must hold the write lock.
func (b *InMemoryBackend) resolveMFASetupSubjectLocked(accessToken, session string) (*User, string, error) {
	switch {
	case accessToken != "" && session != "":
		return nil, "", fmt.Errorf(
			"%w: provide either AccessToken or Session, not both", ErrInvalidParameter,
		)

	case accessToken != "":
		user, err := b.findUserByAccessTokenLocked(accessToken)

		return user, "", err

	case session != "":
		entry, ok := b.mfaSessions[session]
		if !ok {
			return nil, "", fmt.Errorf("%w: session not found or expired", ErrNotAuthorized)
		}

		if !entry.ExpiresAt.IsZero() && time.Now().After(entry.ExpiresAt) {
			delete(b.mfaSessions, session)

			return nil, "", fmt.Errorf("%w: session not found or expired", ErrNotAuthorized)
		}

		if entry.ChallengeType != challengeMFASetup {
			return nil, "", fmt.Errorf("%w: session is not an MFA_SETUP challenge", ErrNotAuthorized)
		}

		user, ok := b.users.Get(userKey(entry.PoolID, entry.Username))
		if !ok {
			// AssociateSoftwareToken's own deserializer models
			// NotAuthorizedException, not UserNotFoundException, and treats a
			// session whose user no longer exists the same as any other stale
			// session (consistent with the other session checks above).
			return nil, "", fmt.Errorf("%w: user %q not found", ErrNotAuthorized, entry.Username)
		}

		return user, session, nil

	default:
		return nil, "", fmt.Errorf("%w: AccessToken or Session is required", ErrInvalidParameter)
	}
}

// AssociateSoftwareToken generates a new TOTP secret for the user resolved via accessToken
// or session (exactly one must be supplied) and stores it. Returns the base32-encoded
// secret for use with TOTP authenticator apps (RFC 6238), plus the session to echo back
// when the caller used the session path (empty for the access-token path).
func (b *InMemoryBackend) AssociateSoftwareToken(accessToken, session string) (string, string, error) {
	b.mu.Lock("AssociateSoftwareToken")
	defer b.mu.Unlock()

	user, sess, err := b.resolveMFASetupSubjectLocked(accessToken, session)
	if err != nil {
		return "", "", err
	}

	secretBytes := make([]byte, totpSecretLen)
	if _, err = rand.Read(secretBytes); err != nil {
		return "", "", fmt.Errorf("generating TOTP secret: %w", err)
	}

	secret := base32.StdEncoding.WithPadding(base32.NoPadding).EncodeToString(secretBytes)
	user.TOTPSecret = secret
	user.TOTPVerified = false

	return secret, sess, nil
}

// VerifySoftwareToken validates userCode as a real RFC 6238 TOTP code for the secret
// previously issued by AssociateSoftwareToken (HMAC-SHA1, 30s step, +/-1 step clock skew,
// matching an authenticator app such as Google Authenticator/Authy) for the user resolved
// via accessToken or session (exactly one must be supplied). Only the code that the secret
// actually produces at (approximately) the current time is accepted. Returns the session to
// echo back when the caller used the session path -- that session "satisfies an MFA_SETUP
// challenge" and is the input RespondToAuthChallenge needs to complete sign-in
// (api_op_VerifySoftwareToken.go).
func (b *InMemoryBackend) VerifySoftwareToken(accessToken, session, userCode string) (string, error) {
	b.mu.Lock("VerifySoftwareToken")
	defer b.mu.Unlock()

	user, sess, err := b.resolveMFASetupSubjectLocked(accessToken, session)
	if err != nil {
		return "", err
	}

	if user.TOTPSecret == "" {
		return "", fmt.Errorf("%w: no TOTP secret associated; call AssociateSoftwareToken first", ErrNotAuthorized)
	}

	if len(userCode) != totpCodeLen {
		return "", fmt.Errorf("%w: TOTP code must be %d digits", ErrCodeMismatch, totpCodeLen)
	}

	for _, ch := range userCode {
		if ch < '0' || ch > '9' {
			return "", fmt.Errorf("%w: TOTP code must contain only digits", ErrCodeMismatch)
		}
	}

	if !verifyTOTPCode(user.TOTPSecret, userCode, time.Now()) {
		return "", fmt.Errorf("%w: invalid software token code", ErrCodeMismatch)
	}

	user.TOTPVerified = true

	return sess, nil
}

// RespondToMFASetupChallenge completes an MFA_SETUP challenge (InitiateAuth/
// AdminInitiateAuth doc: "use the session returned by VerifySoftwareToken as an input to
// RespondToAuthChallenge or AdminRespondToAuthChallenge with challenge name MFA_SETUP to
// complete sign-in"). The session must have had its software token associated and verified
// via AssociateSoftwareToken/VerifySoftwareToken first. On success it records
// SOFTWARE_TOKEN_MFA as the user's MFA preference (the only factor this backend's MFA_SETUP
// path can establish) and issues tokens.
func (b *InMemoryBackend) RespondToMFASetupChallenge(clientID, session string) (*TokenResult, error) {
	b.mu.Lock("RespondToMFASetupChallenge")
	defer b.mu.Unlock()

	entry, ok := b.mfaSessions[session]
	if !ok {
		return nil, fmt.Errorf("%w: MFA_SETUP session not found or expired", ErrNotAuthorized)
	}

	if !entry.ExpiresAt.IsZero() && time.Now().After(entry.ExpiresAt) {
		delete(b.mfaSessions, session)

		return nil, fmt.Errorf("%w: MFA_SETUP session not found or expired", ErrNotAuthorized)
	}

	if entry.ChallengeType != challengeMFASetup {
		return nil, fmt.Errorf("%w: session is not an MFA_SETUP challenge", ErrNotAuthorized)
	}

	if entry.ClientID != clientID {
		return nil, fmt.Errorf("%w: MFA_SETUP session was issued for a different client", ErrNotAuthorized)
	}

	pool, ok := b.pools.Get(entry.PoolID)
	if !ok {
		return nil, fmt.Errorf("%w: user pool %q not found", ErrUserPoolNotFound, entry.PoolID)
	}

	user, ok := b.users.Get(userKey(entry.PoolID, entry.Username))
	if !ok {
		return nil, fmt.Errorf("%w: user %q not found", ErrUserNotFound, entry.Username)
	}

	if !user.TOTPVerified {
		return nil, fmt.Errorf(
			"%w: no verified software token; call AssociateSoftwareToken and VerifySoftwareToken first",
			ErrNotAuthorized,
		)
	}

	if err := b.applyMFAPreferenceLocked(user, false, true, challengeSoftwareTokenMFA); err != nil {
		return nil, err
	}

	delete(b.mfaSessions, session)

	result, err := b.issueTokensLocked(pool, clientID, user, triggerSourceTokenGenAuthentication)
	if err != nil {
		return nil, err
	}

	return result.Tokens, nil
}

// SetUserMFAPreference sets the preferred MFA method for the authenticated user.
func (b *InMemoryBackend) SetUserMFAPreference(
	accessToken string,
	smsMFAEnabled, softwareTokenEnabled bool,
	preferredMFA string,
) error {
	b.mu.Lock("SetUserMFAPreference")
	defer b.mu.Unlock()

	user, err := b.findUserByAccessTokenLocked(accessToken)
	if err != nil {
		return err
	}

	return b.applyMFAPreferenceLocked(user, smsMFAEnabled, softwareTokenEnabled, preferredMFA)
}

// AdminSetUserMFASetting sets the MFA configuration for a specific user (admin operation).
func (b *InMemoryBackend) AdminSetUserMFASetting(
	userPoolID, username string,
	smsMFAEnabled, softwareTokenEnabled bool,
	preferredMFA string,
) error {
	b.mu.Lock("AdminSetUserMFASetting")
	defer b.mu.Unlock()

	if _, ok := b.pools.Get(userPoolID); !ok {
		return fmt.Errorf("%w: pool %q not found", ErrUserPoolNotFound, userPoolID)
	}

	user, ok := b.users.Get(userKey(userPoolID, username))
	if !ok {
		return fmt.Errorf("%w: user %q not found", ErrUserNotFound, username)
	}

	return b.applyMFAPreferenceLocked(user, smsMFAEnabled, softwareTokenEnabled, preferredMFA)
}

// applyMFAPreferenceLocked updates the MFA setting list and preferred MFA on a user.
// Caller must hold the write lock.
func (b *InMemoryBackend) applyMFAPreferenceLocked(
	user *User,
	smsMFAEnabled, softwareTokenEnabled bool,
	preferredMFA string,
) error {
	var settings []string

	if smsMFAEnabled {
		settings = append(settings, challengeSMSMFA)
	}

	if softwareTokenEnabled {
		settings = append(settings, challengeSoftwareTokenMFA)
	}

	sort.Strings(settings)
	user.UserMFASettingList = settings

	if preferredMFA != "" {
		found := slices.Contains(settings, preferredMFA)
		if !found && len(settings) > 0 {
			// AdminSetUserMFAPreference/SetUserMFAPreference's own deserializers
			// model InvalidParameterException for this, not
			// InvalidUserPoolConfigurationException.
			return fmt.Errorf(
				"%w: preferred MFA %q is not in the enabled MFA list",
				ErrInvalidParameter,
				preferredMFA,
			)
		}
		user.PreferredMfaSetting = preferredMFA
	} else if len(settings) == 0 {
		user.PreferredMfaSetting = ""
	}

	user.UpdatedAt = time.Now()

	return nil
}

// EvictExpiredMFASessions removes mfaSession entries that have expired or whose pool or
// user no longer exists. The janitor calls this periodically to prevent unbounded accumulation.
func (b *InMemoryBackend) EvictExpiredMFASessions() {
	b.mu.Lock("EvictExpiredMFASessions")
	defer b.mu.Unlock()

	now := time.Now()

	for token, entry := range b.mfaSessions {
		if !entry.ExpiresAt.IsZero() && now.After(entry.ExpiresAt) {
			delete(b.mfaSessions, token)

			continue
		}

		if _, poolExists := b.pools.Get(entry.PoolID); !poolExists {
			delete(b.mfaSessions, token)

			continue
		}

		if _, userExists := b.users.Get(userKey(entry.PoolID, entry.Username)); !userExists {
			delete(b.mfaSessions, token)
		}
	}
}

// AdminSetUserMFAPreference sets the MFA preferences for a specific user (admin operation).
// This is the modern preferred API (vs AdminSetUserSettings). It delegates to AdminSetUserMFASetting.
func (b *InMemoryBackend) AdminSetUserMFAPreference(
	userPoolID, username string,
	smsMFAEnabled, softwareTokenEnabled bool,
	preferredMFA string,
) error {
	return b.AdminSetUserMFASetting(userPoolID, username, smsMFAEnabled, softwareTokenEnabled, preferredMFA)
}

// mfaConfigOFF is the default MFA configuration value when none is set.
const mfaConfigOFF = "OFF"

// AdminSetUserSettings persists legacy MFAOptions onto a user (admin operation).
func (b *InMemoryBackend) AdminSetUserSettings(userPoolID, username string, mfaOptions []MFAOptionType) error {
	b.mu.Lock("AdminSetUserSettings")
	defer b.mu.Unlock()

	if _, ok := b.pools.Get(userPoolID); !ok {
		return fmt.Errorf("%w: pool %q not found", ErrUserPoolNotFound, userPoolID)
	}

	user, ok := b.users.Get(userKey(userPoolID, username))
	if !ok {
		return fmt.Errorf("%w: user %q not found", ErrUserNotFound, username)
	}

	user.MFAOptions = mfaOptions

	return nil
}

// SetUserSettings persists legacy MFAOptions onto the authenticated user.
func (b *InMemoryBackend) SetUserSettings(accessToken string, mfaOptions []MFAOptionType) error {
	b.mu.Lock("SetUserSettings")
	defer b.mu.Unlock()

	user, err := b.findUserByAccessTokenLocked(accessToken)
	if err != nil {
		return err
	}

	user.MFAOptions = mfaOptions

	return nil
}
