package cognitoidp_test

import (
	"encoding/base32"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/blackbirdworks/gopherstack/services/cognitoidp"
)

// rfc4226Secret is the 20-byte ASCII secret used by the official RFC 4226 (HOTP) Appendix D
// and RFC 6238 (TOTP) Appendix B test vectors.
const rfc4226Secret = "12345678901234567890"

func rfc4226SecretBase32(t *testing.T) string {
	t.Helper()

	return base32.StdEncoding.WithPadding(base32.NoPadding).EncodeToString([]byte(rfc4226Secret))
}

// Test_GenerateTOTPCode_RFC4226Vectors pins GenerateTOTPCode against the official RFC 4226
// Appendix D HOTP test vectors (truncated to 6 digits), by picking a timestamp that falls in
// the 30-second step whose counter equals the RFC's HOTP counter. This proves the dynamic
// truncation + HMAC-SHA1 math is bit-for-bit correct, independent of any TOTP-specific
// timestamp handling.
func Test_GenerateTOTPCode_RFC4226Vectors(t *testing.T) {
	t.Parallel()

	secret := rfc4226SecretBase32(t)

	// RFC 4226 Appendix D, "Truncated Value" column reduced to its low 6 digits (6-digit
	// HOTP truncation is defined as the same dynamic-truncation binary value mod 10^6, i.e.
	// the low 6 decimal digits of the published 6-digit-truncated values already listed
	// there).
	cases := []struct {
		name    string
		want    string
		counter int64
	}{
		{"counter_0", "755224", 0},
		{"counter_1", "287082", 1},
		{"counter_2", "359152", 2},
		{"counter_3", "969429", 3},
		{"counter_4", "338314", 4},
		{"counter_5", "254676", 5},
		{"counter_6", "287922", 6},
		{"counter_7", "162583", 7},
		{"counter_8", "399871", 8},
		{"counter_9", "520489", 9},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			// Any timestamp within [counter*30, counter*30+30) maps to this HOTP counter
			// under the 30-second TOTP step.
			at := time.Unix(tc.counter*30, 0).UTC()

			got, err := cognitoidp.GenerateTOTPCode(secret, at)
			require.NoError(t, err)
			assert.Equal(t, tc.want, got)
		})
	}
}

// Test_GenerateTOTPCode_RFC6238Vectors pins GenerateTOTPCode against the official RFC 6238
// Appendix B test vectors (published as 8-digit codes for SHA1; truncated here to the 6
// digits AWS Cognito actually uses, which are the same dynamic-truncation value mod 10^6).
func Test_GenerateTOTPCode_RFC6238Vectors(t *testing.T) {
	t.Parallel()

	secret := rfc4226SecretBase32(t)

	cases := []struct {
		name       string
		want8Digit string
		unixTime   int64
	}{
		{"T=59", "94287082", 59},
		{"T=1111111109", "07081804", 1111111109},
		{"T=1111111111", "14050471", 1111111111},
		{"T=1234567890", "89005924", 1234567890},
		{"T=2000000000", "69279037", 2000000000},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			want6Digit := tc.want8Digit[len(tc.want8Digit)-6:]

			got, err := cognitoidp.GenerateTOTPCode(secret, time.Unix(tc.unixTime, 0).UTC())
			require.NoError(t, err)
			assert.Equal(t, want6Digit, got)
		})
	}
}

// Test_VerifySoftwareToken_RealTOTP proves the fix end to end: the exact code an
// authenticator app would compute from the AssociateSoftwareToken secret is accepted, a
// fixed/guessed code is rejected with CodeMismatchException, and the challenge cannot be
// bypassed with an arbitrary 6-digit string.
func Test_VerifySoftwareToken_RealTOTP(t *testing.T) {
	t.Parallel()

	cases := []struct {
		wantErr   error
		buildCode func(t *testing.T, secret string) string
		name      string
	}{
		{
			name: "real code from secret is accepted",
			buildCode: func(t *testing.T, secret string) string {
				t.Helper()

				code, err := cognitoidp.GenerateTOTPCode(secret, time.Now())
				require.NoError(t, err)

				return code
			},
			wantErr: nil,
		},
		{
			name: "wrong code is rejected",
			buildCode: func(t *testing.T, secret string) string {
				t.Helper()

				realCode, err := cognitoidp.GenerateTOTPCode(secret, time.Now())
				require.NoError(t, err)

				return wrongSixDigitCode(realCode)
			},
			wantErr: cognitoidp.ErrCodeMismatch,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			b, _, client := setupTestPoolAndClient(t)
			tokens := signUpConfirmAndLogin(t, b, client.ClientID, "totp-"+sanitizeTestName(tc.name))

			secret, _, err := b.AssociateSoftwareToken(tokens.AccessToken, "")
			require.NoError(t, err)

			code := tc.buildCode(t, secret)

			_, err = b.VerifySoftwareToken(tokens.AccessToken, "", code)
			if tc.wantErr == nil {
				require.NoError(t, err)
			} else {
				require.Error(t, err)
				assert.ErrorIs(t, err, tc.wantErr)
			}
		})
	}
}

// Test_RespondToMFAChallenge_SMSCode proves SMS_MFA/EMAIL_OTP challenges now require the
// exact one-time code generated by the backend (not "any 6 digits"), while retaining the
// session across a wrong attempt so the caller can retry until it expires.
func Test_RespondToMFAChallenge_SMSCode(t *testing.T) {
	t.Parallel()

	cases := []struct {
		name    string
		useReal bool
	}{
		{"correct code issues tokens", true},
		{"wrong code is rejected", false},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			b, pool, client := setupTestPoolAndClient(t)
			username := "sms-" + sanitizeTestName(tc.name)
			tokens := signUpConfirmAndLogin(t, b, client.ClientID, username)

			require.NoError(t, b.SetUserMFAPreference(tokens.AccessToken, true, false, "SMS_MFA"))
			require.NoError(t, b.UpdateUserPoolWithOpts(pool.ID, "ON", cognitoidp.UserPoolOptions{}))

			result, err := b.InitiateAuth(client.ClientID, "USER_PASSWORD_AUTH", username, "Pass1234!")
			require.NoError(t, err)
			require.Equal(t, "SMS_MFA", result.ChallengeName)
			require.NotEmpty(t, result.MFASession)

			realCode := b.GetMFASessionCodeForTest(result.MFASession)
			require.Len(t, realCode, 6)

			if tc.useReal {
				gotTokens, respondErr := b.RespondToMFAChallenge(client.ClientID, result.MFASession, realCode)
				require.NoError(t, respondErr)
				assert.NotEmpty(t, gotTokens.AccessToken)

				return
			}

			_, mismatchErr := b.RespondToMFAChallenge(client.ClientID, result.MFASession, wrongSixDigitCode(realCode))
			require.ErrorIs(t, mismatchErr, cognitoidp.ErrCodeMismatch)

			// The session must survive a wrong attempt so the real code can still be used.
			gotTokens, retryErr := b.RespondToMFAChallenge(client.ClientID, result.MFASession, realCode)
			require.NoError(t, retryErr)
			assert.NotEmpty(t, gotTokens.AccessToken)
		})
	}
}

// wrongSixDigitCode returns a 6-digit numeric string guaranteed to differ from realCode.
func wrongSixDigitCode(realCode string) string {
	if realCode != "000000" {
		return "000000"
	}

	return "111111"
}

// sanitizeTestName lowercases and strips spaces so a subtest name can double as a unique
// Cognito username.
func sanitizeTestName(name string) string {
	out := make([]rune, 0, len(name))

	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z':
			out = append(out, r)
		case r >= 'A' && r <= 'Z':
			out = append(out, r+('a'-'A'))
		case r >= '0' && r <= '9':
			out = append(out, r)
		}
	}

	return string(out)
}
