package iot_test

import (
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/labstack/echo/v5"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/blackbirdworks/gopherstack/services/iot"
)

// sdkRouteCases is the authoritative method+path for every real IoT
// control-plane operation, extracted from iot@v1.77.4 serializers.go: each
// entry's "request.Method" and the string passed to httpbinding.SplitURI in
// that op's awsRestjson1_serializeOp<Op>.HandleSerialize. PLACEHOLDER stands
// in for any {Param} URI label (including the three "{label+}" greedy
// labels -- ConfirmTopicRuleDestination, DeleteTopicRuleDestination,
// GetTopicRuleDestination -- gopherstack's own router matches these by
// simple prefix/suffix, not AWS's URI-template greedy-segment semantics, so
// a single PLACEHOLDER segment exercises the same code path a real
// multi-segment ARN would). No two ops in this table share the same
// (method, path-with-params-stripped) pair, so unlike s3/lambda no entry
// needed a required dynamic query/header member to disambiguate it from a
// sibling.
//
// Regenerate by grepping serializers.go for every
// "func (m *awsRestjson1_serializeOp<Op>) HandleSerialize" and pulling
// "request.Method" and the httpbinding.SplitURI(...) argument from its body.
func sdkRouteCases() []struct{ op, method, path string } {
	return []struct{ op, method, path string }{
		{"AcceptCertificateTransfer", "PATCH", "/accept-certificate-transfer/PLACEHOLDER"},
		{"AddThingToBillingGroup", "PUT", "/billing-groups/addThingToBillingGroup"},
		{"AddThingToThingGroup", "PUT", "/thing-groups/addThingToThingGroup"},
		{"AssociateSbomWithPackageVersion", "PUT", "/packages/PLACEHOLDER/versions/PLACEHOLDER/sbom"},
		{"AssociateTargetsWithJob", "POST", "/jobs/PLACEHOLDER/targets"},
		{"AttachPolicy", "PUT", "/target-policies/PLACEHOLDER"},
		{"AttachPrincipalPolicy", "PUT", "/principal-policies/PLACEHOLDER"},
		{"AttachSecurityProfile", "PUT", "/security-profiles/PLACEHOLDER/targets"},
		{"AttachThingPrincipal", "PUT", "/things/PLACEHOLDER/principals"},
		{"CancelAuditMitigationActionsTask", "PUT", "/audit/mitigationactions/tasks/PLACEHOLDER/cancel"},
		{"CancelAuditTask", "PUT", "/audit/tasks/PLACEHOLDER/cancel"},
		{"CancelCertificateTransfer", "PATCH", "/cancel-certificate-transfer/PLACEHOLDER"},
		{"CancelDetectMitigationActionsTask", "PUT", "/detect/mitigationactions/tasks/PLACEHOLDER/cancel"},
		{"CancelJob", "PUT", "/jobs/PLACEHOLDER/cancel"},
		{"CancelJobExecution", "PUT", "/things/PLACEHOLDER/jobs/PLACEHOLDER/cancel"},
		{"ClearDefaultAuthorizer", "DELETE", "/default-authorizer"},
		{"ConfirmTopicRuleDestination", "GET", "/confirmdestination/PLACEHOLDER"},
		{"CreateAuditSuppression", "POST", "/audit/suppressions/create"},
		{"CreateAuthorizer", "POST", "/authorizer/PLACEHOLDER"},
		{"CreateBillingGroup", "POST", "/billing-groups/PLACEHOLDER"},
		{"CreateCertificateFromCsr", "POST", "/certificates"},
		{"CreateCertificateProvider", "POST", "/certificate-providers/PLACEHOLDER"},
		{"CreateCommand", "PUT", "/commands/PLACEHOLDER"},
		{"CreateCustomMetric", "POST", "/custom-metric/PLACEHOLDER"},
		{"CreateDimension", "POST", "/dimensions/PLACEHOLDER"},
		{"CreateDomainConfiguration", "POST", "/domainConfigurations/PLACEHOLDER"},
		{"CreateDynamicThingGroup", "POST", "/dynamic-thing-groups/PLACEHOLDER"},
		{"CreateFleetMetric", "PUT", "/fleet-metric/PLACEHOLDER"},
		{"CreateJob", "PUT", "/jobs/PLACEHOLDER"},
		{"CreateJobTemplate", "PUT", "/job-templates/PLACEHOLDER"},
		{"CreateKeysAndCertificate", "POST", "/keys-and-certificate"},
		{"CreateMitigationAction", "POST", "/mitigationactions/actions/PLACEHOLDER"},
		{"CreateOTAUpdate", "POST", "/otaUpdates/PLACEHOLDER"},
		{"CreatePackage", "PUT", "/packages/PLACEHOLDER"},
		{"CreatePackageVersion", "PUT", "/packages/PLACEHOLDER/versions/PLACEHOLDER"},
		{"CreatePolicy", "POST", "/policies/PLACEHOLDER"},
		{"CreatePolicyVersion", "POST", "/policies/PLACEHOLDER/version"},
		{"CreateProvisioningClaim", "POST", "/provisioning-templates/PLACEHOLDER/provisioning-claim"},
		{"CreateProvisioningTemplate", "POST", "/provisioning-templates"},
		{"CreateProvisioningTemplateVersion", "POST", "/provisioning-templates/PLACEHOLDER/versions"},
		{"CreateRoleAlias", "POST", "/role-aliases/PLACEHOLDER"},
		{"CreateScheduledAudit", "POST", "/audit/scheduledaudits/PLACEHOLDER"},
		{"CreateSecurityProfile", "POST", "/security-profiles/PLACEHOLDER"},
		{"CreateStream", "POST", "/streams/PLACEHOLDER"},
		{"CreateThing", "POST", "/things/PLACEHOLDER"},
		{"CreateThingGroup", "POST", "/thing-groups/PLACEHOLDER"},
		{"CreateThingType", "POST", "/thing-types/PLACEHOLDER"},
		{"CreateTopicRule", "POST", "/rules/PLACEHOLDER"},
		{"CreateTopicRuleDestination", "POST", "/destinations"},
		{"DeleteAccountAuditConfiguration", "DELETE", "/audit/configuration"},
		{"DeleteAuditSuppression", "POST", "/audit/suppressions/delete"},
		{"DeleteAuthorizer", "DELETE", "/authorizer/PLACEHOLDER"},
		{"DeleteBillingGroup", "DELETE", "/billing-groups/PLACEHOLDER"},
		{"DeleteCACertificate", "DELETE", "/cacertificate/PLACEHOLDER"},
		{"DeleteCertificate", "DELETE", "/certificates/PLACEHOLDER"},
		{"DeleteCertificateProvider", "DELETE", "/certificate-providers/PLACEHOLDER"},
		{"DeleteCommand", "DELETE", "/commands/PLACEHOLDER"},
		{"DeleteCommandExecution", "DELETE", "/command-executions/PLACEHOLDER"},
		{"DeleteCustomMetric", "DELETE", "/custom-metric/PLACEHOLDER"},
		{"DeleteDimension", "DELETE", "/dimensions/PLACEHOLDER"},
		{"DeleteDomainConfiguration", "DELETE", "/domainConfigurations/PLACEHOLDER"},
		{"DeleteDynamicThingGroup", "DELETE", "/dynamic-thing-groups/PLACEHOLDER"},
		{"DeleteFleetMetric", "DELETE", "/fleet-metric/PLACEHOLDER"},
		{"DeleteJob", "DELETE", "/jobs/PLACEHOLDER"},
		{"DeleteJobExecution", "DELETE", "/things/PLACEHOLDER/jobs/PLACEHOLDER/executionNumber/PLACEHOLDER"},
		{"DeleteJobTemplate", "DELETE", "/job-templates/PLACEHOLDER"},
		{"DeleteMitigationAction", "DELETE", "/mitigationactions/actions/PLACEHOLDER"},
		{"DeleteOTAUpdate", "DELETE", "/otaUpdates/PLACEHOLDER"},
		{"DeletePackage", "DELETE", "/packages/PLACEHOLDER"},
		{"DeletePackageVersion", "DELETE", "/packages/PLACEHOLDER/versions/PLACEHOLDER"},
		{"DeletePolicy", "DELETE", "/policies/PLACEHOLDER"},
		{"DeletePolicyVersion", "DELETE", "/policies/PLACEHOLDER/version/PLACEHOLDER"},
		{"DeleteProvisioningTemplate", "DELETE", "/provisioning-templates/PLACEHOLDER"},
		{"DeleteProvisioningTemplateVersion", "DELETE", "/provisioning-templates/PLACEHOLDER/versions/PLACEHOLDER"},
		{"DeleteRegistrationCode", "DELETE", "/registrationcode"},
		{"DeleteRoleAlias", "DELETE", "/role-aliases/PLACEHOLDER"},
		{"DeleteScheduledAudit", "DELETE", "/audit/scheduledaudits/PLACEHOLDER"},
		{"DeleteSecurityProfile", "DELETE", "/security-profiles/PLACEHOLDER"},
		{"DeleteStream", "DELETE", "/streams/PLACEHOLDER"},
		{"DeleteThing", "DELETE", "/things/PLACEHOLDER"},
		{"DeleteThingGroup", "DELETE", "/thing-groups/PLACEHOLDER"},
		{"DeleteThingType", "DELETE", "/thing-types/PLACEHOLDER"},
		{"DeleteTopicRule", "DELETE", "/rules/PLACEHOLDER"},
		{"DeleteTopicRuleDestination", "DELETE", "/destinations/PLACEHOLDER"},
		{"DeleteV2LoggingLevel", "DELETE", "/v2LoggingLevel"},
		{"DeprecateThingType", "POST", "/thing-types/PLACEHOLDER/deprecate"},
		{"DescribeAccountAuditConfiguration", "GET", "/audit/configuration"},
		{"DescribeAuditFinding", "GET", "/audit/findings/PLACEHOLDER"},
		{"DescribeAuditMitigationActionsTask", "GET", "/audit/mitigationactions/tasks/PLACEHOLDER"},
		{"DescribeAuditSuppression", "POST", "/audit/suppressions/describe"},
		{"DescribeAuditTask", "GET", "/audit/tasks/PLACEHOLDER"},
		{"DescribeAuthorizer", "GET", "/authorizer/PLACEHOLDER"},
		{"DescribeBillingGroup", "GET", "/billing-groups/PLACEHOLDER"},
		{"DescribeCACertificate", "GET", "/cacertificate/PLACEHOLDER"},
		{"DescribeCertificate", "GET", "/certificates/PLACEHOLDER"},
		{"DescribeCertificateProvider", "GET", "/certificate-providers/PLACEHOLDER"},
		{"DescribeCustomMetric", "GET", "/custom-metric/PLACEHOLDER"},
		{"DescribeDefaultAuthorizer", "GET", "/default-authorizer"},
		{"DescribeDetectMitigationActionsTask", "GET", "/detect/mitigationactions/tasks/PLACEHOLDER"},
		{"DescribeDimension", "GET", "/dimensions/PLACEHOLDER"},
		{"DescribeDomainConfiguration", "GET", "/domainConfigurations/PLACEHOLDER"},
		{"DescribeEncryptionConfiguration", "GET", "/encryption-configuration"},
		{"DescribeEndpoint", "GET", "/endpoint"},
		{"DescribeEventConfigurations", "GET", "/event-configurations"},
		{"DescribeFleetMetric", "GET", "/fleet-metric/PLACEHOLDER"},
		{"DescribeIndex", "GET", "/indices/PLACEHOLDER"},
		{"DescribeJob", "GET", "/jobs/PLACEHOLDER"},
		{"DescribeJobExecution", "GET", "/things/PLACEHOLDER/jobs/PLACEHOLDER"},
		{"DescribeJobTemplate", "GET", "/job-templates/PLACEHOLDER"},
		{"DescribeManagedJobTemplate", "GET", "/managed-job-templates/PLACEHOLDER"},
		{"DescribeMitigationAction", "GET", "/mitigationactions/actions/PLACEHOLDER"},
		{"DescribeProvisioningTemplate", "GET", "/provisioning-templates/PLACEHOLDER"},
		{"DescribeProvisioningTemplateVersion", "GET", "/provisioning-templates/PLACEHOLDER/versions/PLACEHOLDER"},
		{"DescribeRoleAlias", "GET", "/role-aliases/PLACEHOLDER"},
		{"DescribeScheduledAudit", "GET", "/audit/scheduledaudits/PLACEHOLDER"},
		{"DescribeSecurityProfile", "GET", "/security-profiles/PLACEHOLDER"},
		{"DescribeStream", "GET", "/streams/PLACEHOLDER"},
		{"DescribeThing", "GET", "/things/PLACEHOLDER"},
		{"DescribeThingGroup", "GET", "/thing-groups/PLACEHOLDER"},
		{"DescribeThingRegistrationTask", "GET", "/thing-registration-tasks/PLACEHOLDER"},
		{"DescribeThingType", "GET", "/thing-types/PLACEHOLDER"},
		{"DetachPolicy", "POST", "/target-policies/PLACEHOLDER"},
		{"DetachPrincipalPolicy", "DELETE", "/principal-policies/PLACEHOLDER"},
		{"DetachSecurityProfile", "DELETE", "/security-profiles/PLACEHOLDER/targets"},
		{"DetachThingPrincipal", "DELETE", "/things/PLACEHOLDER/principals"},
		{"DisableTopicRule", "POST", "/rules/PLACEHOLDER/disable"},
		{"DisassociateSbomFromPackageVersion", "DELETE", "/packages/PLACEHOLDER/versions/PLACEHOLDER/sbom"},
		{"EnableTopicRule", "POST", "/rules/PLACEHOLDER/enable"},
		{"GetBehaviorModelTrainingSummaries", "GET", "/behavior-model-training/summaries"},
		{"GetBucketsAggregation", "POST", "/indices/buckets"},
		{"GetCardinality", "POST", "/indices/cardinality"},
		{"GetCommand", "GET", "/commands/PLACEHOLDER"},
		{"GetCommandExecution", "GET", "/command-executions/PLACEHOLDER"},
		{"GetEffectivePolicies", "POST", "/effective-policies"},
		{"GetIndexingConfiguration", "GET", "/indexing/config"},
		{"GetJobDocument", "GET", "/jobs/PLACEHOLDER/job-document"},
		{"GetLoggingOptions", "GET", "/loggingOptions"},
		{"GetOTAUpdate", "GET", "/otaUpdates/PLACEHOLDER"},
		{"GetPackage", "GET", "/packages/PLACEHOLDER"},
		{"GetPackageConfiguration", "GET", "/package-configuration"},
		{"GetPackageVersion", "GET", "/packages/PLACEHOLDER/versions/PLACEHOLDER"},
		{"GetPercentiles", "POST", "/indices/percentiles"},
		{"GetPolicy", "GET", "/policies/PLACEHOLDER"},
		{"GetPolicyVersion", "GET", "/policies/PLACEHOLDER/version/PLACEHOLDER"},
		{"GetRegistrationCode", "GET", "/registrationcode"},
		{"GetStatistics", "POST", "/indices/statistics"},
		{"GetThingConnectivityData", "POST", "/things/PLACEHOLDER/connectivity-data"},
		{"GetTopicRule", "GET", "/rules/PLACEHOLDER"},
		{"GetTopicRuleDestination", "GET", "/destinations/PLACEHOLDER"},
		{"GetV2LoggingOptions", "GET", "/v2LoggingOptions"},
		{"ListActiveViolations", "GET", "/active-violations"},
		{"ListAttachedPolicies", "POST", "/attached-policies/PLACEHOLDER"},
		{"ListAuditFindings", "POST", "/audit/findings"},
		{"ListAuditMitigationActionsExecutions", "GET", "/audit/mitigationactions/executions"},
		{"ListAuditMitigationActionsTasks", "GET", "/audit/mitigationactions/tasks"},
		{"ListAuditSuppressions", "POST", "/audit/suppressions/list"},
		{"ListAuditTasks", "GET", "/audit/tasks"},
		{"ListAuthorizers", "GET", "/authorizers"},
		{"ListBillingGroups", "GET", "/billing-groups"},
		{"ListCACertificates", "GET", "/cacertificates"},
		{"ListCertificateProviders", "GET", "/certificate-providers"},
		{"ListCertificates", "GET", "/certificates"},
		{"ListCertificatesByCA", "GET", "/certificates-by-ca/PLACEHOLDER"},
		{"ListCommandExecutions", "POST", "/command-executions"},
		{"ListCommands", "GET", "/commands"},
		{"ListCustomMetrics", "GET", "/custom-metrics"},
		{"ListDetectMitigationActionsExecutions", "GET", "/detect/mitigationactions/executions"},
		{"ListDetectMitigationActionsTasks", "GET", "/detect/mitigationactions/tasks"},
		{"ListDimensions", "GET", "/dimensions"},
		{"ListDomainConfigurations", "GET", "/domainConfigurations"},
		{"ListFleetMetrics", "GET", "/fleet-metrics"},
		{"ListIndices", "GET", "/indices"},
		{"ListJobExecutionsForJob", "GET", "/jobs/PLACEHOLDER/things"},
		{"ListJobExecutionsForThing", "GET", "/things/PLACEHOLDER/jobs"},
		{"ListJobTemplates", "GET", "/job-templates"},
		{"ListJobs", "GET", "/jobs"},
		{"ListManagedJobTemplates", "GET", "/managed-job-templates"},
		{"ListMetricValues", "GET", "/metric-values"},
		{"ListMitigationActions", "GET", "/mitigationactions/actions"},
		{"ListOTAUpdates", "GET", "/otaUpdates"},
		{"ListOutgoingCertificates", "GET", "/certificates-out-going"},
		{"ListPackageVersions", "GET", "/packages/PLACEHOLDER/versions"},
		{"ListPackages", "GET", "/packages"},
		{"ListPolicies", "GET", "/policies"},
		{"ListPolicyPrincipals", "GET", "/policy-principals"},
		{"ListPolicyVersions", "GET", "/policies/PLACEHOLDER/version"},
		{"ListPrincipalPolicies", "GET", "/principal-policies"},
		{"ListPrincipalThings", "GET", "/principals/things"},
		{"ListPrincipalThingsV2", "GET", "/principals/things-v2"},
		{"ListProvisioningTemplateVersions", "GET", "/provisioning-templates/PLACEHOLDER/versions"},
		{"ListProvisioningTemplates", "GET", "/provisioning-templates"},
		{"ListRelatedResourcesForAuditFinding", "GET", "/audit/relatedResources"},
		{"ListRoleAliases", "GET", "/role-aliases"},
		{"ListSbomValidationResults", "GET", "/packages/PLACEHOLDER/versions/PLACEHOLDER/sbom-validation-results"},
		{"ListScheduledAudits", "GET", "/audit/scheduledaudits"},
		{"ListSecurityProfiles", "GET", "/security-profiles"},
		{"ListSecurityProfilesForTarget", "GET", "/security-profiles-for-target"},
		{"ListStreams", "GET", "/streams"},
		{"ListTagsForResource", "GET", "/tags"},
		{"ListTargetsForPolicy", "POST", "/policy-targets/PLACEHOLDER"},
		{"ListTargetsForSecurityProfile", "GET", "/security-profiles/PLACEHOLDER/targets"},
		{"ListThingGroups", "GET", "/thing-groups"},
		{"ListThingGroupsForThing", "GET", "/things/PLACEHOLDER/thing-groups"},
		{"ListThingPrincipals", "GET", "/things/PLACEHOLDER/principals"},
		{"ListThingPrincipalsV2", "GET", "/things/PLACEHOLDER/principals-v2"},
		{"ListThingRegistrationTaskReports", "GET", "/thing-registration-tasks/PLACEHOLDER/reports"},
		{"ListThingRegistrationTasks", "GET", "/thing-registration-tasks"},
		{"ListThingTypes", "GET", "/thing-types"},
		{"ListThings", "GET", "/things"},
		{"ListThingsInBillingGroup", "GET", "/billing-groups/PLACEHOLDER/things"},
		{"ListThingsInThingGroup", "GET", "/thing-groups/PLACEHOLDER/things"},
		{"ListTopicRuleDestinations", "GET", "/destinations"},
		{"ListTopicRules", "GET", "/rules"},
		{"ListV2LoggingLevels", "GET", "/v2LoggingLevel"},
		{"ListViolationEvents", "GET", "/violation-events"},
		{"PutVerificationStateOnViolation", "POST", "/violations/verification-state/PLACEHOLDER"},
		{"RegisterCACertificate", "POST", "/cacertificate"},
		{"RegisterCertificate", "POST", "/certificate/register"},
		{"RegisterCertificateWithoutCA", "POST", "/certificate/register-no-ca"},
		{"RegisterThing", "POST", "/things"},
		{"RejectCertificateTransfer", "PATCH", "/reject-certificate-transfer/PLACEHOLDER"},
		{"RemoveThingFromBillingGroup", "PUT", "/billing-groups/removeThingFromBillingGroup"},
		{"RemoveThingFromThingGroup", "PUT", "/thing-groups/removeThingFromThingGroup"},
		{"ReplaceTopicRule", "PATCH", "/rules/PLACEHOLDER"},
		{"SearchIndex", "POST", "/indices/search"},
		{"SetDefaultAuthorizer", "POST", "/default-authorizer"},
		{"SetDefaultPolicyVersion", "PATCH", "/policies/PLACEHOLDER/version/PLACEHOLDER"},
		{"SetLoggingOptions", "POST", "/loggingOptions"},
		{"SetV2LoggingLevel", "POST", "/v2LoggingLevel"},
		{"SetV2LoggingOptions", "POST", "/v2LoggingOptions"},
		{"StartAuditMitigationActionsTask", "POST", "/audit/mitigationactions/tasks/PLACEHOLDER"},
		{"StartDetectMitigationActionsTask", "PUT", "/detect/mitigationactions/tasks/PLACEHOLDER"},
		{"StartOnDemandAuditTask", "POST", "/audit/tasks"},
		{"StartThingRegistrationTask", "POST", "/thing-registration-tasks"},
		{"StopThingRegistrationTask", "PUT", "/thing-registration-tasks/PLACEHOLDER/cancel"},
		{"TagResource", "POST", "/tags"},
		{"TestAuthorization", "POST", "/test-authorization"},
		{"TestInvokeAuthorizer", "POST", "/authorizer/PLACEHOLDER/test"},
		{"TransferCertificate", "PATCH", "/transfer-certificate/PLACEHOLDER"},
		{"UntagResource", "POST", "/untag"},
		{"UpdateAccountAuditConfiguration", "PATCH", "/audit/configuration"},
		{"UpdateAuditSuppression", "PATCH", "/audit/suppressions/update"},
		{"UpdateAuthorizer", "PUT", "/authorizer/PLACEHOLDER"},
		{"UpdateBillingGroup", "PATCH", "/billing-groups/PLACEHOLDER"},
		{"UpdateCACertificate", "PUT", "/cacertificate/PLACEHOLDER"},
		{"UpdateCertificate", "PUT", "/certificates/PLACEHOLDER"},
		{"UpdateCertificateProvider", "PUT", "/certificate-providers/PLACEHOLDER"},
		{"UpdateCommand", "PATCH", "/commands/PLACEHOLDER"},
		{"UpdateCustomMetric", "PATCH", "/custom-metric/PLACEHOLDER"},
		{"UpdateDimension", "PATCH", "/dimensions/PLACEHOLDER"},
		{"UpdateDomainConfiguration", "PUT", "/domainConfigurations/PLACEHOLDER"},
		{"UpdateDynamicThingGroup", "PATCH", "/dynamic-thing-groups/PLACEHOLDER"},
		{"UpdateEncryptionConfiguration", "PATCH", "/encryption-configuration"},
		{"UpdateEventConfigurations", "PATCH", "/event-configurations"},
		{"UpdateFleetMetric", "PATCH", "/fleet-metric/PLACEHOLDER"},
		{"UpdateIndexingConfiguration", "POST", "/indexing/config"},
		{"UpdateJob", "PATCH", "/jobs/PLACEHOLDER"},
		{"UpdateMitigationAction", "PATCH", "/mitigationactions/actions/PLACEHOLDER"},
		{"UpdatePackage", "PATCH", "/packages/PLACEHOLDER"},
		{"UpdatePackageConfiguration", "PATCH", "/package-configuration"},
		{"UpdatePackageVersion", "PATCH", "/packages/PLACEHOLDER/versions/PLACEHOLDER"},
		{"UpdateProvisioningTemplate", "PATCH", "/provisioning-templates/PLACEHOLDER"},
		{"UpdateRoleAlias", "PUT", "/role-aliases/PLACEHOLDER"},
		{"UpdateScheduledAudit", "PATCH", "/audit/scheduledaudits/PLACEHOLDER"},
		{"UpdateSecurityProfile", "PATCH", "/security-profiles/PLACEHOLDER"},
		{"UpdateStream", "PUT", "/streams/PLACEHOLDER"},
		{"UpdateThing", "PATCH", "/things/PLACEHOLDER"},
		{"UpdateThingGroup", "PATCH", "/thing-groups/PLACEHOLDER"},
		{"UpdateThingGroupsForThing", "PUT", "/thing-groups/updateThingGroupsForThing"},
		{"UpdateThingType", "PATCH", "/thing-types/PLACEHOLDER"},
		{"UpdateTopicRuleDestination", "PATCH", "/destinations"},
		{"ValidateSecurityProfileBehaviors", "POST", "/security-profile-behaviors/validate"},
	}
}

// TestExtractOperation_SDKRouteTable drives every real IoT op's
// authoritative method+path (see sdkRouteCases) through ExtractOperation and
// asserts the route table resolves it to the right op, then drives the same
// request through the real Handler() and asserts it did not fall through to
// the "unknown operation: " error that handler.go's dispatch default case
// emits (handler.go:186-189) -- guarding against an op name that resolves
// correctly but has no matching case anywhere in the dispatch tree
// (gopherstack-ey26 class), not just an ExtractOperation mismatch.
func TestExtractOperation_SDKRouteTable(t *testing.T) {
	t.Parallel()

	h := iot.NewHandler(iot.NewInMemoryBackend(), nil)

	for _, tc := range sdkRouteCases() {
		t.Run(strings.ToLower(tc.op), func(t *testing.T) {
			t.Parallel()

			e := echo.New()
			req := httptest.NewRequest(tc.method, tc.path, nil)
			rec := httptest.NewRecorder()
			c := e.NewContext(req, rec)

			got := h.ExtractOperation(c)
			require.Equal(t, tc.op, got, "method=%s path=%s", tc.method, tc.path)

			require.NoError(t, h.Handler()(c))
			assert.NotContains(t, rec.Body.String(), "unknown operation: ",
				"method=%s path=%s op=%s: dispatched to the unmatched-route handler", tc.method, tc.path, tc.op)
		})
	}
}
