package elasticache_test

import (
	"context"
	"testing"

	"github.com/aws/aws-sdk-go-v2/aws"
	elasticachesdk "github.com/aws/aws-sdk-go-v2/service/elasticache"
	elasticachetypes "github.com/aws/aws-sdk-go-v2/service/elasticache/types"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/blackbirdworks/gopherstack/services/elasticache"
)

// ----------------------------------------
// CreateReplicationGroupFull — backend unit tests
// ----------------------------------------

func TestBackend_CreateReplicationGroupFull_ClusterMode(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1")

	rg, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:                   "cluster-rg",
		Description:          "cluster mode enabled",
		ClusterModeEnabled:   true,
		NumNodeGroups:        3,
		ReplicasPerNodeGroup: 1,
	})

	require.NoError(t, err)
	assert.True(t, rg.ClusterModeEnabled)
	assert.Len(t, rg.NodeGroups, 3)
	assert.Equal(t, int32(1), rg.ReplicaCount)
}

func TestBackend_CreateReplicationGroupFull_AuthToken(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1")

	rg, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:               "auth-rg",
		Description:      "with auth token",
		AuthTokenEnabled: true,
		AuthToken:        "my-secret-token",
	})

	require.NoError(t, err)
	assert.True(t, rg.AuthTokenEnabled)
	assert.NotNil(t, rg.AuthTokenLastModifiedDate)
}

func TestBackend_CreateReplicationGroupFull_AuthToken_AutoGenerated(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1")

	rg, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:               "auth-auto-rg",
		Description:      "auto generated token",
		AuthTokenEnabled: true,
	})

	require.NoError(t, err)
	assert.True(t, rg.AuthTokenEnabled)
	assert.NotEmpty(t, rg.AuthToken)
	assert.NotNil(t, rg.AuthTokenLastModifiedDate)
}

func TestBackend_CreateReplicationGroupFull_KmsKey(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1")

	kmsKey := "arn:aws:kms:us-east-1:123456789012:key/12345678-1234-1234-1234-123456789012"
	rg, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:                      "kms-rg",
		Description:             "with kms key",
		KmsKeyID:                kmsKey,
		AtRestEncryptionEnabled: true,
	})

	require.NoError(t, err)
	assert.Equal(t, kmsKey, rg.KmsKeyID)
	assert.True(t, rg.AtRestEncryptionEnabled)
}

func TestBackend_CreateReplicationGroupFull_TransitEncryption(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1")

	rg, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:                       "transit-rg",
		Description:              "transit encryption",
		TransitEncryptionEnabled: true,
		TransitEncryptionMode:    "preferred",
	})

	require.NoError(t, err)
	assert.True(t, rg.TransitEncryptionEnabled)
	assert.Equal(t, "preferred", rg.TransitEncryptionMode)
}

func TestBackend_CreateReplicationGroupFull_TransitEncryptionRequired_WithoutToken_Fails(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1")

	_, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:                       "transit-required-rg",
		Description:              "transit required without token",
		TransitEncryptionEnabled: true,
		TransitEncryptionMode:    "required",
		AuthTokenEnabled:         false,
	})

	require.Error(t, err)
	assert.ErrorIs(t, err, elasticache.ErrAuthTokenRequiredForMode)
}

func TestBackend_CreateReplicationGroupFull_LogDelivery(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1")

	ldConfigs := []elasticache.LogDeliveryConfig{
		{
			LogType:            "slow-log",
			DestinationType:    "cloudwatch-logs",
			DestinationDetails: "/aws/elasticache/slow-log",
			LogFormat:          "json",
			Status:             "active",
		},
	}

	rg, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:                        "log-rg",
		Description:               "with log delivery",
		LogDeliveryConfigurations: ldConfigs,
		NotificationTopicArn:      "arn:aws:sns:us-east-1:123456789012:MyTopic",
	})

	require.NoError(t, err)
	assert.Len(t, rg.LogDeliveryConfigurations, 1)
	assert.Equal(t, "slow-log", rg.LogDeliveryConfigurations[0].LogType)
	assert.Equal(t, "arn:aws:sns:us-east-1:123456789012:MyTopic", rg.NotificationTopicArn)
}

func TestBackend_CreateReplicationGroupFull_DataTiering_Valid(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1")

	rg, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:                 "data-tier-rg",
		Description:        "data tiering",
		DataTieringEnabled: true,
		CacheNodeType:      "cache.r7g.large",
		EngineVersion:      "7.1.0",
	})

	require.NoError(t, err)
	assert.True(t, rg.DataTieringEnabled)
}

func TestBackend_CreateReplicationGroupFull_DataTiering_InvalidNodeType(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1")

	_, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:                 "data-tier-bad-rg",
		Description:        "bad data tiering",
		DataTieringEnabled: true,
		CacheNodeType:      "cache.t3.micro",
	})

	require.Error(t, err)
	assert.ErrorIs(t, err, elasticache.ErrDataTieringInvalid)
}

func TestBackend_CreateReplicationGroupFull_SnapshotRetentionLimit(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1")

	rg, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:                     "snap-ret-rg",
		Description:            "snapshot retention",
		SnapshotRetentionLimit: 7,
		SnapshotWindow:         "03:00-04:00",
	})

	require.NoError(t, err)
	assert.Equal(t, 7, rg.SnapshotRetentionLimit)
	assert.Equal(t, "03:00-04:00", rg.SnapshotWindow)
}

func TestBackend_CreateReplicationGroupFull_Valkey(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1")

	rg, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:            "valkey-rg",
		Description:   "valkey engine",
		Engine:        "valkey",
		EngineVersion: "8.2.0",
	})

	require.NoError(t, err)
	assert.Equal(t, "valkey", rg.Engine)
	assert.Equal(t, "8.2.0", rg.EngineVersion)
}

func TestBackend_CreateReplicationGroupFull_AlreadyExists(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1")

	opts := elasticache.ReplicationGroupCreateOpts{
		ID:          "dup-rg",
		Description: "first",
	}

	_, err := b.CreateReplicationGroupFull(context.Background(), opts)
	require.NoError(t, err)

	_, err = b.CreateReplicationGroupFull(context.Background(), opts)
	require.Error(t, err)
	assert.ErrorIs(t, err, elasticache.ErrReplicationGroupAlreadyExists)
}

func TestBackend_CreateReplicationGroupFull_InvalidParamGroup(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1")

	_, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:                 "param-rg",
		Description:        "invalid param group",
		ParameterGroupName: "nonexistent-group",
	})

	require.Error(t, err)
	assert.ErrorIs(t, err, elasticache.ErrParameterGroupNotFound)
}

// ----------------------------------------
// ModifyReplicationGroupFull — backend unit tests
// ----------------------------------------

func TestBackend_ModifyReplicationGroupFull_ApplyImmediately(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1")

	_, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:          "modify-imm-rg",
		Description: "immediate test",
	})
	require.NoError(t, err)

	rg, err := b.ModifyReplicationGroupFull(
		context.Background(),
		"modify-imm-rg",
		elasticache.ReplicationGroupModifyOpts{
			EngineVersion:    "7.0.7",
			CacheNodeType:    "cache.r6g.large",
			ApplyImmediately: true,
		},
	)

	require.NoError(t, err)
	assert.Equal(t, "7.0.7", rg.EngineVersion)
	assert.Equal(t, "cache.r6g.large", rg.CacheNodeType)
	assert.Nil(t, rg.PendingModifiedValues)
}

func TestBackend_ModifyReplicationGroupFull_PendingChanges(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1")

	_, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:          "modify-pending-rg",
		Description: "pending changes test",
	})
	require.NoError(t, err)

	rg, err := b.ModifyReplicationGroupFull(
		context.Background(),
		"modify-pending-rg",
		elasticache.ReplicationGroupModifyOpts{
			EngineVersion:    "7.0.7",
			ApplyImmediately: false,
		},
	)

	require.NoError(t, err)
	require.NotNil(t, rg.PendingModifiedValues)
	assert.Equal(t, "7.0.7", rg.PendingModifiedValues.EngineVersion)
}

func TestBackend_ModifyReplicationGroupFull_AuthTokenRotate(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1")

	_, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:               "auth-rotate-rg",
		Description:      "auth rotate test",
		AuthTokenEnabled: true,
		AuthToken:        "original-token",
	})
	require.NoError(t, err)

	rg, err := b.ModifyReplicationGroupFull(
		context.Background(),
		"auth-rotate-rg",
		elasticache.ReplicationGroupModifyOpts{
			AuthTokenUpdateStrategy: "ROTATE",
			ApplyImmediately:        true,
		},
	)

	require.NoError(t, err)
	assert.NotEqual(t, "original-token", rg.AuthToken)
	assert.True(t, rg.AuthTokenEnabled)
	assert.NotNil(t, rg.AuthTokenLastModifiedDate)
}

func TestBackend_ModifyReplicationGroupFull_AuthTokenDelete(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1")

	_, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:               "auth-delete-rg",
		Description:      "auth delete test",
		AuthTokenEnabled: true,
		AuthToken:        "to-be-deleted",
	})
	require.NoError(t, err)

	rg, err := b.ModifyReplicationGroupFull(
		context.Background(),
		"auth-delete-rg",
		elasticache.ReplicationGroupModifyOpts{
			AuthTokenUpdateStrategy: "DELETE",
			ApplyImmediately:        true,
		},
	)

	require.NoError(t, err)
	assert.False(t, rg.AuthTokenEnabled)
	assert.Empty(t, rg.AuthToken)
}

func TestBackend_ModifyReplicationGroupFull_AuthTokenSet(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1")

	_, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:          "auth-set-rg",
		Description: "auth set test",
	})
	require.NoError(t, err)

	rg, err := b.ModifyReplicationGroupFull(context.Background(), "auth-set-rg", elasticache.ReplicationGroupModifyOpts{
		AuthToken:               "new-token",
		AuthTokenUpdateStrategy: "SET",
		ApplyImmediately:        true,
	})

	require.NoError(t, err)
	assert.True(t, rg.AuthTokenEnabled)
	assert.Equal(t, "new-token", rg.AuthToken)
}

func TestBackend_ModifyReplicationGroupFull_TransitEncryptionMode(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1")

	_, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:          "transit-mode-rg",
		Description: "transit mode test",
	})
	require.NoError(t, err)

	rg, err := b.ModifyReplicationGroupFull(
		context.Background(),
		"transit-mode-rg",
		elasticache.ReplicationGroupModifyOpts{
			TransitEncryptionMode:   "required",
			AuthToken:               "token-for-required",
			AuthTokenUpdateStrategy: "SET",
			ApplyImmediately:        true,
		},
	)

	require.NoError(t, err)
	assert.Equal(t, "required", rg.TransitEncryptionMode)
	assert.True(t, rg.TransitEncryptionEnabled)
}

func TestBackend_ModifyReplicationGroupFull_SnapshotRetentionLimit(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1")

	_, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:          "snap-ret-modify-rg",
		Description: "snapshot retention modify",
	})
	require.NoError(t, err)

	limit := 14
	rg, err := b.ModifyReplicationGroupFull(
		context.Background(),
		"snap-ret-modify-rg",
		elasticache.ReplicationGroupModifyOpts{
			SnapshotRetentionLimit: &limit,
			ApplyImmediately:       true,
		},
	)

	require.NoError(t, err)
	assert.Equal(t, 14, rg.SnapshotRetentionLimit)
}

func TestBackend_ModifyReplicationGroupFull_ReplicaCount(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1")

	_, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:          "replica-count-rg",
		Description: "replica count test",
	})
	require.NoError(t, err)

	rc := int32(3)
	rg, err := b.ModifyReplicationGroupFull(
		context.Background(),
		"replica-count-rg",
		elasticache.ReplicationGroupModifyOpts{
			ReplicaCount:     &rc,
			ApplyImmediately: true,
		},
	)

	require.NoError(t, err)
	assert.Equal(t, int32(3), rg.ReplicaCount)
}

func TestBackend_ModifyReplicationGroupFull_NotFound(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1")

	_, err := b.ModifyReplicationGroupFull(
		context.Background(),
		"nonexistent-rg",
		elasticache.ReplicationGroupModifyOpts{
			Description: "should fail",
		},
	)

	require.Error(t, err)
	assert.ErrorIs(t, err, elasticache.ErrReplicationGroupNotFound)
}

func TestBackend_ModifyReplicationGroupFull_InvalidParamGroup(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1")

	_, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:          "pg-mod-rg",
		Description: "param group modify",
	})
	require.NoError(t, err)

	_, err = b.ModifyReplicationGroupFull(context.Background(), "pg-mod-rg", elasticache.ReplicationGroupModifyOpts{
		ParameterGroupName: "nonexistent-group",
	})

	require.Error(t, err)
	assert.ErrorIs(t, err, elasticache.ErrParameterGroupNotFound)
}

// ----------------------------------------
// TriggerAutoSnapshot — backend unit tests
// ----------------------------------------

func TestBackend_TriggerAutoSnapshot_Success(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1")

	_, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:          "auto-snap-rg",
		Description: "auto snapshot test",
	})
	require.NoError(t, err)

	snap, err := b.TriggerAutoSnapshot(context.Background(), "auto-snap-rg")

	require.NoError(t, err)
	assert.Equal(t, "automated", snap.SnapshotSource)
	assert.Equal(t, "auto-snap-rg", snap.ReplicationGroupID)
	assert.Equal(t, "available", snap.Status)
	assert.NotEmpty(t, snap.ARN)
}

func TestBackend_TriggerAutoSnapshot_NotFound(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1")

	_, err := b.TriggerAutoSnapshot(context.Background(), "nonexistent-rg")

	require.Error(t, err)
	assert.ErrorIs(t, err, elasticache.ErrReplicationGroupNotFound)
}

func TestBackend_TriggerAutoSnapshot_PrunesOldSnapshots(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1")

	_, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:                     "prune-snap-rg",
		Description:            "pruning test",
		SnapshotRetentionLimit: 1,
	})
	require.NoError(t, err)

	// Create a manual snapshot to serve as an "old" automated snapshot via seed.
	elasticache.AddSnapshotInternal(b, "prune-snap-rg-auto-old", "prune-snap-rg", "automated")

	// Trigger auto snapshot — should prune the old one.
	_, err = b.TriggerAutoSnapshot(context.Background(), "prune-snap-rg")
	require.NoError(t, err)

	// Only 1 automated snapshot should remain.
	page, err := b.DescribeSnapshots(context.Background(), "", "", "prune-snap-rg", "", 100)
	require.NoError(t, err)

	autoCount := 0
	for _, s := range page.Data {
		if s.SnapshotSource == "automated" {
			autoCount++
		}
	}

	assert.LessOrEqual(t, autoCount, 1)
}

func TestBackend_TriggerAutoSnapshot_DuplicateSameDay(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1")

	_, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:          "dup-snap-rg",
		Description: "duplicate snapshot test",
	})
	require.NoError(t, err)

	_, err = b.TriggerAutoSnapshot(context.Background(), "dup-snap-rg")
	require.NoError(t, err)

	_, err = b.TriggerAutoSnapshot(context.Background(), "dup-snap-rg")
	require.Error(t, err)
	assert.ErrorIs(t, err, elasticache.ErrSnapshotAlreadyExists)
}

// ----------------------------------------
// HTTP handler — CreateReplicationGroup with new fields
// ----------------------------------------

func TestHandler_CreateReplicationGroup_WithAuthToken(t *testing.T) {
	t.Parallel()

	client := newTestStack(t)

	out, err := client.CreateReplicationGroup(t.Context(), &elasticachesdk.CreateReplicationGroupInput{
		ReplicationGroupId:          aws.String("http-auth-rg"),
		ReplicationGroupDescription: aws.String("with auth token via HTTP"),
		AuthToken:                   aws.String("secret-http-token"),
		TransitEncryptionEnabled:    aws.Bool(true),
	})

	require.NoError(t, err)
	require.NotNil(t, out.ReplicationGroup)
	assert.Equal(t, "http-auth-rg", aws.ToString(out.ReplicationGroup.ReplicationGroupId))
	assert.True(t, aws.ToBool(out.ReplicationGroup.AuthTokenEnabled))
}

func TestHandler_CreateReplicationGroup_WithClusterMode(t *testing.T) {
	t.Parallel()

	client := newTestStack(t)

	out, err := client.CreateReplicationGroup(t.Context(), &elasticachesdk.CreateReplicationGroupInput{
		ReplicationGroupId:          aws.String("http-cluster-rg"),
		ReplicationGroupDescription: aws.String("cluster mode via HTTP"),
		ClusterMode:                 elasticachetypes.ClusterModeEnabled,
		NumNodeGroups:               aws.Int32(2),
		ReplicasPerNodeGroup:        aws.Int32(1),
	})

	require.NoError(t, err)
	require.NotNil(t, out.ReplicationGroup)
	assert.True(t, aws.ToBool(out.ReplicationGroup.ClusterEnabled))
}

func TestHandler_CreateReplicationGroup_WithKmsKey(t *testing.T) {
	t.Parallel()

	client := newTestStack(t)

	kmsKey := "arn:aws:kms:us-east-1:123456789012:key/test-key"
	out, err := client.CreateReplicationGroup(t.Context(), &elasticachesdk.CreateReplicationGroupInput{
		ReplicationGroupId:          aws.String("http-kms-rg"),
		ReplicationGroupDescription: aws.String("kms key via HTTP"),
		KmsKeyId:                    aws.String(kmsKey),
		AtRestEncryptionEnabled:     aws.Bool(true),
	})

	require.NoError(t, err)
	require.NotNil(t, out.ReplicationGroup)
	assert.Equal(t, kmsKey, aws.ToString(out.ReplicationGroup.KmsKeyId))
	assert.True(t, aws.ToBool(out.ReplicationGroup.AtRestEncryptionEnabled))
}

func TestHandler_CreateReplicationGroup_WithSnapshotRetention(t *testing.T) {
	t.Parallel()

	client := newTestStack(t)

	out, err := client.CreateReplicationGroup(t.Context(), &elasticachesdk.CreateReplicationGroupInput{
		ReplicationGroupId:          aws.String("http-snap-rg"),
		ReplicationGroupDescription: aws.String("snapshot retention via HTTP"),
		SnapshotRetentionLimit:      aws.Int32(7),
		SnapshotWindow:              aws.String("05:00-06:00"),
	})

	require.NoError(t, err)
	require.NotNil(t, out.ReplicationGroup)
	assert.Equal(t, int32(7), aws.ToInt32(out.ReplicationGroup.SnapshotRetentionLimit))
}

func TestHandler_CreateReplicationGroup_TransitEncryptionRequired_WithToken(t *testing.T) {
	t.Parallel()

	client := newTestStack(t)

	out, err := client.CreateReplicationGroup(t.Context(), &elasticachesdk.CreateReplicationGroupInput{
		ReplicationGroupId:          aws.String("http-transit-req-rg"),
		ReplicationGroupDescription: aws.String("transit required with token"),
		AuthToken:                   aws.String("required-token"),
		TransitEncryptionEnabled:    aws.Bool(true),
		TransitEncryptionMode:       elasticachetypes.TransitEncryptionModeRequired,
	})

	require.NoError(t, err)
	require.NotNil(t, out.ReplicationGroup)
	assert.True(t, aws.ToBool(out.ReplicationGroup.TransitEncryptionEnabled))
	assert.Equal(t, elasticachetypes.TransitEncryptionModeRequired, out.ReplicationGroup.TransitEncryptionMode)
}

func TestHandler_CreateReplicationGroup_DataTiering(t *testing.T) {
	t.Parallel()

	client := newTestStack(t)

	out, err := client.CreateReplicationGroup(t.Context(), &elasticachesdk.CreateReplicationGroupInput{
		ReplicationGroupId:          aws.String("http-data-tier-rg"),
		ReplicationGroupDescription: aws.String("data tiering"),
		DataTieringEnabled:          aws.Bool(true),
		CacheNodeType:               aws.String("cache.r7g.large"),
		EngineVersion:               aws.String("7.1.0"),
	})

	require.NoError(t, err)
	require.NotNil(t, out.ReplicationGroup)
	assert.Equal(t, elasticachetypes.DataTieringStatusEnabled, out.ReplicationGroup.DataTiering)
}

// ----------------------------------------
// HTTP handler — ModifyReplicationGroup with new fields
// ----------------------------------------

func TestHandler_ModifyReplicationGroup_ApplyImmediately(t *testing.T) {
	t.Parallel()

	client := newTestStack(t)

	_, err := client.CreateReplicationGroup(t.Context(), &elasticachesdk.CreateReplicationGroupInput{
		ReplicationGroupId:          aws.String("http-modify-imm-rg"),
		ReplicationGroupDescription: aws.String("modify apply immediately"),
	})
	require.NoError(t, err)

	out, err := client.ModifyReplicationGroup(t.Context(), &elasticachesdk.ModifyReplicationGroupInput{
		ReplicationGroupId: aws.String("http-modify-imm-rg"),
		EngineVersion:      aws.String("7.0.7"),
		ApplyImmediately:   aws.Bool(true),
	})

	require.NoError(t, err)
	require.NotNil(t, out.ReplicationGroup)
	// Verify modification succeeded by checking the describe output.
	desc, descErr := client.DescribeReplicationGroups(t.Context(), &elasticachesdk.DescribeReplicationGroupsInput{
		ReplicationGroupId: aws.String("http-modify-imm-rg"),
	})
	require.NoError(t, descErr)
	require.Len(t, desc.ReplicationGroups, 1)
}

func TestHandler_ModifyReplicationGroup_WithAutoFailover(t *testing.T) {
	t.Parallel()

	client := newTestStack(t)

	_, err := client.CreateReplicationGroup(t.Context(), &elasticachesdk.CreateReplicationGroupInput{
		ReplicationGroupId:          aws.String("http-failover-rg"),
		ReplicationGroupDescription: aws.String("failover test"),
	})
	require.NoError(t, err)

	out, err := client.ModifyReplicationGroup(t.Context(), &elasticachesdk.ModifyReplicationGroupInput{
		ReplicationGroupId:       aws.String("http-failover-rg"),
		AutomaticFailoverEnabled: aws.Bool(true),
		ApplyImmediately:         aws.Bool(true),
	})

	require.NoError(t, err)
	require.NotNil(t, out.ReplicationGroup)
	assert.Equal(t, elasticachetypes.AutomaticFailoverStatusEnabled, out.ReplicationGroup.AutomaticFailover)
}

func TestHandler_ModifyReplicationGroup_NotFound(t *testing.T) {
	t.Parallel()

	client := newTestStack(t)

	_, err := client.ModifyReplicationGroup(t.Context(), &elasticachesdk.ModifyReplicationGroupInput{
		ReplicationGroupId:          aws.String("nonexistent-rg"),
		ReplicationGroupDescription: aws.String("should fail"),
	})

	require.Error(t, err)
}

// ----------------------------------------
// Valkey engine — DescribeCacheEngineVersions
// ----------------------------------------

func TestDescribeCacheEngineVersions_Valkey(t *testing.T) {
	t.Parallel()

	client := newTestStack(t)

	out, err := client.DescribeCacheEngineVersions(t.Context(), &elasticachesdk.DescribeCacheEngineVersionsInput{
		Engine: aws.String("valkey"),
	})

	require.NoError(t, err)
	assert.GreaterOrEqual(t, len(out.CacheEngineVersions), 2)

	for _, v := range out.CacheEngineVersions {
		assert.Equal(t, "valkey", aws.ToString(v.Engine))
	}
}

func TestDescribeCacheEngineVersions_ValkeyFamily(t *testing.T) {
	t.Parallel()

	client := newTestStack(t)

	out, err := client.DescribeCacheEngineVersions(t.Context(), &elasticachesdk.DescribeCacheEngineVersionsInput{
		CacheParameterGroupFamily: aws.String("valkey8"),
	})

	require.NoError(t, err)
	assert.GreaterOrEqual(t, len(out.CacheEngineVersions), 1)

	for _, v := range out.CacheEngineVersions {
		assert.Equal(t, "valkey8", aws.ToString(v.CacheParameterGroupFamily))
	}
}

// ----------------------------------------
// ClusterMode enforcement tests
// ----------------------------------------

func TestBackend_ModifyReplicationGroupShardConfiguration_RequiresClusterMode(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1")

	_, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:                 "no-cluster-rg",
		Description:        "no cluster mode",
		ClusterModeEnabled: false,
	})
	require.NoError(t, err)

	_, err = b.ModifyReplicationGroupShardConfiguration(context.Background(), "no-cluster-rg", 2)
	require.Error(t, err)
	assert.ErrorIs(t, err, elasticache.ErrClusterModeRequired)
}

func TestBackend_ModifyReplicationGroupShardConfiguration_WithClusterMode(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1")

	_, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:                 "yes-cluster-rg",
		Description:        "with cluster mode",
		ClusterModeEnabled: true,
		NumNodeGroups:      2,
	})
	require.NoError(t, err)

	rg, err := b.ModifyReplicationGroupShardConfiguration(context.Background(), "yes-cluster-rg", 4)
	require.NoError(t, err)
	assert.Len(t, rg.NodeGroups, 4)
}

// ----------------------------------------
// Memcached CacheNodeMember tracking (gap #3)
// ----------------------------------------

func TestHandler_CreateCacheCluster_Memcached_Members(t *testing.T) {
	t.Parallel()

	client := newTestStack(t)

	out, err := client.CreateCacheCluster(t.Context(), &elasticachesdk.CreateCacheClusterInput{
		CacheClusterId: aws.String("memcached-cluster"),
		Engine:         aws.String("memcached"),
		CacheNodeType:  aws.String("cache.t3.micro"),
		NumCacheNodes:  aws.Int32(3),
	})

	require.NoError(t, err)
	require.NotNil(t, out.CacheCluster)
	assert.Equal(t, int32(3), aws.ToInt32(out.CacheCluster.NumCacheNodes))
}

// ----------------------------------------
// DescribeCacheParameterGroups — Valkey families
// ----------------------------------------

func TestDescribeCacheParameterGroups_Valkey(t *testing.T) {
	t.Parallel()

	client := newTestStack(t)

	out, err := client.DescribeCacheParameterGroups(t.Context(), &elasticachesdk.DescribeCacheParameterGroupsInput{})

	require.NoError(t, err)

	families := make(map[string]bool)
	for _, pg := range out.CacheParameterGroups {
		families[aws.ToString(pg.CacheParameterGroupFamily)] = true
	}

	assert.True(t, families["valkey8"], "expected valkey8 family")
	assert.True(t, families["valkey7"], "expected valkey7 family")
}

// ----------------------------------------
// GlobalReplicationGroup — region tracking (gap #12)
// ----------------------------------------

func TestBackend_CreateGlobalReplicationGroup_PrimaryRegion(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1")

	_, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:          "grg-primary",
		Description: "primary for global",
	})
	require.NoError(t, err)

	grg, err := b.CreateGlobalReplicationGroup(context.Background(), "my-global", "global test", "grg-primary")
	require.NoError(t, err)

	assert.NotEmpty(t, grg.PrimaryReplicationGroupRegion)
	assert.Equal(t, "us-east-1", grg.PrimaryReplicationGroupRegion)
	assert.NotNil(t, grg.SecondaryReplicationGroups)
}

// ----------------------------------------
// UserGroup RBAC binding tracking (gap #15)
// ----------------------------------------

func TestBackend_UserGroup_AssignedReplicationGroupIDs(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1")

	_, err := b.CreateUser(context.Background(), "u1", "user1", "on ~* +@all", "redis", false)
	require.NoError(t, err)

	ug, err := b.CreateUserGroup(context.Background(), "ug1", "group 1", "redis", []string{"u1"})
	require.NoError(t, err)

	assert.NotNil(t, ug)
	assert.Contains(t, ug.UserIDs, "u1")
	// AssignedReplicationGroupIDs starts empty (populated when bound to RG).
	assert.Empty(t, ug.AssignedReplicationGroupIDs)
}

// ----------------------------------------
// Persistence: new fields survive snapshot/restore
// ----------------------------------------

func TestBackend_Persistence_NewFieldsRoundTrip(t *testing.T) {
	t.Parallel()

	b1 := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1")

	_, err := b1.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:                       "persist-rg",
		Description:              "persistence test",
		ClusterModeEnabled:       true,
		AuthTokenEnabled:         true,
		AuthToken:                "persist-token",
		KmsKeyID:                 "arn:aws:kms:us-east-1:123:key/abc",
		AtRestEncryptionEnabled:  true,
		TransitEncryptionEnabled: true,
		TransitEncryptionMode:    "preferred",
		DataTieringEnabled:       false,
		SnapshotRetentionLimit:   3,
		NotificationTopicArn:     "arn:aws:sns:us-east-1:123:topic",
	})
	require.NoError(t, err)

	snap := b1.Snapshot()
	require.NotNil(t, snap)

	b2 := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1")
	err = b2.Restore(snap)
	require.NoError(t, err)

	page, err := b2.DescribeReplicationGroups(context.Background(), "persist-rg", "", 0)
	require.NoError(t, err)
	require.Len(t, page.Data, 1)

	rg := page.Data[0]
	assert.True(t, rg.ClusterModeEnabled)
	assert.True(t, rg.AuthTokenEnabled)
	assert.True(t, rg.AtRestEncryptionEnabled)
	assert.True(t, rg.TransitEncryptionEnabled)
	assert.Equal(t, "preferred", rg.TransitEncryptionMode)
	assert.Equal(t, 3, rg.SnapshotRetentionLimit)
	assert.Equal(t, "arn:aws:sns:us-east-1:123:topic", rg.NotificationTopicArn)
}

// ----------------------------------------
// GetSupportedOperations includes new ops
// ----------------------------------------

func TestHandler_GetSupportedOperations_Audit1(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1")
	h := elasticache.NewHandler(b)
	ops := h.GetSupportedOperations()

	// These were supported before and must remain supported.
	essentialOps := []string{
		"CreateReplicationGroup",
		"ModifyReplicationGroup",
		"DescribeCacheEngineVersions",
	}
	for _, op := range essentialOps {
		assert.Contains(t, ops, op)
	}
}
