package elasticache_test

import (
	"context"
	"net/http"
	"testing"
	"time"

	elasticachesdk "github.com/aws/aws-sdk-go-v2/service/elasticache"
	elasticachetypes "github.com/aws/aws-sdk-go-v2/service/elasticache/types"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/blackbirdworks/gopherstack/services/elasticache"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestFailoverReplicationGroup(t *testing.T) {
	t.Parallel()

	tests := []struct {
		wantErr error
		name    string
		rgID    string
	}{
		{
			name:    "failover_existing_group",
			rgID:    "my-rg",
			wantErr: nil,
		},
		{
			name:    "failover_missing_group",
			rgID:    "nonexistent",
			wantErr: elasticache.ErrReplicationGroupNotFound,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			backend := elasticache.NewInMemoryBackend(elasticache.EngineStub, "123456789012", "us-east-1", nil)

			if tt.wantErr == nil {
				_, err := backend.CreateReplicationGroup(context.Background(), tt.rgID, "test rg")
				require.NoError(t, err)
			}

			rg, err := backend.FailoverReplicationGroup(context.Background(), tt.rgID, "0001")

			if tt.wantErr != nil {
				require.ErrorIs(t, err, tt.wantErr)

				return
			}

			require.NoError(t, err)
			assert.Equal(t, "available", rg.Status)

			p, evErr := backend.DescribeEvents(
				context.Background(),
				tt.rgID,
				"replication-group",
				"",
				time.Time{},
				time.Time{},
				0,
				0,
			)
			require.NoError(t, evErr)

			found := false
			for _, e := range p.Data {
				if e.Message == "failover completed" {
					found = true
				}
			}
			assert.True(t, found, "expected failover event not found")
		})
	}
}

func TestBackend_CreateReplicationGroupFull_ClusterMode(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1", nil)

	rg, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:                   "cluster-rg",
		Description:          "cluster mode enabled",
		ClusterModeEnabled:   true,
		NumNodeGroups:        3,
		ReplicasPerNodeGroup: 1,
	})

	require.NoError(t, err)
	assert.True(t, rg.ClusterModeEnabled)
	assert.Len(t, rg.NodeGroups, 3)
	assert.Equal(t, int32(1), rg.ReplicaCount)
}

func TestBackend_CreateReplicationGroupFull_AuthToken(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1", nil)

	rg, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:               "auth-rg",
		Description:      "with auth token",
		AuthTokenEnabled: true,
		AuthToken:        "my-secret-token",
	})

	require.NoError(t, err)
	assert.True(t, rg.AuthTokenEnabled)
	assert.NotNil(t, rg.AuthTokenLastModifiedDate)
}

func TestBackend_CreateReplicationGroupFull_AuthToken_AutoGenerated(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1", nil)

	rg, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:               "auth-auto-rg",
		Description:      "auto generated token",
		AuthTokenEnabled: true,
	})

	require.NoError(t, err)
	assert.True(t, rg.AuthTokenEnabled)
	assert.NotEmpty(t, rg.AuthToken)
	assert.NotNil(t, rg.AuthTokenLastModifiedDate)
}

func TestBackend_CreateReplicationGroupFull_KmsKey(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1", nil)

	kmsKey := "arn:aws:kms:us-east-1:123456789012:key/12345678-1234-1234-1234-123456789012"
	rg, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:                      "kms-rg",
		Description:             "with kms key",
		KmsKeyID:                kmsKey,
		AtRestEncryptionEnabled: true,
	})

	require.NoError(t, err)
	assert.Equal(t, kmsKey, rg.KmsKeyID)
	assert.True(t, rg.AtRestEncryptionEnabled)
}

func TestBackend_CreateReplicationGroupFull_TransitEncryption(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1", nil)

	rg, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:                       "transit-rg",
		Description:              "transit encryption",
		TransitEncryptionEnabled: true,
		TransitEncryptionMode:    "preferred",
	})

	require.NoError(t, err)
	assert.True(t, rg.TransitEncryptionEnabled)
	assert.Equal(t, "preferred", rg.TransitEncryptionMode)
}

func TestBackend_CreateReplicationGroupFull_TransitEncryptionRequired_WithoutToken_Fails(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1", nil)

	_, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:                       "transit-required-rg",
		Description:              "transit required without token",
		TransitEncryptionEnabled: true,
		TransitEncryptionMode:    "required",
		AuthTokenEnabled:         false,
	})

	require.Error(t, err)
	assert.ErrorIs(t, err, elasticache.ErrAuthTokenRequiredForMode)
}

func TestBackend_CreateReplicationGroupFull_LogDelivery(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1", nil)

	ldConfigs := []elasticache.LogDeliveryConfig{
		{
			LogType:            "slow-log",
			DestinationType:    "cloudwatch-logs",
			DestinationDetails: "/aws/elasticache/slow-log",
			LogFormat:          "json",
			Status:             "active",
		},
	}

	rg, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:                        "log-rg",
		Description:               "with log delivery",
		LogDeliveryConfigurations: ldConfigs,
		NotificationTopicArn:      "arn:aws:sns:us-east-1:123456789012:MyTopic",
	})

	require.NoError(t, err)
	assert.Len(t, rg.LogDeliveryConfigurations, 1)
	assert.Equal(t, "slow-log", rg.LogDeliveryConfigurations[0].LogType)
	assert.Equal(t, "arn:aws:sns:us-east-1:123456789012:MyTopic", rg.NotificationTopicArn)
}

func TestBackend_CreateReplicationGroupFull_DataTiering_Valid(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1", nil)

	rg, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:                 "data-tier-rg",
		Description:        "data tiering",
		DataTieringEnabled: true,
		CacheNodeType:      "cache.r7g.large",
		EngineVersion:      "7.1.0",
	})

	require.NoError(t, err)
	assert.True(t, rg.DataTieringEnabled)
}

func TestBackend_CreateReplicationGroupFull_DataTiering_InvalidNodeType(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1", nil)

	_, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:                 "data-tier-bad-rg",
		Description:        "bad data tiering",
		DataTieringEnabled: true,
		CacheNodeType:      "cache.t3.micro",
	})

	require.Error(t, err)
	assert.ErrorIs(t, err, elasticache.ErrDataTieringInvalid)
}

func TestBackend_CreateReplicationGroupFull_SnapshotRetentionLimit(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1", nil)

	rg, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:                     "snap-ret-rg",
		Description:            "snapshot retention",
		SnapshotRetentionLimit: 7,
		SnapshotWindow:         "03:00-04:00",
	})

	require.NoError(t, err)
	assert.Equal(t, 7, rg.SnapshotRetentionLimit)
	assert.Equal(t, "03:00-04:00", rg.SnapshotWindow)
}

func TestBackend_CreateReplicationGroupFull_Valkey(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1", nil)

	rg, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:            "valkey-rg",
		Description:   "valkey engine",
		Engine:        "valkey",
		EngineVersion: "8.2.0",
	})

	require.NoError(t, err)
	assert.Equal(t, "valkey", rg.Engine)
	assert.Equal(t, "8.2.0", rg.EngineVersion)
}

func TestBackend_CreateReplicationGroupFull_AlreadyExists(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1", nil)

	opts := elasticache.ReplicationGroupCreateOpts{
		ID:          "dup-rg",
		Description: "first",
	}

	_, err := b.CreateReplicationGroupFull(context.Background(), opts)
	require.NoError(t, err)

	_, err = b.CreateReplicationGroupFull(context.Background(), opts)
	require.Error(t, err)
	assert.ErrorIs(t, err, elasticache.ErrReplicationGroupAlreadyExists)
}

func TestBackend_CreateReplicationGroupFull_InvalidParamGroup(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1", nil)

	_, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:                 "param-rg",
		Description:        "invalid param group",
		ParameterGroupName: "nonexistent-group",
	})

	require.Error(t, err)
	assert.ErrorIs(t, err, elasticache.ErrParameterGroupNotFound)
}

// ----------------------------------------
// ModifyReplicationGroupFull — backend unit tests
// ----------------------------------------

func TestBackend_ModifyReplicationGroupFull_ApplyImmediately(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1", nil)

	_, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:          "modify-imm-rg",
		Description: "immediate test",
	})
	require.NoError(t, err)

	rg, err := b.ModifyReplicationGroupFull(
		context.Background(),
		"modify-imm-rg",
		elasticache.ReplicationGroupModifyOpts{
			EngineVersion:    "7.0.7",
			CacheNodeType:    "cache.r6g.large",
			ApplyImmediately: true,
		},
	)

	require.NoError(t, err)
	assert.Equal(t, "7.0.7", rg.EngineVersion)
	assert.Equal(t, "cache.r6g.large", rg.CacheNodeType)
	assert.Nil(t, rg.PendingModifiedValues)
}

func TestBackend_ModifyReplicationGroupFull_PendingChanges(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1", nil)

	_, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:          "modify-pending-rg",
		Description: "pending changes test",
	})
	require.NoError(t, err)

	rg, err := b.ModifyReplicationGroupFull(
		context.Background(),
		"modify-pending-rg",
		elasticache.ReplicationGroupModifyOpts{
			EngineVersion:    "7.0.7",
			ApplyImmediately: false,
		},
	)

	require.NoError(t, err)
	require.NotNil(t, rg.PendingModifiedValues)
	assert.Equal(t, "7.0.7", rg.PendingModifiedValues.EngineVersion)
}

func TestBackend_ModifyReplicationGroupFull_AuthTokenRotate(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1", nil)

	_, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:               "auth-rotate-rg",
		Description:      "auth rotate test",
		AuthTokenEnabled: true,
		AuthToken:        "original-token",
	})
	require.NoError(t, err)

	rg, err := b.ModifyReplicationGroupFull(
		context.Background(),
		"auth-rotate-rg",
		elasticache.ReplicationGroupModifyOpts{
			AuthTokenUpdateStrategy: "ROTATE",
			ApplyImmediately:        true,
		},
	)

	require.NoError(t, err)
	assert.NotEqual(t, "original-token", rg.AuthToken)
	assert.True(t, rg.AuthTokenEnabled)
	assert.NotNil(t, rg.AuthTokenLastModifiedDate)
}

func TestBackend_ModifyReplicationGroupFull_AuthTokenDelete(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1", nil)

	_, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:               "auth-delete-rg",
		Description:      "auth delete test",
		AuthTokenEnabled: true,
		AuthToken:        "to-be-deleted",
	})
	require.NoError(t, err)

	rg, err := b.ModifyReplicationGroupFull(
		context.Background(),
		"auth-delete-rg",
		elasticache.ReplicationGroupModifyOpts{
			AuthTokenUpdateStrategy: "DELETE",
			ApplyImmediately:        true,
		},
	)

	require.NoError(t, err)
	assert.False(t, rg.AuthTokenEnabled)
	assert.Empty(t, rg.AuthToken)
}

func TestBackend_ModifyReplicationGroupFull_AuthTokenSet(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1", nil)

	_, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:          "auth-set-rg",
		Description: "auth set test",
	})
	require.NoError(t, err)

	rg, err := b.ModifyReplicationGroupFull(context.Background(), "auth-set-rg", elasticache.ReplicationGroupModifyOpts{
		AuthToken:               "new-token",
		AuthTokenUpdateStrategy: "SET",
		ApplyImmediately:        true,
	})

	require.NoError(t, err)
	assert.True(t, rg.AuthTokenEnabled)
	assert.Equal(t, "new-token", rg.AuthToken)
}

func TestBackend_ModifyReplicationGroupFull_TransitEncryptionMode(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1", nil)

	_, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:          "transit-mode-rg",
		Description: "transit mode test",
	})
	require.NoError(t, err)

	rg, err := b.ModifyReplicationGroupFull(
		context.Background(),
		"transit-mode-rg",
		elasticache.ReplicationGroupModifyOpts{
			TransitEncryptionMode:   "required",
			AuthToken:               "token-for-required",
			AuthTokenUpdateStrategy: "SET",
			ApplyImmediately:        true,
		},
	)

	require.NoError(t, err)
	assert.Equal(t, "required", rg.TransitEncryptionMode)
	assert.True(t, rg.TransitEncryptionEnabled)
}

func TestBackend_ModifyReplicationGroupFull_SnapshotRetentionLimit(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1", nil)

	_, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:          "snap-ret-modify-rg",
		Description: "snapshot retention modify",
	})
	require.NoError(t, err)

	limit := 14
	rg, err := b.ModifyReplicationGroupFull(
		context.Background(),
		"snap-ret-modify-rg",
		elasticache.ReplicationGroupModifyOpts{
			SnapshotRetentionLimit: &limit,
			ApplyImmediately:       true,
		},
	)

	require.NoError(t, err)
	assert.Equal(t, 14, rg.SnapshotRetentionLimit)
}

func TestBackend_ModifyReplicationGroupFull_ReplicaCount(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1", nil)

	_, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:          "replica-count-rg",
		Description: "replica count test",
	})
	require.NoError(t, err)

	rc := int32(3)
	rg, err := b.ModifyReplicationGroupFull(
		context.Background(),
		"replica-count-rg",
		elasticache.ReplicationGroupModifyOpts{
			ReplicaCount:     &rc,
			ApplyImmediately: true,
		},
	)

	require.NoError(t, err)
	assert.Equal(t, int32(3), rg.ReplicaCount)
}

func TestBackend_ModifyReplicationGroupFull_NotFound(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1", nil)

	_, err := b.ModifyReplicationGroupFull(
		context.Background(),
		"nonexistent-rg",
		elasticache.ReplicationGroupModifyOpts{
			Description: "should fail",
		},
	)

	require.Error(t, err)
	assert.ErrorIs(t, err, elasticache.ErrReplicationGroupNotFound)
}

func TestBackend_ModifyReplicationGroupFull_InvalidParamGroup(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1", nil)

	_, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:          "pg-mod-rg",
		Description: "param group modify",
	})
	require.NoError(t, err)

	_, err = b.ModifyReplicationGroupFull(context.Background(), "pg-mod-rg", elasticache.ReplicationGroupModifyOpts{
		ParameterGroupName: "nonexistent-group",
	})

	require.Error(t, err)
	assert.ErrorIs(t, err, elasticache.ErrParameterGroupNotFound)
}

// ----------------------------------------
// TriggerAutoSnapshot — backend unit tests
// ----------------------------------------

func TestBackend_TriggerAutoSnapshot_Success(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1", nil)

	_, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:          "auto-snap-rg",
		Description: "auto snapshot test",
	})
	require.NoError(t, err)

	snap, err := b.TriggerAutoSnapshot(context.Background(), "auto-snap-rg")

	require.NoError(t, err)
	assert.Equal(t, "automated", snap.SnapshotSource)
	assert.Equal(t, "auto-snap-rg", snap.ReplicationGroupID)
	assert.Equal(t, "available", snap.Status)
	assert.NotEmpty(t, snap.ARN)
}

func TestBackend_TriggerAutoSnapshot_NotFound(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1", nil)

	_, err := b.TriggerAutoSnapshot(context.Background(), "nonexistent-rg")

	require.Error(t, err)
	assert.ErrorIs(t, err, elasticache.ErrReplicationGroupNotFound)
}

func TestBackend_TriggerAutoSnapshot_PrunesOldSnapshots(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1", nil)

	_, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:                     "prune-snap-rg",
		Description:            "pruning test",
		SnapshotRetentionLimit: 1,
	})
	require.NoError(t, err)

	// Create a manual snapshot to serve as an "old" automated snapshot via seed.
	elasticache.AddSnapshotInternal(b, "prune-snap-rg-auto-old", "prune-snap-rg", "automated")

	// Trigger auto snapshot — should prune the old one.
	_, err = b.TriggerAutoSnapshot(context.Background(), "prune-snap-rg")
	require.NoError(t, err)

	// Only 1 automated snapshot should remain.
	page, err := b.DescribeSnapshots(context.Background(), "", "", "prune-snap-rg", "", "", 100)
	require.NoError(t, err)

	autoCount := 0
	for _, s := range page.Data {
		if s.SnapshotSource == "automated" {
			autoCount++
		}
	}

	assert.LessOrEqual(t, autoCount, 1)
}

func TestBackend_TriggerAutoSnapshot_DuplicateSameDay(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1", nil)

	_, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:          "dup-snap-rg",
		Description: "duplicate snapshot test",
	})
	require.NoError(t, err)

	_, err = b.TriggerAutoSnapshot(context.Background(), "dup-snap-rg")
	require.NoError(t, err)

	_, err = b.TriggerAutoSnapshot(context.Background(), "dup-snap-rg")
	require.Error(t, err)
	assert.ErrorIs(t, err, elasticache.ErrSnapshotAlreadyExists)
}

// ----------------------------------------
// HTTP handler — CreateReplicationGroup with new fields
// ----------------------------------------

func TestBackend_ModifyReplicationGroupShardConfiguration_RequiresClusterMode(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1", nil)

	_, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:                 "no-cluster-rg",
		Description:        "no cluster mode",
		ClusterModeEnabled: false,
	})
	require.NoError(t, err)

	_, err = b.ModifyReplicationGroupShardConfiguration(context.Background(), "no-cluster-rg", 2, true)
	require.Error(t, err)
	assert.ErrorIs(t, err, elasticache.ErrClusterModeRequired)
}

func TestBackend_ModifyReplicationGroupShardConfiguration_WithClusterMode(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1", nil)

	_, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:                 "yes-cluster-rg",
		Description:        "with cluster mode",
		ClusterModeEnabled: true,
		NumNodeGroups:      2,
	})
	require.NoError(t, err)

	rg, err := b.ModifyReplicationGroupShardConfiguration(context.Background(), "yes-cluster-rg", 4, true)
	require.NoError(t, err)
	assert.Len(t, rg.NodeGroups, 4)
}

// ----------------------------------------
// Memcached CacheNodeMember tracking (gap #3)
// ----------------------------------------

func TestBackend_TriggerAutoSnapshot_Engine(t *testing.T) {
	t.Parallel()

	b := elasticache.NewInMemoryBackend(elasticache.EngineStub, "000000000000", "us-east-1", nil)

	_, err := b.CreateReplicationGroupFull(context.Background(), elasticache.ReplicationGroupCreateOpts{
		ID:          "engine-snap-rg",
		Description: "engine snapshot test",
		Engine:      "redis",
	})
	require.NoError(t, err)

	snap, err := b.TriggerAutoSnapshot(context.Background(), "engine-snap-rg")
	require.NoError(t, err)
	assert.Equal(t, "automated", snap.SnapshotSource)
	assert.NotEmpty(t, snap.ARN)
	assert.Contains(t, snap.ARN, "arn:aws:elasticache:")
}

// ----------------------------------------
// IncreaseReplicaCount / DecreaseReplicaCount via HTTP
// ----------------------------------------

// Test_CreateReplicationGroup_RestoreFromSnapshot is the replication-group
// counterpart: same previously-dropped SnapshotName parameter, now wired
// through the additive ReplicationGroupCreateOpts.SnapshotName field. As
// with CreateCacheCluster, CreateReplicationGroup's modeled error list also
// omits SnapshotNotFoundFault, so a missing snapshot surfaces as
// InvalidParameterValueException (400) instead.
func Test_CreateReplicationGroup_RestoreFromSnapshot(t *testing.T) {
	t.Parallel()

	client := newTestStack(t)
	ctx := context.Background()

	_, err := client.CreateCacheCluster(ctx, &elasticachesdk.CreateCacheClusterInput{
		CacheClusterId: aws.String("src-cluster-rg"),
		Engine:         aws.String("redis"),
		EngineVersion:  aws.String("7.1.0"),
		CacheNodeType:  aws.String("cache.r6g.large"),
		NumCacheNodes:  aws.Int32(1),
	})
	require.NoError(t, err)

	_, err = client.CreateSnapshot(ctx, &elasticachesdk.CreateSnapshotInput{
		SnapshotName:   aws.String("src-snap-rg"),
		CacheClusterId: aws.String("src-cluster-rg"),
	})
	require.NoError(t, err)

	out, err := client.CreateReplicationGroup(ctx, &elasticachesdk.CreateReplicationGroupInput{
		ReplicationGroupId:          aws.String("restored-rg"),
		ReplicationGroupDescription: aws.String("restored from snapshot"),
		SnapshotName:                aws.String("src-snap-rg"),
	})
	require.NoError(t, err)
	assert.Equal(t, "cache.r6g.large", aws.ToString(out.ReplicationGroup.CacheNodeType))

	_, err = client.CreateReplicationGroup(ctx, &elasticachesdk.CreateReplicationGroupInput{
		ReplicationGroupId:          aws.String("restored-rg-missing"),
		ReplicationGroupDescription: aws.String("missing snapshot"),
		SnapshotName:                aws.String("no-such-snap-rg"),
	})
	require.Error(t, err)
	requireFault[elasticachetypes.InvalidParameterValueException](t, err)
	requireHTTPStatus(t, err, http.StatusBadRequest)
}
