package ce

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/blackbirdworks/gopherstack/pkgs/logger"
	"github.com/blackbirdworks/gopherstack/pkgs/persistence"
)

// ceSnapshotVersion identifies the shape of [backendSnapshot]. It must be
// bumped whenever a change to backendSnapshot (or a value type held by one of
// the registered tables) would make an older snapshot unsafe to decode as the
// current shape. Restore compares this against the persisted value and
// discards (ResetAll, not a partial decode) any mismatch -- see Restore. The
// pre-Phase-3.3 snapshot format had no version field at all, so an old
// snapshot decodes with Version == 0, which is guaranteed to mismatch
// ceSnapshotVersion and is discarded the same way any other incompatible
// snapshot is.
const ceSnapshotVersion = 1

// backendSnapshot is the top-level on-disk shape for the Cost Explorer
// backend.
//
// Tables holds one JSON-encoded array per registered table name, produced by
// b.registry.SnapshotAll() -- every store.Table-backed resource field is a
// "clean" table (see store_setup.go's file doc comment), so no ephemeral
// DTO-registry is needed here. BackfillJobs has no per-entry identity to key
// a Table by, so it remains a raw field, matching its pre-refactor
// persistence. CostLedger is intentionally NOT part of this snapshot -- it
// was never persisted pre-refactor either (it is synthetic, regenerated by
// seedCostLedger) -- so Restore leaves whatever ledger is already in memory
// untouched, exactly as before. Version guards against decoding a snapshot
// from an incompatible (older or newer) build of this backend as though it
// were the current shape; see Restore.
type backendSnapshot struct {
	Tables       map[string]json.RawMessage `json:"tables"`
	AccountID    string                     `json:"accountID"`
	Region       string                     `json:"region"`
	BackfillJobs []*BackfillJob             `json:"backfillJobs"`
	AnomalyTTL   time.Duration              `json:"anomalyTTL"`
	Version      int                        `json:"version"`
}

// Snapshot serialises the backend state to JSON.
// It implements persistence.Persistable.
func (b *InMemoryBackend) Snapshot(ctx context.Context) []byte {
	b.mu.RLock("Snapshot")
	defer b.mu.RUnlock()

	tables, err := b.registry.SnapshotAll()
	if err != nil {
		logger.Load(ctx).WarnContext(ctx, "ce: snapshot table marshal failed", "error", err)

		return nil
	}

	snap := backendSnapshot{
		Version:      ceSnapshotVersion,
		Tables:       tables,
		AccountID:    b.accountID,
		Region:       b.region,
		BackfillJobs: b.backfillJobs,
		AnomalyTTL:   b.anomalyTTL,
	}

	data, err := json.Marshal(snap)
	if err != nil {
		logger.Load(ctx).WarnContext(ctx, "ce: failed to marshal snapshot", "error", err)

		return nil
	}

	return data
}

// Restore loads backend state from a JSON snapshot.
// It implements persistence.Persistable.
func (b *InMemoryBackend) Restore(ctx context.Context, data []byte) error {
	var snap backendSnapshot

	if err := persistence.UnmarshalSnapshot(ctx, "ce", data, &snap); err != nil {
		return err
	}

	b.mu.Lock("Restore")
	defer b.mu.Unlock()

	if snap.Version != ceSnapshotVersion {
		// An incompatible (older/newer/absent) snapshot version must never be
		// partially decoded as the current shape -- that risks silently
		// misinterpreting fields. Discard cleanly and start empty instead of
		// erroring, since this is an expected, recoverable condition (e.g.
		// upgrading gopherstack across a snapshot-format change), not data
		// corruption.
		logger.Load(ctx).WarnContext(ctx,
			"ce: discarding incompatible snapshot version, starting empty",
			"gotVersion", snap.Version, "wantVersion", ceSnapshotVersion)

		b.registry.ResetAll()
		b.costLedger = nil
		b.backfillJobs = nil
		b.anomalyTTL = DefaultAnomalyTTL
		b.seedCostLedger()

		return nil
	}

	if err := b.registry.RestoreAll(snap.Tables); err != nil {
		return fmt.Errorf("ce: restore snapshot tables: %w", err)
	}

	b.accountID = snap.AccountID
	b.region = snap.Region
	b.backfillJobs = snap.BackfillJobs

	// Default to DefaultAnomalyTTL when restoring from a pre-AnomalyTTL
	// snapshot to avoid evicting every anomaly on Restore (zero TTL is
	// "evict everything").
	if snap.AnomalyTTL > 0 {
		b.anomalyTTL = snap.AnomalyTTL
	} else {
		b.anomalyTTL = DefaultAnomalyTTL
	}

	return nil
}

// Snapshot implements persistence.Persistable by delegating to the backend.
func (h *Handler) Snapshot(ctx context.Context) []byte {
	return h.Backend.Snapshot(ctx)
}

// Restore implements persistence.Persistable by delegating to the backend.
func (h *Handler) Restore(ctx context.Context, data []byte) error {
	return h.Backend.Restore(ctx, data)
}

// Reset implements service.Resettable by delegating to the backend.
func (h *Handler) Reset() {
	h.Backend.Reset()
}
