package resourcegroups

import "strings"

// stackGroupTypeList holds the resource types that support CloudFormation stack-based groups
// (AWS Resource Groups user guide, "Resources that you can use with AWS Resource Groups"; column
// "CloudFormation Stack-based Groups"), one per line.
const stackGroupTypeList = "\n" +
	"AWS::ApiGateway::Account\n" +
	"AWS::ApiGateway::ApiKey\n" +
	"AWS::ApiGateway::DomainName\n" +
	"AWS::ApiGateway::RestApi\n" +
	"AWS::ApiGateway::UsagePlan\n" +
	"AWS::AppStream::Fleet\n" +
	"AWS::AppStream::ImageBuilder\n" +
	"AWS::AppStream::Stack\n" +
	"AWS::AppSync::DataSource\n" +
	"AWS::AppSync::GraphQLApi\n" +
	"AWS::BillingConductor::BillingGroup\n" +
	"AWS::BillingConductor::CustomLineItem\n" +
	"AWS::BillingConductor::PricingPlan\n" +
	"AWS::BillingConductor::PricingRule\n" +
	"AWS::Cassandra::Keyspace\n" +
	"AWS::CertificateManager::Certificate\n" +
	"AWS::CloudFormation::Stack\n" +
	"AWS::CloudFront::Distribution\n" +
	"AWS::CloudFront::StreamingDistribution\n" +
	"AWS::CloudTrail::Trail\n" +
	"AWS::CloudWatch::Alarm\n" +
	"AWS::CloudWatch::Dashboard\n" +
	"AWS::CodeArtifact::Domain\n" +
	"AWS::CodeArtifact::Repository\n" +
	"AWS::CodeDeploy::Application\n" +
	"AWS::CodeDeploy::DeploymentConfig\n" +
	"AWS::CodeGuruReviewer::RepositoryAssociation\n" +
	"AWS::CodePipeline::Pipeline\n" +
	"AWS::CodePipeline::Webhook\n" +
	"AWS::Cognito::IdentityPool\n" +
	"AWS::Cognito::UserPool\n" +
	"AWS::DMS::Endpoint\n" +
	"AWS::DMS::ReplicationInstance\n" +
	"AWS::DataBrew::Dataset\n" +
	"AWS::DataBrew::Job\n" +
	"AWS::DataBrew::Project\n" +
	"AWS::DataBrew::Recipe\n" +
	"AWS::DataBrew::Schedule\n" +
	"AWS::DataPipeline::Pipeline\n" +
	"AWS::DynamoDB::Table\n" +
	"AWS::EC2::CustomerGateway\n" +
	"AWS::EC2::DHCPOptions\n" +
	"AWS::EC2::Instance\n" +
	"AWS::EC2::InternetGateway\n" +
	"AWS::EC2::LaunchTemplate\n" +
	"AWS::EC2::NatGateway\n" +
	"AWS::EC2::NetworkAcl\n" +
	"AWS::EC2::NetworkInterface\n" +
	"AWS::EC2::PlacementGroup\n" +
	"AWS::EC2::RouteTable\n" +
	"AWS::EC2::SecurityGroup\n" +
	"AWS::EC2::Subnet\n" +
	"AWS::EC2::VPC\n" +
	"AWS::EC2::VPCPeeringConnection\n" +
	"AWS::EC2::VPNConnection\n" +
	"AWS::EC2::VPNGateway\n" +
	"AWS::EC2::Volume\n" +
	"AWS::EFS::FileSystem\n" +
	"AWS::EKS::Cluster\n" +
	"AWS::EMR::Cluster\n" +
	"AWS::EMRContainers::VirtualCluster\n" +
	"AWS::EMRServerless::Application\n" +
	"AWS::ElastiCache::CacheCluster\n" +
	"AWS::ElasticLoadBalancing::LoadBalancer\n" +
	"AWS::ElasticLoadBalancingV2::Listener\n" +
	"AWS::ElasticLoadBalancingV2::ListenerRule\n" +
	"AWS::ElasticLoadBalancingV2::LoadBalancer\n" +
	"AWS::ElasticLoadBalancingV2::TargetGroup\n" +
	"AWS::Elasticsearch::Domain\n" +
	"AWS::Events::Rule\n" +
	"AWS::Glue::Database\n" +
	"AWS::GuardDuty::Detector\n" +
	"AWS::IAM::Role\n" +
	"AWS::Inspector::AssessmentTemplate\n" +
	"AWS::IoT::TopicRule\n" +
	"AWS::IoTEvents::DetectorModel\n" +
	"AWS::IoTEvents::Input\n" +
	"AWS::IoTFleetWise::Campaign\n" +
	"AWS::IoTFleetWise::DecoderManifest\n" +
	"AWS::IoTFleetWise::Fleet\n" +
	"AWS::IoTFleetWise::ModelManifest\n" +
	"AWS::IoTFleetWise::SignalCatalog\n" +
	"AWS::IoTFleetWise::Vehicle\n" +
	"AWS::KMS::Alias\n" +
	"AWS::KMS::Key\n" +
	"AWS::Kinesis::Stream\n" +
	"AWS::KinesisAnalytics::Application\n" +
	"AWS::KinesisAnalyticsV2::Application\n" +
	"AWS::KinesisFirehose::DeliveryStream\n" +
	"AWS::Lambda::Alias\n" +
	"AWS::Lambda::EventSourceMapping\n" +
	"AWS::Lambda::Function\n" +
	"AWS::Lambda::LayerVersion\n" +
	"AWS::Lambda::Version\n" +
	"AWS::Logs::LogGroup\n" +
	"AWS::Macie::CustomDataIdentifier\n" +
	"AWS::Macie::FindingsFilter\n" +
	"AWS::OpenSearchService::Domain\n" +
	"AWS::OpsWorks::Instance\n" +
	"AWS::OpsWorks::Layer\n" +
	"AWS::OpsWorks::Stack\n" +
	"AWS::Pinpoint::App\n" +
	"AWS::Pinpoint::EmailTemplate\n" +
	"AWS::Pinpoint::PushTemplate\n" +
	"AWS::Pinpoint::SmsTemplate\n" +
	"AWS::QLDB::Ledger\n" +
	"AWS::QLDB::Stream\n" +
	"AWS::RDS::DBCluster\n" +
	"AWS::RDS::DBClusterParameterGroup\n" +
	"AWS::RDS::DBInstance\n" +
	"AWS::RDS::DBParameterGroup\n" +
	"AWS::RDS::DBSecurityGroup\n" +
	"AWS::RDS::DBSubnetGroup\n" +
	"AWS::Redshift::Cluster\n" +
	"AWS::Redshift::ClusterParameterGroup\n" +
	"AWS::Redshift::ClusterSecurityGroup\n" +
	"AWS::Redshift::ClusterSubnetGroup\n" +
	"AWS::ResourceGroups::Group\n" +
	"AWS::Route53::HealthCheck\n" +
	"AWS::Route53::HostedZone\n" +
	"AWS::S3::Bucket\n" +
	"AWS::SES::ConfigurationSet\n" +
	"AWS::SES::ContactList\n" +
	"AWS::SNS::Topic\n" +
	"AWS::SQS::Queue\n" +
	"AWS::SSM::Document\n" +
	"AWS::SSM::Parameter\n" +
	"AWS::SSM::PatchBaseline\n" +
	"AWS::SageMaker::Endpoint\n" +
	"AWS::SageMaker::EndpointConfig\n" +
	"AWS::SageMaker::Model\n" +
	"AWS::SageMaker::ModelPackageGroup\n" +
	"AWS::SageMaker::NotebookInstance\n" +
	"AWS::SageMaker::Project\n" +
	"AWS::SecretsManager::Secret\n" +
	"AWS::ServiceCatalog::CloudFormationProduct\n" +
	"AWS::ServiceCatalog::Portfolio\n" +
	"AWS::StepFunctions::Activity\n" +
	"AWS::StepFunctions::StateMachine\n" +
	"AWS::Synthetics::Canary\n" +
	"AWS::SystemsManagerSAP::Application\n" +
	"AWS::Timestream::ScheduledQuery\n" +
	"AWS::Wisdom::Assistant\n" +
	"AWS::Wisdom::AssistantAssociation\n" +
	"AWS::Wisdom::KnowledgeBase\n" +
	"AWS::WorkSpaces::Workspace\n"

func stackTypeSupported(resType string) bool {
	return strings.Contains(stackGroupTypeList, "\n"+resType+"\n")
}
