package apprunner

// Code in this file supports Phase 3.3 of the datalayer refactor: every
// map[string]*T resource field on InMemoryBackend that has a real, globally
// unique identity field (an ARN) is replaced with a *store.Table[T],
// following the pattern established by services/sesv2 / services/vpclattice
// (data-driven, direct/byName-index registration -- see pkgs/store's package
// doc for the underlying primitive).
//
// storedService, storedAutoScalingConfiguration, storedConnection,
// storedObservabilityConfiguration, storedVpcConnector, and
// storedVpcIngressConnection are all keyed by their own ARN field -- every
// ARN is generated by the backend's *ARN helpers and is globally unique (not
// merely unique within some parent) -- so all six are direct registrations.
// storedService, storedConnection, and storedVpcIngressConnection
// additionally carry a byName secondary Index, replacing the
// byName/connByName/vicByName map[string]string lookup maps the original
// code used for the create-time duplicate-name check.
//
// Left as plain maps (not store.Table-backed): asgByName and obsByName
// (map[string][]*T, order-sensitive slice-maps -- Create*/Delete* rely on
// the last element of the slice being the highest revision, and
// store.Index's remove is a swap-with-last that does not preserve insertion
// order), customDomains (map[string][]*storedCustomDomain, also an
// order-preserving append/splice with no sort), and tags
// (map[string]map[string]string, not *T). See persistence.go for how each is
// carried through Snapshot/Restore.
import (
	"github.com/blackbirdworks/gopherstack/pkgs/store"
)

func serviceKeyFn(v *storedService) string          { return v.ServiceArn }
func serviceNameIndexKeyFn(v *storedService) string { return v.ServiceName }

func asgKeyFn(v *storedAutoScalingConfiguration) string { return v.AutoScalingConfigurationArn }

func connectionKeyFn(v *storedConnection) string          { return v.ConnectionArn }
func connectionNameIndexKeyFn(v *storedConnection) string { return v.ConnectionName }

func obsKeyFn(v *storedObservabilityConfiguration) string { return v.ObservabilityConfigurationArn }

func vpcConnectorKeyFn(v *storedVpcConnector) string { return v.VpcConnectorArn }

func vicKeyFn(v *storedVpcIngressConnection) string { return v.VpcIngressConnectionArn }
func vicNameIndexKeyFn(v *storedVpcIngressConnection) string {
	return v.VpcIngressConnectionName
}

// registerAllTables registers every backend resource table (and its
// secondary indexes) exactly once. It must be called during construction
// only, immediately after b.registry is created -- store.Register panics on
// a duplicate name, so runtime resets go through b.registry.ResetAll()
// instead (see InMemoryBackend.Reset in store.go).
func registerAllTables(b *InMemoryBackend) {
	b.services = store.Register(b.registry, "services", store.New(serviceKeyFn))
	b.byName = b.services.AddIndex("byName", serviceNameIndexKeyFn)

	b.autoScalingConfigs = store.Register(b.registry, "autoScalingConfigs", store.New(asgKeyFn))

	b.connections = store.Register(b.registry, "connections", store.New(connectionKeyFn))
	b.connByName = b.connections.AddIndex("byName", connectionNameIndexKeyFn)

	b.observabilityConfigs = store.Register(b.registry, "observabilityConfigs", store.New(obsKeyFn))

	b.vpcConnectors = store.Register(b.registry, "vpcConnectors", store.New(vpcConnectorKeyFn))

	b.vpcIngressConnections = store.Register(b.registry, "vpcIngressConnections", store.New(vicKeyFn))
	b.vicByName = b.vpcIngressConnections.AddIndex("byName", vicNameIndexKeyFn)
}
