package appconfig

import (
	"crypto/rand"
	"encoding/binary"
	"fmt"
	"maps"
	"slices"
	"sort"
	"strconv"
	"time"

	"github.com/google/uuid"

	"github.com/blackbirdworks/gopherstack/pkgs/arn"
	"github.com/blackbirdworks/gopherstack/pkgs/lockmetrics"
	"github.com/blackbirdworks/gopherstack/pkgs/page"
	"github.com/blackbirdworks/gopherstack/pkgs/store"
)

const (
	contentTypeOctetStream = "application/octet-stream"
)

const appConfigIDChars = "abcdefghijklmnopqrstuvwxyz0123456789"

// newResourceID generates a cryptographically random 7-character lowercase alphanumeric ID,
// matching the format of real AWS AppConfig resource IDs (4-7 chars required by the provider).
func newResourceID() string {
	const length = 7
	b := make([]byte, length)
	charCount := uint64(len(appConfigIDChars))

	for i := range b {
		var v [8]byte
		_, _ = rand.Read(v[:])
		b[i] = appConfigIDChars[binary.BigEndian.Uint64(v[:])%charCount]
	}

	return string(b)
}

// InMemoryBackend implements StorageBackend for AppConfig using a
// store.Registry of store.Table-backed resource collections.
//
// applications, deploymentStrategies, extensions, and extensionAssociations
// are flat, top-level collections keyed by their own real identity field
// (ID), matching the services/sesv2 / services/dax / services/datasync
// clean-direct-register template.
//
// environments and configProfiles were previously nested two levels deep
// (outer key = applicationID; inner key = the resource's own ID). Both
// Environment.ID and ConfigurationProfile.ID are generated by the same
// globally-random newResourceID() every other resource in this backend
// uses (not parent-scoped), so -- per the opsworks/datasync "globally-unique
// ID, bare-ID lookups" precedent -- each registers DIRECTLY on its own ID,
// with a companion byApp *store.Index (grouping entries by ApplicationID)
// added additively for the per-application List/cascade-delete operations
// the nested maps used to answer directly. A second byAppName *store.Index
// (composite "applicationID|name" key) replaces the old
// environmentsByName/configProfilesByName nested reverse maps for the
// per-application name-uniqueness checks.
//
// hostedConfigVersions and deployments were previously nested three levels
// deep (outer key = applicationID; middle key = profileID/environmentID;
// inner key = an int32 VersionNumber/DeploymentNumber). Unlike the resource
// IDs above, VersionNumber and DeploymentNumber are per-parent counters --
// unique only within their owning profile/environment, not globally -- so
// per the composite-key rule each flattens to one *store.Table keyed by a
// composite "applicationID|parentID|number" string (see hcvKey/deploymentKey
// below), with companion *store.Index values grouping entries by profile/env
// (List operations) and by application (DeleteApplication's cascade delete).
// hostedConfigVersions additionally carries a byLabel *store.Index replacing
// the old versionLabelIndex raw map: VersionLabel uniqueness is answered by
// the index instead of a parallel set.
//
// Left as plain maps (not store.Table-backed):
//   - tags (map[string]map[string]string): its values are plain string
//     maps, not *T, so it does not fit store.Table's keyed-by-identity-value
//     shape.
//   - versionCounters, deploymentCounters (map[string]map[string]int32):
//     their values are int32, not *T. Both must survive Snapshot/Restore
//     (see persistence.go) since they are the source of truth for the next
//     version/deployment number -- reconstructing them from the tables'
//     current contents would under-count after any delete.
//   - accountSettings is a single struct, not a map at all.
type InMemoryBackend struct {
	registry *store.Registry

	applications       *store.Table[Application]
	applicationsByName *store.Index[Application]

	environments          *store.Table[Environment]
	environmentsByApp     *store.Index[Environment]
	environmentsByAppName *store.Index[Environment]

	configProfiles          *store.Table[ConfigurationProfile]
	configProfilesByApp     *store.Index[ConfigurationProfile]
	configProfilesByAppName *store.Index[ConfigurationProfile]

	hostedConfigVersions          *store.Table[HostedConfigurationVersion]
	hostedConfigVersionsByProfile *store.Index[HostedConfigurationVersion]
	hostedConfigVersionsByApp     *store.Index[HostedConfigurationVersion]
	hostedConfigVersionsByLabel   *store.Index[HostedConfigurationVersion]

	deploymentStrategies       *store.Table[DeploymentStrategy]
	deploymentStrategiesByName *store.Index[DeploymentStrategy]

	deployments      *store.Table[Deployment]
	deploymentsByEnv *store.Index[Deployment]
	deploymentsByApp *store.Index[Deployment]

	extensions       *store.Table[Extension]
	extensionsByName *store.Index[Extension]

	extensionAssociations *store.Table[ExtensionAssociation]

	tags               map[string]map[string]string
	versionCounters    map[string]map[string]int32
	deploymentCounters map[string]map[string]int32

	mu *lockmetrics.RWMutex

	accountSettings AccountSettings

	paginationSecret string
	accountID        string
	region           string
}

// NewInMemoryBackend creates a new InMemoryBackend for AppConfig.
func NewInMemoryBackend(accountID, region string) *InMemoryBackend {
	b := &InMemoryBackend{
		tags:               make(map[string]map[string]string),
		versionCounters:    make(map[string]map[string]int32),
		deploymentCounters: make(map[string]map[string]int32),
		registry:           store.NewRegistry(),
		mu:                 lockmetrics.New("appconfig"),
		paginationSecret:   uuid.NewString(),
		accountID:          accountID,
		region:             region,
	}
	registerAllTables(b)

	return b
}

// PaginationSecret returns the HMAC secret for pagination tokens.
func (b *InMemoryBackend) PaginationSecret() string { return b.paginationSecret }

// appconfigARN builds an AppConfig resource ARN for tag lookup/cleanup.
func (b *InMemoryBackend) appconfigARN(resourcePath string) string {
	return arn.Build("appconfig", b.region, b.accountID, resourcePath)
}

// ---- composite keys ----
//
// environments and configProfiles register directly on their own ID (see
// the InMemoryBackend doc comment), so appNameKey is used only to build the
// byAppName index key for per-application name-uniqueness checks.
// hostedConfigVersions and deployments register on a composite key because
// VersionNumber/DeploymentNumber are unique only within their parent.
func appNameKey(applicationID, name string) string { return applicationID + "|" + name }

func appEnvKey(applicationID, environmentID string) string {
	return applicationID + "|" + environmentID
}

func appProfileKey(applicationID, profileID string) string {
	return applicationID + "|" + profileID
}

func hcvKey(applicationID, profileID string, versionNumber int32) string {
	return appProfileKey(applicationID, profileID) + "|" + strconv.FormatInt(int64(versionNumber), 10)
}

func hcvLabelKey(applicationID, profileID, label string) string {
	return appProfileKey(applicationID, profileID) + "|" + label
}

func deploymentKey(applicationID, environmentID string, deploymentNumber int32) string {
	return appEnvKey(applicationID, environmentID) + "|" + strconv.FormatInt(int64(deploymentNumber), 10)
}

// CreateApplication creates a new AppConfig application.
func (b *InMemoryBackend) CreateApplication(name, description string) (*Application, error) {
	b.mu.Lock("CreateApplication")
	defer b.mu.Unlock()

	if name == "" {
		return nil, fmt.Errorf("%w: Name is required", ErrBadRequest)
	}

	if len(b.applicationsByName.Get(name)) > 0 {
		return nil, fmt.Errorf("%w: application with name %q already exists", ErrConflict, name)
	}

	now := time.Now()
	app := &Application{
		ID:          newResourceID(),
		Name:        name,
		Description: description,
		CreatedAt:   now,
		UpdatedAt:   now,
	}
	b.applications.Put(app)
	cp := *app

	return &cp, nil
}

// GetApplication retrieves an application by ID.
func (b *InMemoryBackend) GetApplication(applicationID string) (*Application, error) {
	b.mu.RLock("GetApplication")
	defer b.mu.RUnlock()

	app, ok := b.applications.Get(applicationID)
	if !ok {
		return nil, fmt.Errorf("%w: application %s", ErrApplicationNotFound, applicationID)
	}

	cp := *app

	return &cp, nil
}

// ListApplications returns paginated applications.
func (b *InMemoryBackend) ListApplications(
	nextToken string,
	maxResults int,
) ([]Application, string) {
	b.mu.RLock("ListApplications")
	defer b.mu.RUnlock()

	all := b.applications.All()
	out := make([]Application, 0, len(all))
	for _, app := range all {
		out = append(out, *app)
	}

	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })

	page, token := appConfigPaginate(out, nextToken, b.paginationSecret, maxResults)

	return page, token
}

// UpdateApplication updates an application's name and description. A nil
// name/description means the request omitted that field, and AWS AppConfig
// leaves an omitted field unchanged rather than clearing it (only an
// explicit, present value -- including "" -- overwrites).
func (b *InMemoryBackend) UpdateApplication(
	applicationID string, name, description *string,
) (*Application, error) {
	b.mu.Lock("UpdateApplication")
	defer b.mu.Unlock()

	existing, ok := b.applications.Get(applicationID)
	if !ok {
		return nil, fmt.Errorf("%w: application %s", ErrApplicationNotFound, applicationID)
	}

	updated := *existing
	if name != nil && *name != "" {
		updated.Name = *name
	}

	if description != nil {
		updated.Description = *description
	}

	updated.UpdatedAt = time.Now()
	b.applications.Put(&updated)
	cp := updated

	return &cp, nil
}

// DeleteApplication deletes an application by ID.
func (b *InMemoryBackend) DeleteApplication(applicationID string) error {
	b.mu.Lock("DeleteApplication")
	defer b.mu.Unlock()

	if !b.applications.Has(applicationID) {
		return fmt.Errorf("%w: application %s", ErrApplicationNotFound, applicationID)
	}

	// Clean up tags for the application and all its child resources.
	delete(b.tags, b.appconfigARN("application/"+applicationID))

	for _, env := range slices.Clone(b.environmentsByApp.Get(applicationID)) {
		delete(b.tags, b.appconfigARN("application/"+applicationID+"/environment/"+env.ID))
		b.environments.Delete(env.ID)
	}

	for _, profile := range slices.Clone(b.configProfilesByApp.Get(applicationID)) {
		delete(
			b.tags,
			b.appconfigARN("application/"+applicationID+"/configurationprofile/"+profile.ID),
		)
		b.configProfiles.Delete(profile.ID)
	}

	for _, v := range slices.Clone(b.hostedConfigVersionsByApp.Get(applicationID)) {
		b.hostedConfigVersions.Delete(hostedConfigVersionKeyFn(v))
	}

	for _, d := range slices.Clone(b.deploymentsByApp.Get(applicationID)) {
		b.deployments.Delete(deploymentKeyFn(d))
	}

	b.applications.Delete(applicationID)
	delete(b.versionCounters, applicationID)
	delete(b.deploymentCounters, applicationID)

	return nil
}

// CreateEnvironment creates a new environment within an application.
func (b *InMemoryBackend) CreateEnvironment(
	applicationID, name, description string,
	monitors []Monitor,
) (*Environment, error) {
	b.mu.Lock("CreateEnvironment")
	defer b.mu.Unlock()

	if name == "" {
		return nil, fmt.Errorf("%w: Name is required", ErrBadRequest)
	}

	if !b.applications.Has(applicationID) {
		return nil, fmt.Errorf("%w: application %s", ErrApplicationNotFound, applicationID)
	}

	if len(b.environmentsByAppName.Get(appNameKey(applicationID, name))) > 0 {
		return nil, fmt.Errorf(
			"%w: environment with name %q already exists in application %s",
			ErrConflict,
			name,
			applicationID,
		)
	}

	now := time.Now()
	env := &Environment{
		ID:            newResourceID(),
		ApplicationID: applicationID,
		Name:          name,
		Description:   description,
		State:         "READY_FOR_DEPLOYMENT",
		Monitors:      monitors,
		CreatedAt:     now,
		UpdatedAt:     now,
	}
	b.environments.Put(env)
	cp := *env

	return &cp, nil
}

// GetEnvironment retrieves an environment by application and environment ID.
func (b *InMemoryBackend) GetEnvironment(
	applicationID, environmentID string,
) (*Environment, error) {
	b.mu.RLock("GetEnvironment")
	defer b.mu.RUnlock()

	env, ok := b.environments.Get(environmentID)
	if !ok || env.ApplicationID != applicationID {
		return nil, fmt.Errorf("%w: environment %s", ErrEnvironmentNotFound, environmentID)
	}

	cp := *env

	return &cp, nil
}

// ListEnvironments returns paginated environments for an application.
func (b *InMemoryBackend) ListEnvironments(
	applicationID, nextToken string,
	maxResults int,
) ([]Environment, string, error) {
	b.mu.RLock("ListEnvironments")
	defer b.mu.RUnlock()

	if !b.applications.Has(applicationID) {
		return nil, "", fmt.Errorf("%w: application %s", ErrApplicationNotFound, applicationID)
	}

	envs := b.environmentsByApp.Get(applicationID)
	out := make([]Environment, 0, len(envs))

	for _, e := range envs {
		out = append(out, *e)
	}

	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })

	page, token := appConfigPaginate(out, nextToken, b.paginationSecret, maxResults)

	return page, token, nil
}

// UpdateEnvironment updates an environment's name, description, and
// monitors. A nil name/description/monitors means the request omitted that
// field, and AWS AppConfig leaves an omitted field unchanged rather than
// clearing it.
func (b *InMemoryBackend) UpdateEnvironment(
	applicationID, environmentID string,
	name, description *string,
	monitors *[]Monitor,
) (*Environment, error) {
	b.mu.Lock("UpdateEnvironment")
	defer b.mu.Unlock()

	existing, ok := b.environments.Get(environmentID)
	if !ok || existing.ApplicationID != applicationID {
		return nil, fmt.Errorf("%w: environment %s", ErrEnvironmentNotFound, environmentID)
	}

	updated := *existing
	if name != nil && *name != "" {
		updated.Name = *name
	}

	if description != nil {
		updated.Description = *description
	}

	if monitors != nil {
		updated.Monitors = *monitors
	}

	updated.UpdatedAt = time.Now()
	b.environments.Put(&updated)
	cp := updated

	return &cp, nil
}

// DeleteEnvironment deletes an environment.
func (b *InMemoryBackend) DeleteEnvironment(applicationID, environmentID string) error {
	b.mu.Lock("DeleteEnvironment")
	defer b.mu.Unlock()

	env, ok := b.environments.Get(environmentID)
	if !ok || env.ApplicationID != applicationID {
		return fmt.Errorf("%w: environment %s", ErrEnvironmentNotFound, environmentID)
	}

	b.environments.Delete(environmentID)
	delete(b.tags, b.appconfigARN("application/"+applicationID+"/environment/"+environmentID))

	return nil
}

// CreateConfigurationProfile creates a new configuration profile.
func (b *InMemoryBackend) CreateConfigurationProfile(
	applicationID, name, description, locationURI, profileType, retrievalRoleArn string,
	validators []Validator,
) (*ConfigurationProfile, error) {
	b.mu.Lock("CreateConfigurationProfile")
	defer b.mu.Unlock()

	if name == "" {
		return nil, fmt.Errorf("%w: Name is required", ErrBadRequest)
	}

	if locationURI == "" {
		return nil, fmt.Errorf("%w: LocationUri is required", ErrBadRequest)
	}

	if !b.applications.Has(applicationID) {
		return nil, fmt.Errorf("%w: application %s", ErrApplicationNotFound, applicationID)
	}

	if len(b.configProfilesByAppName.Get(appNameKey(applicationID, name))) > 0 {
		return nil, fmt.Errorf(
			"%w: configuration profile with name %q already exists in application %s",
			ErrConflict,
			name,
			applicationID,
		)
	}

	profile := &ConfigurationProfile{
		ID:               newResourceID(),
		ApplicationID:    applicationID,
		Name:             name,
		Description:      description,
		LocationURI:      locationURI,
		Type:             profileType,
		RetrievalRoleArn: retrievalRoleArn,
		Validators:       validators,
	}
	b.configProfiles.Put(profile)
	cp := *profile

	return &cp, nil
}

// GetConfigurationProfile retrieves a configuration profile.
func (b *InMemoryBackend) GetConfigurationProfile(
	applicationID, profileID string,
) (*ConfigurationProfile, error) {
	b.mu.RLock("GetConfigurationProfile")
	defer b.mu.RUnlock()

	profile, ok := b.configProfiles.Get(profileID)
	if !ok || profile.ApplicationID != applicationID {
		return nil, fmt.Errorf(
			"%w: configuration profile %s",
			ErrConfigurationProfileNotFound,
			profileID,
		)
	}

	cp := *profile

	return &cp, nil
}

// ListConfigurationProfiles returns paginated profiles for an application.
func (b *InMemoryBackend) ListConfigurationProfiles(
	applicationID, nextToken string,
	maxResults int,
) ([]ConfigurationProfile, string, error) {
	b.mu.RLock("ListConfigurationProfiles")
	defer b.mu.RUnlock()

	if !b.applications.Has(applicationID) {
		return nil, "", fmt.Errorf("%w: application %s", ErrApplicationNotFound, applicationID)
	}

	profiles := b.configProfilesByApp.Get(applicationID)
	out := make([]ConfigurationProfile, 0, len(profiles))

	for _, p := range profiles {
		out = append(out, *p)
	}

	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })

	page, token := appConfigPaginate(out, nextToken, b.paginationSecret, maxResults)

	return page, token, nil
}

// UpdateConfigurationProfile updates a configuration profile. A nil
// name/description/retrievalRoleArn/validators means the request omitted
// that field, and AWS AppConfig leaves an omitted field unchanged rather
// than clearing it.
func (b *InMemoryBackend) UpdateConfigurationProfile(
	applicationID, profileID string,
	name, description, retrievalRoleArn *string,
	validators *[]Validator,
) (*ConfigurationProfile, error) {
	b.mu.Lock("UpdateConfigurationProfile")
	defer b.mu.Unlock()

	existing, ok := b.configProfiles.Get(profileID)
	if !ok || existing.ApplicationID != applicationID {
		return nil, fmt.Errorf(
			"%w: configuration profile %s",
			ErrConfigurationProfileNotFound,
			profileID,
		)
	}

	updated := *existing
	if name != nil && *name != "" {
		updated.Name = *name
	}

	if description != nil {
		updated.Description = *description
	}

	if retrievalRoleArn != nil {
		updated.RetrievalRoleArn = *retrievalRoleArn
	}

	if validators != nil {
		updated.Validators = *validators
	}

	b.configProfiles.Put(&updated)
	cp := updated

	return &cp, nil
}

// DeleteConfigurationProfile deletes a configuration profile.
func (b *InMemoryBackend) DeleteConfigurationProfile(applicationID, profileID string) error {
	b.mu.Lock("DeleteConfigurationProfile")
	defer b.mu.Unlock()

	profile, ok := b.configProfiles.Get(profileID)
	if !ok || profile.ApplicationID != applicationID {
		return fmt.Errorf(
			"%w: configuration profile %s",
			ErrConfigurationProfileNotFound,
			profileID,
		)
	}

	b.configProfiles.Delete(profileID)
	delete(b.tags, b.appconfigARN("application/"+applicationID+"/configurationprofile/"+profileID))

	return nil
}

const maxHostedConfigSizeBytes = 1024 * 1024 // 1 MiB, matching AWS limit

// CreateHostedConfigurationVersion creates a hosted configuration version.
func (b *InMemoryBackend) CreateHostedConfigurationVersion(
	applicationID, profileID, contentType, description, versionLabel string,
	content []byte,
) (*HostedConfigurationVersion, error) {
	b.mu.Lock("CreateHostedConfigurationVersion")
	defer b.mu.Unlock()

	if len(content) > maxHostedConfigSizeBytes {
		return nil, fmt.Errorf(
			"%w: content exceeds maximum size of %d bytes",
			ErrPayloadTooLarge,
			maxHostedConfigSizeBytes,
		)
	}

	if !b.applications.Has(applicationID) {
		return nil, fmt.Errorf("%w: application %s", ErrApplicationNotFound, applicationID)
	}

	profile, ok := b.configProfiles.Get(profileID)
	if !ok || profile.ApplicationID != applicationID {
		return nil, fmt.Errorf(
			"%w: configuration profile %s",
			ErrConfigurationProfileNotFound,
			profileID,
		)
	}

	// VersionLabel must be unique across versions for this profile.
	if versionLabel != "" &&
		len(b.hostedConfigVersionsByLabel.Get(hcvLabelKey(applicationID, profileID, versionLabel))) > 0 {
		return nil, fmt.Errorf(
			"%w: version label %q already exists for profile %s",
			ErrConflict,
			versionLabel,
			profileID,
		)
	}

	if b.versionCounters[applicationID] == nil {
		b.versionCounters[applicationID] = make(map[string]int32)
	}

	b.versionCounters[applicationID][profileID]++
	versionNumber := b.versionCounters[applicationID][profileID]

	v := &HostedConfigurationVersion{
		ApplicationID:          applicationID,
		ConfigurationProfileID: profileID,
		ContentType:            contentType,
		Description:            description,
		VersionLabel:           versionLabel,
		Content:                content,
		VersionNumber:          versionNumber,
		CreatedAt:              time.Now(),
	}
	b.hostedConfigVersions.Put(v)
	cp := *v

	return &cp, nil
}

// GetHostedConfigurationVersion retrieves a hosted configuration version.
func (b *InMemoryBackend) GetHostedConfigurationVersion(
	applicationID, profileID string,
	versionNumber int32,
) (*HostedConfigurationVersion, error) {
	b.mu.RLock("GetHostedConfigurationVersion")
	defer b.mu.RUnlock()

	v, ok := b.hostedConfigVersions.Get(hcvKey(applicationID, profileID, versionNumber))
	if !ok {
		return nil, fmt.Errorf("%w: version %d", ErrHostedConfigVersionNotFound, versionNumber)
	}

	cp := *v

	return &cp, nil
}

// ListHostedConfigurationVersions returns paginated versions for a profile, optionally filtered by versionLabel.
func (b *InMemoryBackend) ListHostedConfigurationVersions(
	applicationID, profileID, nextToken, versionLabel string, maxResults int,
) ([]HostedConfigurationVersion, string, error) {
	b.mu.RLock("ListHostedConfigurationVersions")
	defer b.mu.RUnlock()

	if !b.applications.Has(applicationID) {
		return nil, "", fmt.Errorf("%w: application %s", ErrApplicationNotFound, applicationID)
	}

	if profile, ok := b.configProfiles.Get(profileID); !ok || profile.ApplicationID != applicationID {
		return nil, "", fmt.Errorf(
			"%w: configuration profile %s",
			ErrConfigurationProfileNotFound,
			profileID,
		)
	}

	profileVersions := b.hostedConfigVersionsByProfile.Get(appProfileKey(applicationID, profileID))

	out := make([]HostedConfigurationVersion, 0, len(profileVersions))
	for _, v := range profileVersions {
		if versionLabel != "" && v.VersionLabel != versionLabel {
			continue
		}

		out = append(out, *v)
	}

	sort.Slice(out, func(i, j int) bool { return out[i].VersionNumber < out[j].VersionNumber })

	page, token := appConfigPaginate(out, nextToken, b.paginationSecret, maxResults)

	return page, token, nil
}

// DeleteHostedConfigurationVersion deletes a hosted configuration version.
func (b *InMemoryBackend) DeleteHostedConfigurationVersion(
	applicationID, profileID string,
	versionNumber int32,
) error {
	b.mu.Lock("DeleteHostedConfigurationVersion")
	defer b.mu.Unlock()

	key := hcvKey(applicationID, profileID, versionNumber)
	if !b.hostedConfigVersions.Has(key) {
		return fmt.Errorf("%w: version %d", ErrHostedConfigVersionNotFound, versionNumber)
	}

	b.hostedConfigVersions.Delete(key)

	return nil
}

// CreateDeploymentStrategy creates a new deployment strategy.
func (b *InMemoryBackend) CreateDeploymentStrategy(
	name, description string,
	deploymentDuration, bakeTime int32,
	growthFactor float32,
	growthType, replicateTo string,
) (*DeploymentStrategy, error) {
	b.mu.Lock("CreateDeploymentStrategy")
	defer b.mu.Unlock()

	if name == "" {
		return nil, fmt.Errorf("%w: Name is required", ErrBadRequest)
	}

	if len(b.deploymentStrategiesByName.Get(name)) > 0 {
		return nil, fmt.Errorf(
			"%w: deployment strategy with name %q already exists",
			ErrConflict,
			name,
		)
	}

	now := time.Now()
	strategy := &DeploymentStrategy{
		ID:                          newResourceID(),
		Name:                        name,
		Description:                 description,
		DeploymentDurationInMinutes: deploymentDuration,
		FinalBakeTimeInMinutes:      bakeTime,
		GrowthFactor:                growthFactor,
		GrowthType:                  growthType,
		ReplicateTo:                 replicateTo,
		CreatedAt:                   now,
		UpdatedAt:                   now,
	}
	b.deploymentStrategies.Put(strategy)
	cp := *strategy

	return &cp, nil
}

// GetDeploymentStrategy retrieves a deployment strategy by ID.
func (b *InMemoryBackend) GetDeploymentStrategy(strategyID string) (*DeploymentStrategy, error) {
	b.mu.RLock("GetDeploymentStrategy")
	defer b.mu.RUnlock()

	strategy, ok := b.deploymentStrategies.Get(strategyID)
	if !ok {
		return nil, fmt.Errorf(
			"%w: deployment strategy %s",
			ErrDeploymentStrategyNotFound,
			strategyID,
		)
	}

	cp := *strategy

	return &cp, nil
}

// ListDeploymentStrategies returns paginated deployment strategies.
func (b *InMemoryBackend) ListDeploymentStrategies(
	nextToken string,
	maxResults int,
) ([]DeploymentStrategy, string) {
	b.mu.RLock("ListDeploymentStrategies")
	defer b.mu.RUnlock()

	all := b.deploymentStrategies.All()
	out := make([]DeploymentStrategy, 0, len(all))
	for _, s := range all {
		out = append(out, *s)
	}

	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })

	page, token := appConfigPaginate(out, nextToken, b.paginationSecret, maxResults)

	return page, token
}

// UpdateDeploymentStrategy updates a deployment strategy. A nil description
// means the request omitted that field, and AWS AppConfig leaves an omitted
// field unchanged rather than clearing it.
func (b *InMemoryBackend) UpdateDeploymentStrategy(
	strategyID, name string,
	description *string,
	deploymentDuration, bakeTime int32,
	growthFactor float32,
) (*DeploymentStrategy, error) {
	b.mu.Lock("UpdateDeploymentStrategy")
	defer b.mu.Unlock()

	existing, ok := b.deploymentStrategies.Get(strategyID)
	if !ok {
		return nil, fmt.Errorf(
			"%w: deployment strategy %s",
			ErrDeploymentStrategyNotFound,
			strategyID,
		)
	}

	updated := *existing
	if name != "" {
		updated.Name = name
	}

	if description != nil {
		updated.Description = *description
	}

	updated.DeploymentDurationInMinutes = deploymentDuration
	updated.FinalBakeTimeInMinutes = bakeTime
	updated.GrowthFactor = growthFactor
	updated.UpdatedAt = time.Now()
	b.deploymentStrategies.Put(&updated)
	cp := updated

	return &cp, nil
}

// DeleteDeploymentStrategy deletes a deployment strategy.
func (b *InMemoryBackend) DeleteDeploymentStrategy(strategyID string) error {
	b.mu.Lock("DeleteDeploymentStrategy")
	defer b.mu.Unlock()

	if !b.deploymentStrategies.Has(strategyID) {
		return fmt.Errorf("%w: deployment strategy %s", ErrDeploymentStrategyNotFound, strategyID)
	}

	b.deploymentStrategies.Delete(strategyID)
	delete(b.tags, b.appconfigARN("deploymentstrategy/"+strategyID))

	return nil
}

// StartDeployment starts a deployment.
func (b *InMemoryBackend) StartDeployment(
	applicationID, environmentID, configProfileID, strategyID, configVersion, description string,
) (*Deployment, error) {
	b.mu.Lock("StartDeployment")
	defer b.mu.Unlock()

	if !b.applications.Has(applicationID) {
		return nil, fmt.Errorf("%w: application %s", ErrApplicationNotFound, applicationID)
	}

	env, ok := b.environments.Get(environmentID)
	if !ok || env.ApplicationID != applicationID {
		return nil, fmt.Errorf("%w: environment %s", ErrEnvironmentNotFound, environmentID)
	}

	profile, ok := b.configProfiles.Get(configProfileID)
	if !ok || profile.ApplicationID != applicationID {
		return nil, fmt.Errorf(
			"%w: configuration profile %s",
			ErrConfigurationProfileNotFound,
			configProfileID,
		)
	}

	if !b.deploymentStrategies.Has(strategyID) {
		return nil, fmt.Errorf(
			"%w: deployment strategy %s",
			ErrDeploymentStrategyNotFound,
			strategyID,
		)
	}

	if b.deploymentCounters[applicationID] == nil {
		b.deploymentCounters[applicationID] = make(map[string]int32)
	}

	b.deploymentCounters[applicationID][environmentID]++
	deploymentNumber := b.deploymentCounters[applicationID][environmentID]

	now := time.Now()
	deployment := &Deployment{
		ApplicationID:          applicationID,
		EnvironmentID:          environmentID,
		ConfigurationProfileID: configProfileID,
		DeploymentStrategyID:   strategyID,
		ConfigurationVersion:   configVersion,
		Description:            description,
		State:                  "COMPLETE",
		TriggeredBy:            "USER",
		PercentageComplete:     100.0, //nolint:mnd // 100% complete
		DeploymentNumber:       deploymentNumber,
		StartedAt:              now,
		CompletedAt:            now,
	}
	b.deployments.Put(deployment)
	cp := *deployment

	return &cp, nil
}

// GetDeployment retrieves a deployment.
func (b *InMemoryBackend) GetDeployment(
	applicationID, environmentID string,
	deploymentNumber int32,
) (*Deployment, error) {
	b.mu.RLock("GetDeployment")
	defer b.mu.RUnlock()

	d, ok := b.deployments.Get(deploymentKey(applicationID, environmentID, deploymentNumber))
	if !ok {
		return nil, fmt.Errorf("%w: deployment %d", ErrDeploymentNotFound, deploymentNumber)
	}

	cp := *d

	return &cp, nil
}

// ListDeployments returns paginated deployments for an environment.
func (b *InMemoryBackend) ListDeployments(
	applicationID, environmentID, nextToken string,
	maxResults int,
) ([]Deployment, string, error) {
	b.mu.RLock("ListDeployments")
	defer b.mu.RUnlock()

	// Single lookup — returns a clear error for app-not-found or env-not-found.
	env, ok := b.environments.Get(environmentID)
	if !ok || env.ApplicationID != applicationID {
		if !b.applications.Has(applicationID) {
			return nil, "", fmt.Errorf("%w: application %s", ErrApplicationNotFound, applicationID)
		}

		return nil, "", fmt.Errorf("%w: environment %s", ErrEnvironmentNotFound, environmentID)
	}

	deploys := b.deploymentsByEnv.Get(appEnvKey(applicationID, environmentID))

	out := make([]Deployment, 0, len(deploys))
	for _, d := range deploys {
		out = append(out, *d)
	}

	sort.Slice(
		out,
		func(i, j int) bool { return out[i].DeploymentNumber < out[j].DeploymentNumber },
	)

	page, token := appConfigPaginate(out, nextToken, b.paginationSecret, maxResults)

	return page, token, nil
}

// stoppableDeploymentStates are the states from which a deployment can be stopped.
var stoppableDeploymentStates = map[string]bool{ //nolint:gochecknoglobals // compile-time constant map
	"BAKING":     true,
	"DEPLOYING":  true,
	"VALIDATING": true,
}

// StopDeployment stops an in-progress deployment.
func (b *InMemoryBackend) StopDeployment(
	applicationID, environmentID string,
	deploymentNumber int32,
) error {
	b.mu.Lock("StopDeployment")
	defer b.mu.Unlock()

	key := deploymentKey(applicationID, environmentID, deploymentNumber)

	d, ok := b.deployments.Get(key)
	if !ok {
		return fmt.Errorf("%w: deployment %d", ErrDeploymentNotFound, deploymentNumber)
	}

	// Allow stopping from any non-terminal state to keep in-memory stub pragmatic.
	// (Real deployments complete instantly here so we still accept the request.)
	if d.State != "COMPLETE" && d.State != "ROLLED_BACK" && !stoppableDeploymentStates[d.State] {
		return fmt.Errorf("%w: cannot stop deployment in state %s", ErrBadRequest, d.State)
	}

	updated := *d
	updated.State = "ROLLED_BACK"
	updated.CompletedAt = time.Now()
	b.deployments.Put(&updated)

	return nil
}

// ListTagsForResource returns the tags for the given resource ARN.
func (b *InMemoryBackend) ListTagsForResource(resourceArn string) (map[string]string, error) {
	b.mu.RLock("ListTagsForResource")
	defer b.mu.RUnlock()

	t := b.tags[resourceArn]
	result := make(map[string]string, len(t))
	maps.Copy(result, t)

	return result, nil
}

// TagResource adds or replaces tags on the given resource ARN.
func (b *InMemoryBackend) TagResource(resourceArn string, tags map[string]string) error {
	b.mu.Lock("TagResource")
	defer b.mu.Unlock()

	if b.tags[resourceArn] == nil {
		b.tags[resourceArn] = make(map[string]string)
	}

	maps.Copy(b.tags[resourceArn], tags)

	return nil
}

// UntagResource removes the specified tag keys from the given resource ARN.
func (b *InMemoryBackend) UntagResource(resourceArn string, tagKeys []string) error {
	b.mu.Lock("UntagResource")
	defer b.mu.Unlock()

	t := b.tags[resourceArn]
	if t == nil {
		return nil
	}

	for _, k := range tagKeys {
		delete(t, k)
	}

	return nil
}

// CreateExtension creates a new AppConfig extension.
func (b *InMemoryBackend) CreateExtension(
	name, description string,
	actions map[string][]ExtensionAction,
	parameters map[string]ExtensionParameter,
) (*Extension, error) {
	b.mu.Lock("CreateExtension")
	defer b.mu.Unlock()

	if name == "" {
		return nil, fmt.Errorf("%w: Name is required", ErrBadRequest)
	}

	// Enforce name uniqueness.
	if len(b.extensionsByName.Get(name)) > 0 {
		return nil, fmt.Errorf(
			"%w: extension with name %s already exists",
			ErrExtensionAlreadyExists,
			name,
		)
	}

	id := newResourceID()
	ext := &Extension{
		ID:            id,
		Name:          name,
		Description:   description,
		Arn:           b.appconfigARN("extension/" + id),
		VersionNumber: 1,
		Actions:       actions,
		Parameters:    parameters,
	}
	b.extensions.Put(ext)
	cp := *ext

	return &cp, nil
}

// resolveExtension finds an extension by ID or name.
func (b *InMemoryBackend) resolveExtension(identifier string) *Extension {
	if ext, ok := b.extensions.Get(identifier); ok {
		return ext
	}

	if matches := b.extensionsByName.Get(identifier); len(matches) > 0 {
		return matches[0]
	}

	return nil
}

// GetExtension retrieves an extension by identifier (ID or name).
func (b *InMemoryBackend) GetExtension(extensionIdentifier string) (*Extension, error) {
	b.mu.RLock("GetExtension")
	defer b.mu.RUnlock()

	ext := b.resolveExtension(extensionIdentifier)
	if ext == nil {
		return nil, fmt.Errorf("%w: extension %s", ErrExtensionNotFound, extensionIdentifier)
	}

	cp := *ext

	return &cp, nil
}

// ListExtensions returns paginated extensions, optionally filtered by name and/or version number.
func (b *InMemoryBackend) ListExtensions(
	nextToken string,
	maxResults int,
	nameFilter string,
	versionNumber int32,
) ([]Extension, string) {
	b.mu.RLock("ListExtensions")
	defer b.mu.RUnlock()

	all := b.extensions.All()
	out := make([]Extension, 0, len(all))

	for _, ext := range all {
		if nameFilter != "" && ext.Name != nameFilter {
			continue
		}

		if versionNumber > 0 && ext.VersionNumber != versionNumber {
			continue
		}

		out = append(out, *ext)
	}

	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })

	page, token := appConfigPaginate(out, nextToken, b.paginationSecret, maxResults)

	return page, token
}

// UpdateExtension updates an extension's description, actions, and
// parameters. A nil description means the request omitted that field, and
// AWS AppConfig leaves an omitted field unchanged rather than clearing it.
func (b *InMemoryBackend) UpdateExtension(
	extensionIdentifier string,
	description *string,
	actions map[string][]ExtensionAction,
	parameters map[string]ExtensionParameter,
) (*Extension, error) {
	b.mu.Lock("UpdateExtension")
	defer b.mu.Unlock()

	ext := b.resolveExtension(extensionIdentifier)
	if ext == nil {
		return nil, fmt.Errorf("%w: extension %s", ErrExtensionNotFound, extensionIdentifier)
	}

	updated := *ext
	if description != nil {
		updated.Description = *description
	}

	if actions != nil {
		updated.Actions = actions
	}

	if parameters != nil {
		updated.Parameters = parameters
	}

	updated.VersionNumber++
	b.extensions.Put(&updated)
	cp := updated

	return &cp, nil
}

// DeleteExtension deletes an extension by identifier (ID or name).
func (b *InMemoryBackend) DeleteExtension(extensionIdentifier string) error {
	b.mu.Lock("DeleteExtension")
	defer b.mu.Unlock()

	ext := b.resolveExtension(extensionIdentifier)
	if ext == nil {
		return fmt.Errorf("%w: extension %s", ErrExtensionNotFound, extensionIdentifier)
	}

	b.extensions.Delete(ext.ID)
	delete(b.tags, ext.Arn)

	return nil
}

// CreateExtensionAssociation creates an association between an extension and a resource.
func (b *InMemoryBackend) CreateExtensionAssociation(
	extensionIdentifier, resourceIdentifier string,
	parameters map[string]string,
	extensionVersionNumber *int32,
) (*ExtensionAssociation, error) {
	b.mu.Lock("CreateExtensionAssociation")
	defer b.mu.Unlock()

	if extensionIdentifier == "" {
		return nil, fmt.Errorf("%w: ExtensionIdentifier is required", ErrBadRequest)
	}

	if resourceIdentifier == "" {
		return nil, fmt.Errorf("%w: ResourceIdentifier is required", ErrBadRequest)
	}

	ext := b.resolveExtension(extensionIdentifier)
	if ext == nil {
		return nil, fmt.Errorf("%w: extension %s", ErrExtensionNotFound, extensionIdentifier)
	}

	versionNum := ext.VersionNumber
	if extensionVersionNumber != nil {
		versionNum = *extensionVersionNumber
	}

	id := newResourceID()
	assoc := &ExtensionAssociation{
		ID:                     id,
		Arn:                    b.appconfigARN("extensionassociation/" + id),
		ExtensionArn:           ext.Arn,
		ResourceArn:            resourceIdentifier,
		ExtensionVersionNumber: versionNum,
		Parameters:             parameters,
	}
	b.extensionAssociations.Put(assoc)
	cp := *assoc

	return &cp, nil
}

// GetExtensionAssociation retrieves an extension association by ID.
func (b *InMemoryBackend) GetExtensionAssociation(
	extensionAssociationID string,
) (*ExtensionAssociation, error) {
	b.mu.RLock("GetExtensionAssociation")
	defer b.mu.RUnlock()

	assoc, ok := b.extensionAssociations.Get(extensionAssociationID)
	if !ok {
		return nil, fmt.Errorf(
			"%w: extension association %s",
			ErrExtensionAssociationNotFound,
			extensionAssociationID,
		)
	}

	cp := *assoc

	return &cp, nil
}

// ListExtensionAssociations returns paginated extension associations,
// optionally filtered by extensionIdentifier (ARN prefix) and/or resourceIdentifier (ARN prefix).
func (b *InMemoryBackend) ListExtensionAssociations(
	nextToken, extensionIdentifier, resourceIdentifier string,
	maxResults int,
) ([]ExtensionAssociation, string) {
	b.mu.RLock("ListExtensionAssociations")
	defer b.mu.RUnlock()

	all := b.extensionAssociations.All()
	out := make([]ExtensionAssociation, 0, len(all))

	for _, a := range all {
		if extensionIdentifier != "" && a.ExtensionArn != extensionIdentifier {
			continue
		}

		if resourceIdentifier != "" && a.ResourceArn != resourceIdentifier {
			continue
		}

		out = append(out, *a)
	}

	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })

	page, token := appConfigPaginate(out, nextToken, b.paginationSecret, maxResults)

	return page, token
}

// DeleteExtensionAssociation deletes an extension association by ID.
func (b *InMemoryBackend) DeleteExtensionAssociation(extensionAssociationID string) error {
	b.mu.Lock("DeleteExtensionAssociation")
	defer b.mu.Unlock()

	assoc, ok := b.extensionAssociations.Get(extensionAssociationID)
	if !ok {
		return fmt.Errorf(
			"%w: extension association %s",
			ErrExtensionAssociationNotFound,
			extensionAssociationID,
		)
	}

	b.extensionAssociations.Delete(extensionAssociationID)
	delete(b.tags, assoc.Arn)

	return nil
}

// GetAccountSettings returns the account-level AppConfig settings.
func (b *InMemoryBackend) GetAccountSettings() (*AccountSettings, error) {
	b.mu.RLock("GetAccountSettings")
	defer b.mu.RUnlock()

	cp := b.accountSettings

	return &cp, nil
}

// UpdateAccountSettings updates account-level AppConfig settings.
func (b *InMemoryBackend) UpdateAccountSettings(
	deletionProtection *DeletionProtectionSettings,
) (*AccountSettings, error) {
	b.mu.Lock("UpdateAccountSettings")
	defer b.mu.Unlock()

	if deletionProtection != nil {
		b.accountSettings.DeletionProtection = deletionProtection
	}

	cp := b.accountSettings

	return &cp, nil
}

// UpdateExtensionAssociation updates an extension association's parameters.
func (b *InMemoryBackend) UpdateExtensionAssociation(
	extensionAssociationID string,
	parameters map[string]string,
) (*ExtensionAssociation, error) {
	b.mu.Lock("UpdateExtensionAssociation")
	defer b.mu.Unlock()

	existing, ok := b.extensionAssociations.Get(extensionAssociationID)
	if !ok {
		return nil, fmt.Errorf(
			"%w: extension association %s",
			ErrExtensionAssociationNotFound,
			extensionAssociationID,
		)
	}

	updated := *existing
	if parameters != nil {
		updated.Parameters = parameters
	}

	b.extensionAssociations.Put(&updated)
	cp := updated

	return &cp, nil
}

// ValidateConfiguration validates a configuration version against its validators.
// In this implementation, all well-formed configurations are considered valid.
// The configurationVersion parameter is accepted for API compatibility but not evaluated.
func (b *InMemoryBackend) ValidateConfiguration(applicationID, profileID, _ string) error {
	b.mu.RLock("ValidateConfiguration")
	defer b.mu.RUnlock()

	if !b.applications.Has(applicationID) {
		return fmt.Errorf("%w: application %s", ErrApplicationNotFound, applicationID)
	}

	profile, ok := b.configProfiles.Get(profileID)
	if !ok || profile.ApplicationID != applicationID {
		return fmt.Errorf(
			"%w: configuration profile %s",
			ErrConfigurationProfileNotFound,
			profileID,
		)
	}

	return nil
}

// GetConfiguration retrieves the latest deployed configuration for the given application,
// environment, and configuration profile (deprecated API).
func (b *InMemoryBackend) GetConfiguration(
	application, environment, configuration string,
) (*HostedConfigurationVersion, error) {
	b.mu.RLock("GetConfiguration")
	defer b.mu.RUnlock()

	appID, err := b.resolveAppID(application)
	if err != nil {
		return nil, err
	}

	if _, err = b.resolveEnvID(appID, environment); err != nil {
		return nil, err
	}

	profileID, err := b.resolveProfileID(appID, configuration)
	if err != nil {
		return nil, err
	}

	return b.latestConfigVersion(appID, profileID), nil
}

// resolveAppID finds an application ID by ID or name. Must be called under lock.
func (b *InMemoryBackend) resolveAppID(identifier string) (string, error) {
	if b.applications.Has(identifier) {
		return identifier, nil
	}

	if matches := b.applicationsByName.Get(identifier); len(matches) > 0 {
		return matches[0].ID, nil
	}

	return "", fmt.Errorf("%w: application %s", ErrApplicationNotFound, identifier)
}

// resolveEnvID finds an environment ID by ID or name within an application. Must be called under lock.
func (b *InMemoryBackend) resolveEnvID(appID, identifier string) (string, error) {
	if env, ok := b.environments.Get(identifier); ok && env.ApplicationID == appID {
		return identifier, nil
	}

	if matches := b.environmentsByAppName.Get(appNameKey(appID, identifier)); len(matches) > 0 {
		return matches[0].ID, nil
	}

	return "", fmt.Errorf("%w: environment %s", ErrEnvironmentNotFound, identifier)
}

// resolveProfileID finds a configuration profile ID by ID or name. Must be called under lock.
func (b *InMemoryBackend) resolveProfileID(appID, identifier string) (string, error) {
	if profile, ok := b.configProfiles.Get(identifier); ok && profile.ApplicationID == appID {
		return identifier, nil
	}

	if matches := b.configProfilesByAppName.Get(appNameKey(appID, identifier)); len(matches) > 0 {
		return matches[0].ID, nil
	}

	return "", fmt.Errorf(
		"%w: configuration profile %s",
		ErrConfigurationProfileNotFound,
		identifier,
	)
}

// latestConfigVersion returns the latest hosted configuration version for a profile. Must be called under lock.
// It walks version numbers from the counter downward to skip any deleted versions, so the
// common case (no deletes) is O(1) and deletions from the top add at most one step each.
func (b *InMemoryBackend) latestConfigVersion(appID, profileID string) *HostedConfigurationVersion {
	empty := &HostedConfigurationVersion{
		ApplicationID:          appID,
		ConfigurationProfileID: profileID,
		ContentType:            contentTypeOctetStream,
		Content:                []byte{},
	}

	if len(b.hostedConfigVersionsByProfile.Get(appProfileKey(appID, profileID))) == 0 {
		return empty
	}

	counter := b.versionCounters[appID][profileID]

	for n := counter; n >= 1; n-- {
		if v, ok := b.hostedConfigVersions.Get(hcvKey(appID, profileID, n)); ok {
			cp := *v

			return &cp
		}
	}

	return empty
}

// appConfigPaginate applies HMAC-signed token-based pagination to a sorted slice.
func appConfigPaginate[T any](all []T, nextToken, secret string, maxResults int) ([]T, string) {
	const defaultLimit = 50

	p := page.NewHMAC(all, nextToken, secret, maxResults, defaultLimit)

	return p.Data, p.Next
}
