package ec2_test

import (
	"testing"

	"github.com/aws/aws-sdk-go-v2/aws"
	ec2sdk "github.com/aws/aws-sdk-go-v2/service/ec2"
	"github.com/aws/aws-sdk-go-v2/service/ec2/types"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/blackbirdworks/gopherstack/services/ec2"
)

// This file covers the second slice of the never-parity-recorded
// Describe/List operations (regenerated by grepping the dispatch table's own
// "OpName": h.handleOpName / ops["OpName"] = h.handleOpName registrations
// and subtracting names PARITY.md already mentions). It fixes seven
// previously-unread-Filters bugs, all confirmed to fail against pre-fix code
// first: the ID lists on these operations were already read correctly, but
// the Filters field declared on the wire (awsEc2query_serializeOpDocument*
// FlatKey "Filter") was silently dropped in every case, so a real client's
// filter was always ignored and every resource came back regardless.

// ---- Bug 1: DescribeClassicLinkInstances ----
//
// Filters (group-id, tag, tag-key, vpc-id -- api_op_DescribeClassicLinkInstances.go)
// were declared but never read; only the InstanceId.N list was honored.
func TestDescribeClassicLinkInstances_VpcIdFilter_RealClient(t *testing.T) {
	t.Parallel()

	h := ec2.NewHandler(ec2.NewInMemoryBackend("000000000000", "us-east-1"))
	client := newTestEC2Client(t, h)

	vpc1, err := client.CreateVpc(t.Context(), &ec2sdk.CreateVpcInput{CidrBlock: aws.String("10.0.0.0/16")})
	require.NoError(t, err)
	vpc2, err := client.CreateVpc(t.Context(), &ec2sdk.CreateVpcInput{CidrBlock: aws.String("10.1.0.0/16")})
	require.NoError(t, err)

	_, err = client.EnableVpcClassicLink(t.Context(), &ec2sdk.EnableVpcClassicLinkInput{VpcId: vpc1.Vpc.VpcId})
	require.NoError(t, err)
	_, err = client.EnableVpcClassicLink(t.Context(), &ec2sdk.EnableVpcClassicLinkInput{VpcId: vpc2.Vpc.VpcId})
	require.NoError(t, err)

	sg1, err := client.CreateSecurityGroup(t.Context(), &ec2sdk.CreateSecurityGroupInput{
		GroupName: aws.String("sweep42-sg1"), Description: aws.String("sweep42-sg1"), VpcId: vpc1.Vpc.VpcId,
	})
	require.NoError(t, err)
	sg2, err := client.CreateSecurityGroup(t.Context(), &ec2sdk.CreateSecurityGroupInput{
		GroupName: aws.String("sweep42-sg2"), Description: aws.String("sweep42-sg2"), VpcId: vpc2.Vpc.VpcId,
	})
	require.NoError(t, err)

	inst1, err := client.RunInstances(t.Context(), &ec2sdk.RunInstancesInput{
		ImageId: aws.String("ami-sweep42a"), InstanceType: types.InstanceTypeT3Micro,
		MinCount: aws.Int32(1), MaxCount: aws.Int32(1),
	})
	require.NoError(t, err)
	inst2, err := client.RunInstances(t.Context(), &ec2sdk.RunInstancesInput{
		ImageId: aws.String("ami-sweep42a"), InstanceType: types.InstanceTypeT3Micro,
		MinCount: aws.Int32(1), MaxCount: aws.Int32(1),
	})
	require.NoError(t, err)

	_, err = client.AttachClassicLinkVpc(t.Context(), &ec2sdk.AttachClassicLinkVpcInput{
		InstanceId: inst1.Instances[0].InstanceId, VpcId: vpc1.Vpc.VpcId, Groups: []string{aws.ToString(sg1.GroupId)},
	})
	require.NoError(t, err)
	_, err = client.AttachClassicLinkVpc(t.Context(), &ec2sdk.AttachClassicLinkVpcInput{
		InstanceId: inst2.Instances[0].InstanceId, VpcId: vpc2.Vpc.VpcId, Groups: []string{aws.ToString(sg2.GroupId)},
	})
	require.NoError(t, err)

	out, err := client.DescribeClassicLinkInstances(t.Context(), &ec2sdk.DescribeClassicLinkInstancesInput{
		Filters: []types.Filter{{Name: aws.String("vpc-id"), Values: []string{aws.ToString(vpc1.Vpc.VpcId)}}},
	})
	require.NoError(t, err)
	require.Len(t, out.Instances, 1, "vpc-id filter ignored -- expected only the instance linked to vpc1")
	assert.Equal(t, aws.ToString(inst1.Instances[0].InstanceId), aws.ToString(out.Instances[0].InstanceId))
}

// ---- Bug 2: DescribeSecondaryNetworks ----
//
// Filters (owner-id, secondary-network-id, secondary-network-arn, state,
// type, ipv4-cidr-block-association.*, tag, tag-key --
// api_op_DescribeSecondaryNetworks.go) were declared but never read.
func TestDescribeSecondaryNetworks_TypeFilter_RealClient(t *testing.T) {
	t.Parallel()

	h := ec2.NewHandler(ec2.NewInMemoryBackend("000000000000", "us-east-1"))
	client := newTestEC2Client(t, h)

	rdma, err := client.CreateSecondaryNetwork(t.Context(), &ec2sdk.CreateSecondaryNetworkInput{
		Ipv4CidrBlock: aws.String("100.64.0.0/16"), NetworkType: types.SecondaryNetworkTypeRdma,
	})
	require.NoError(t, err)
	_, err = client.CreateSecondaryNetwork(t.Context(), &ec2sdk.CreateSecondaryNetworkInput{
		Ipv4CidrBlock: aws.String("100.65.0.0/16"), NetworkType: types.SecondaryNetworkTypeRdma,
	})
	require.NoError(t, err)

	out, err := client.DescribeSecondaryNetworks(t.Context(), &ec2sdk.DescribeSecondaryNetworksInput{
		Filters: []types.Filter{{Name: aws.String("type"), Values: []string{"rdma"}}},
	})
	require.NoError(t, err)
	require.Len(t, out.SecondaryNetworks, 2, "both networks are type=rdma (the backend's only supported type)")

	byID, err := client.DescribeSecondaryNetworks(t.Context(), &ec2sdk.DescribeSecondaryNetworksInput{
		Filters: []types.Filter{
			{
				Name:   aws.String("secondary-network-id"),
				Values: []string{aws.ToString(rdma.SecondaryNetwork.SecondaryNetworkId)},
			},
		},
	})
	require.NoError(t, err)
	require.Len(t, byID.SecondaryNetworks, 1, "secondary-network-id filter ignored")
	assert.Equal(t, aws.ToString(rdma.SecondaryNetwork.SecondaryNetworkId),
		aws.ToString(byID.SecondaryNetworks[0].SecondaryNetworkId))
}

// ---- Bug 3: DescribeSecondarySubnets ----
//
// Filters (owner-id, secondary-network-id, secondary-network-type,
// secondary-subnet-id, secondary-subnet-arn, state,
// ipv4-cidr-block-association.*, tag, tag-key --
// api_op_DescribeSecondarySubnets.go) were declared but never read.
func TestDescribeSecondarySubnets_SecondaryNetworkIdFilter_RealClient(t *testing.T) {
	t.Parallel()

	h := ec2.NewHandler(ec2.NewInMemoryBackend("000000000000", "us-east-1"))
	client := newTestEC2Client(t, h)

	net1, err := client.CreateSecondaryNetwork(t.Context(), &ec2sdk.CreateSecondaryNetworkInput{
		Ipv4CidrBlock: aws.String("100.64.0.0/16"), NetworkType: types.SecondaryNetworkTypeRdma,
	})
	require.NoError(t, err)
	net2, err := client.CreateSecondaryNetwork(t.Context(), &ec2sdk.CreateSecondaryNetworkInput{
		Ipv4CidrBlock: aws.String("100.65.0.0/16"), NetworkType: types.SecondaryNetworkTypeRdma,
	})
	require.NoError(t, err)

	sub1, err := client.CreateSecondarySubnet(t.Context(), &ec2sdk.CreateSecondarySubnetInput{
		Ipv4CidrBlock: aws.String("100.64.1.0/24"), SecondaryNetworkId: net1.SecondaryNetwork.SecondaryNetworkId,
	})
	require.NoError(t, err)
	_, err = client.CreateSecondarySubnet(t.Context(), &ec2sdk.CreateSecondarySubnetInput{
		Ipv4CidrBlock: aws.String("100.65.1.0/24"), SecondaryNetworkId: net2.SecondaryNetwork.SecondaryNetworkId,
	})
	require.NoError(t, err)

	out, err := client.DescribeSecondarySubnets(t.Context(), &ec2sdk.DescribeSecondarySubnetsInput{
		Filters: []types.Filter{
			{
				Name:   aws.String("secondary-network-id"),
				Values: []string{aws.ToString(net1.SecondaryNetwork.SecondaryNetworkId)},
			},
		},
	})
	require.NoError(t, err)
	require.Len(t, out.SecondarySubnets, 1,
		"secondary-network-id filter ignored -- expected only the subnet under net1")
	assert.Equal(t, aws.ToString(sub1.SecondarySubnet.SecondarySubnetId),
		aws.ToString(out.SecondarySubnets[0].SecondarySubnetId))
}

// ---- Bug 4: DescribeSecondaryInterfaces ----
//
// Filters (owner-id, status, secondary-interface-id/-arn/-type,
// secondary-network-id/-type, secondary-subnet-id, attachment.instance-id,
// private-ipv4-addresses.private-ip-address, tag, tag-key --
// api_op_DescribeSecondaryInterfaces.go) were declared but never read.
// Secondary interfaces have no Create API (seeded directly, same as this
// backend's other Outpost/RDMA hardware resources); the Describe call under
// test still goes through the real SDK client.
func TestDescribeSecondaryInterfaces_StatusFilter_RealClient(t *testing.T) {
	t.Parallel()

	backend := ec2.NewInMemoryBackend("000000000000", "us-east-1")
	h := ec2.NewHandler(backend)
	client := newTestEC2Client(t, h)

	avail, err := backend.SeedSecondaryInterface(ec2.SecondaryInterface{Status: "available"})
	require.NoError(t, err)
	_, err = backend.SeedSecondaryInterface(ec2.SecondaryInterface{Status: "in-use"})
	require.NoError(t, err)

	out, err := client.DescribeSecondaryInterfaces(t.Context(), &ec2sdk.DescribeSecondaryInterfacesInput{
		Filters: []types.Filter{{Name: aws.String("status"), Values: []string{"available"}}},
	})
	require.NoError(t, err)
	require.Len(t, out.SecondaryInterfaces, 1, "status filter ignored -- expected only the available interface")
	assert.Equal(t, avail.SecondaryInterfaceID, aws.ToString(out.SecondaryInterfaces[0].SecondaryInterfaceId))
}

// ---- Bug 5: DescribeServiceLinkVirtualInterfaces ----
//
// Filters (owner-id, outpost-lag-id, outpost-arn, state, vlan,
// service-link-virtual-interface-id, local-gateway-virtual-interface-id,
// tag, tag-key -- api_op_DescribeServiceLinkVirtualInterfaces.go) were
// declared but never read. Like secondary interfaces, these have no Create
// API and are seeded directly; the Describe call under test still goes
// through the real SDK client.
func TestDescribeServiceLinkVirtualInterfaces_OutpostLagIdFilter_RealClient(t *testing.T) {
	t.Parallel()

	backend := ec2.NewInMemoryBackend("000000000000", "us-east-1")
	h := ec2.NewHandler(backend)
	client := newTestEC2Client(t, h)

	match, err := backend.SeedServiceLinkVirtualInterface(ec2.ServiceLinkVirtualInterface{OutpostLagID: "lag-sweep42a"})
	require.NoError(t, err)
	_, err = backend.SeedServiceLinkVirtualInterface(ec2.ServiceLinkVirtualInterface{OutpostLagID: "lag-sweep42b"})
	require.NoError(t, err)

	out, err := client.DescribeServiceLinkVirtualInterfaces(
		t.Context(), &ec2sdk.DescribeServiceLinkVirtualInterfacesInput{
			Filters: []types.Filter{{Name: aws.String("outpost-lag-id"), Values: []string{"lag-sweep42a"}}},
		},
	)
	require.NoError(t, err)
	require.Len(t, out.ServiceLinkVirtualInterfaces, 1, "outpost-lag-id filter ignored")
	assert.Equal(t, match.ServiceLinkVirtualInterfaceID,
		aws.ToString(out.ServiceLinkVirtualInterfaces[0].ServiceLinkVirtualInterfaceId))
}

// ---- Bug 6: DescribeInstanceSqlHaHistoryStates ----
//
// Filters (tag, tag-key, haStatus, sqlServerLicenseUsage --
// api_op_DescribeInstanceSqlHaHistoryStates.go) were declared but never
// read; only InstanceId.N/StartTime/EndTime were honored.
func TestDescribeInstanceSqlHaHistoryStates_HaStatusFilter_RealClient(t *testing.T) {
	t.Parallel()

	h := ec2.NewHandler(ec2.NewInMemoryBackend("000000000000", "us-east-1"))
	client := newTestEC2Client(t, h)

	inst, err := client.RunInstances(t.Context(), &ec2sdk.RunInstancesInput{
		ImageId: aws.String("ami-sweep42b"), InstanceType: types.InstanceTypeT3Micro,
		MinCount: aws.Int32(1), MaxCount: aws.Int32(1),
	})
	require.NoError(t, err)
	instanceID := inst.Instances[0].InstanceId

	_, err = client.EnableInstanceSqlHaStandbyDetections(t.Context(), &ec2sdk.EnableInstanceSqlHaStandbyDetectionsInput{
		InstanceIds: []string{aws.ToString(instanceID)},
	})
	require.NoError(t, err, "registration starts in \"processing\" state, recorded to history")

	_, err = client.DescribeInstanceSqlHaStates(t.Context(), &ec2sdk.DescribeInstanceSqlHaStatesInput{
		InstanceIds: []string{aws.ToString(instanceID)},
	})
	require.NoError(t, err, "settles \"processing\" -> \"active\", recorded to history")

	out, err := client.DescribeInstanceSqlHaHistoryStates(t.Context(), &ec2sdk.DescribeInstanceSqlHaHistoryStatesInput{
		InstanceIds: []string{aws.ToString(instanceID)},
		Filters:     []types.Filter{{Name: aws.String("haStatus"), Values: []string{"processing"}}},
	})
	require.NoError(t, err)
	require.Len(t, out.Instances, 1,
		"haStatus filter ignored -- expected only the \"processing\" history entry, not \"active\" too")
	assert.Equal(t, types.HaStatusProcessing, out.Instances[0].HaStatus)
}

// ---- Bug 7: DescribeImageUsageReportEntries ----
//
// Filters (account-id, creation-time, resource-type --
// api_op_DescribeImageUsageReportEntries.go) were declared but never read;
// only ReportId.N/ImageId.N were honored.
func TestDescribeImageUsageReportEntries_ResourceTypeFilter_RealClient(t *testing.T) {
	t.Parallel()

	h := ec2.NewHandler(ec2.NewInMemoryBackend("000000000000", "us-east-1"))
	client := newTestEC2Client(t, h)

	img, err := client.RegisterImage(t.Context(), &ec2sdk.RegisterImageInput{Name: aws.String("sweep42-image")})
	require.NoError(t, err)

	_, err = client.RunInstances(t.Context(), &ec2sdk.RunInstancesInput{
		ImageId: img.ImageId, InstanceType: types.InstanceTypeT3Micro,
		MinCount: aws.Int32(1), MaxCount: aws.Int32(1),
	})
	require.NoError(t, err)

	_, err = client.CreateLaunchTemplate(t.Context(), &ec2sdk.CreateLaunchTemplateInput{
		LaunchTemplateName: aws.String("sweep42-lt"),
		LaunchTemplateData: &types.RequestLaunchTemplateData{ImageId: img.ImageId},
	})
	require.NoError(t, err)

	report, err := client.CreateImageUsageReport(t.Context(), &ec2sdk.CreateImageUsageReportInput{
		ImageId: img.ImageId,
		ResourceTypes: []types.ImageUsageResourceTypeRequest{
			{ResourceType: aws.String("ec2:Instance")},
			{ResourceType: aws.String("ec2:LaunchTemplate")},
		},
	})
	require.NoError(t, err)

	out, err := client.DescribeImageUsageReportEntries(t.Context(), &ec2sdk.DescribeImageUsageReportEntriesInput{
		ReportIds: []string{aws.ToString(report.ReportId)},
		Filters:   []types.Filter{{Name: aws.String("resource-type"), Values: []string{"ec2:Instance"}}},
	})
	require.NoError(t, err)
	require.Len(t, out.ImageUsageReportEntries, 1,
		"resource-type filter ignored -- expected only the ec2:Instance entry, not ec2:LaunchTemplate too")
	assert.Equal(t, "ec2:Instance", aws.ToString(out.ImageUsageReportEntries[0].ResourceType))
}
