package ec2_test

import (
	"testing"

	"github.com/aws/aws-sdk-go-v2/aws"
	ec2sdk "github.com/aws/aws-sdk-go-v2/service/ec2"
	"github.com/aws/aws-sdk-go-v2/service/ec2/types"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/blackbirdworks/gopherstack/services/ec2"
)

// This file covers a slice of the never-parity-recorded Describe/List
// operations (regenerated by grepping the dispatch table's own
// "OpName": h.handleOpName / ops["OpName"] = h.handleOpName registrations
// and subtracting names PARITY.md already mentions). It fixes eight
// previously-unread/misread-parameter bugs and confirms nine more operations
// read their wire keys correctly. Four further operations
// (DescribeTransitGatewayConnects/ConnectPeers/PeeringAttachments/
// RouteTables) were already fixed and covered by real-client tests in
// wire_field_fixes_ec2sweep36_test.go -- PARITY.md simply never recorded
// them; see PARITY.md for that correction.

// ---- Bug 1: DescribePrincipalIdFormat ----
//
// handleDescribePrincipalIDFormat used to read "PrincipalArn" -- a key that
// does not exist anywhere on DescribePrincipalIdFormatInput
// (api_op_DescribePrincipalIdFormat.go has no such field at all; the
// operation always describes the calling principal) -- and never read the
// real Resource.N filter the wire does declare
// (awsEc2query_serializeOpDocumentDescribePrincipalIdFormatInput: FlatKey
// "Resource"). A real client's Resources filter was silently dropped and
// every resource type's ID-format status came back regardless.
func TestDescribePrincipalIdFormat_ResourceFilter_RealClient(t *testing.T) {
	t.Parallel()

	h := ec2.NewHandler(ec2.NewInMemoryBackend("000000000000", "us-east-1"))
	client := newTestEC2Client(t, h)

	out, err := client.DescribePrincipalIdFormat(t.Context(), &ec2sdk.DescribePrincipalIdFormatInput{
		Resources: []string{"instance"},
	})
	require.NoError(t, err)
	require.Len(t, out.Principals, 1)

	resources := make([]string, 0, len(out.Principals[0].Statuses))
	for _, s := range out.Principals[0].Statuses {
		resources = append(resources, aws.ToString(s.Resource))
	}

	assert.Equal(t, []string{"instance"}, resources,
		"Resource filter ignored -- expected only \"instance\", got %v", resources)
}

// ---- Bug 2: DescribeIamInstanceProfileAssociations ----
//
// handleDescribeIamInstanceProfileAssociations used to unconditionally read
// Filter.1.Value.1 as the instance-id filter value BEFORE checking whether
// Filter.1.Name was actually "instance-id"
// (DescribeIamInstanceProfileAssociationsInput.Filters documents only
// "instance-id" and "state", api_op_DescribeIamInstanceProfileAssociations.go).
// A lone "state" filter sent as Filter.1 was misread as an instance-id
// filter matching no real instance, so every association was silently
// dropped.
func TestDescribeIamInstanceProfileAssociations_StateFilter_RealClient(t *testing.T) {
	t.Parallel()

	h := ec2.NewHandler(ec2.NewInMemoryBackend("000000000000", "us-east-1"))
	client := newTestEC2Client(t, h)

	for range 2 {
		instOut, err := client.RunInstances(t.Context(), &ec2sdk.RunInstancesInput{
			ImageId:      aws.String("ami-sweep41a"),
			InstanceType: types.InstanceTypeT3Micro,
			MinCount:     aws.Int32(1),
			MaxCount:     aws.Int32(1),
		})
		require.NoError(t, err)
		require.Len(t, instOut.Instances, 1)

		_, err = client.AssociateIamInstanceProfile(t.Context(), &ec2sdk.AssociateIamInstanceProfileInput{
			InstanceId: instOut.Instances[0].InstanceId,
			IamInstanceProfile: &types.IamInstanceProfileSpecification{
				Arn: aws.String("arn:aws:iam::000000000000:instance-profile/sweep41a"),
			},
		})
		require.NoError(t, err)
	}

	out, err := client.DescribeIamInstanceProfileAssociations(
		t.Context(),
		&ec2sdk.DescribeIamInstanceProfileAssociationsInput{
			Filters: []types.Filter{
				{Name: aws.String("state"), Values: []string{"associated"}},
			},
		},
	)
	require.NoError(t, err)
	assert.Len(t, out.IamInstanceProfileAssociations, 2,
		"a lone \"state\" filter was misread as an instance-id filter, dropping every association")
}

// ---- Bug 3: DescribeLaunchTemplates ----
//
// handleDescribeLaunchTemplates used to only ever read LaunchTemplateName.N,
// silently ignoring LaunchTemplateId.N even though
// awsEc2query_serializeOpDocumentDescribeLaunchTemplatesInput FlatKeys both
// "LaunchTemplateId" and "LaunchTemplateName" -- a client filtering by
// specific template IDs got every template back unfiltered.
func TestDescribeLaunchTemplates_LaunchTemplateIds_RealClient(t *testing.T) {
	t.Parallel()

	h := ec2.NewHandler(ec2.NewInMemoryBackend("000000000000", "us-east-1"))
	client := newTestEC2Client(t, h)

	lt1, err := client.CreateLaunchTemplate(t.Context(), &ec2sdk.CreateLaunchTemplateInput{
		LaunchTemplateName: aws.String("sweep41-lt1"),
		LaunchTemplateData: &types.RequestLaunchTemplateData{ImageId: aws.String("ami-sweep41b")},
	})
	require.NoError(t, err)

	_, err = client.CreateLaunchTemplate(t.Context(), &ec2sdk.CreateLaunchTemplateInput{
		LaunchTemplateName: aws.String("sweep41-lt2"),
		LaunchTemplateData: &types.RequestLaunchTemplateData{ImageId: aws.String("ami-sweep41c")},
	})
	require.NoError(t, err)

	out, err := client.DescribeLaunchTemplates(t.Context(), &ec2sdk.DescribeLaunchTemplatesInput{
		LaunchTemplateIds: []string{aws.ToString(lt1.LaunchTemplate.LaunchTemplateId)},
	})
	require.NoError(t, err)
	require.Len(t, out.LaunchTemplates, 1,
		"LaunchTemplateIds ignored -- expected exactly the requested template")
	assert.Equal(t, "sweep41-lt1", aws.ToString(out.LaunchTemplates[0].LaunchTemplateName))
}

// ---- Bug 4: DescribeLaunchTemplateVersions ----
//
// handleDescribeLaunchTemplateVersions used to only ever read
// LaunchTemplateId, ignoring LaunchTemplateName (an alternative identifier),
// Versions (FlatKey "LaunchTemplateVersion"), and MinVersion/MaxVersion
// (awsEc2query_serializeOpDocumentDescribeLaunchTemplateVersionsInput). A
// client identifying the template by name alone always got "LaunchTemplateId
// is required"; MinVersion/MaxVersion range requests were silently ignored.
func TestDescribeLaunchTemplateVersions_NameAndVersionRange_RealClient(t *testing.T) {
	t.Parallel()

	h := ec2.NewHandler(ec2.NewInMemoryBackend("000000000000", "us-east-1"))
	client := newTestEC2Client(t, h)

	_, err := client.CreateLaunchTemplate(t.Context(), &ec2sdk.CreateLaunchTemplateInput{
		LaunchTemplateName: aws.String("sweep41-ltv"),
		LaunchTemplateData: &types.RequestLaunchTemplateData{ImageId: aws.String("ami-sweep41d")},
	})
	require.NoError(t, err)

	byName, err := client.DescribeLaunchTemplateVersions(t.Context(), &ec2sdk.DescribeLaunchTemplateVersionsInput{
		LaunchTemplateName: aws.String("sweep41-ltv"),
	})
	require.NoError(t, err,
		"LaunchTemplateName ignored -- LaunchTemplateId was required even though the wire allows either")
	require.Len(t, byName.LaunchTemplateVersions, 1)

	tooHigh, err := client.DescribeLaunchTemplateVersions(t.Context(), &ec2sdk.DescribeLaunchTemplateVersionsInput{
		LaunchTemplateName: aws.String("sweep41-ltv"),
		MinVersion:         aws.String("2"),
	})
	require.NoError(t, err)
	assert.Empty(t, tooHigh.LaunchTemplateVersions,
		"MinVersion ignored -- the only version is 1, which should not satisfy MinVersion=2")
}

// ---- Bug 5: DescribeImageUsageReports ----
//
// handleDescribeImageUsageReports used to ignore its url.Values entirely,
// dropping ReportId.N and ImageId.N even though both are FlatKey lists on
// the wire (awsEc2query_serializeOpDocumentDescribeImageUsageReportsInput).
func TestDescribeImageUsageReports_ReportIdFilter_RealClient(t *testing.T) {
	t.Parallel()

	h := ec2.NewHandler(ec2.NewInMemoryBackend("000000000000", "us-east-1"))
	client := newTestEC2Client(t, h)

	img, err := client.RegisterImage(t.Context(), &ec2sdk.RegisterImageInput{
		Name: aws.String("sweep41-image"),
	})
	require.NoError(t, err)

	resourceTypes := []types.ImageUsageResourceTypeRequest{{ResourceType: aws.String("ec2:Instance")}}

	report1, err := client.CreateImageUsageReport(t.Context(), &ec2sdk.CreateImageUsageReportInput{
		ImageId:       img.ImageId,
		ResourceTypes: resourceTypes,
	})
	require.NoError(t, err)

	_, err = client.CreateImageUsageReport(t.Context(), &ec2sdk.CreateImageUsageReportInput{
		ImageId:       img.ImageId,
		ResourceTypes: resourceTypes,
	})
	require.NoError(t, err)

	out, err := client.DescribeImageUsageReports(t.Context(), &ec2sdk.DescribeImageUsageReportsInput{
		ReportIds: []string{aws.ToString(report1.ReportId)},
	})
	require.NoError(t, err)
	require.Len(t, out.ImageUsageReports, 1, "ReportIds ignored -- expected exactly the requested report")
	assert.Equal(t, aws.ToString(report1.ReportId), aws.ToString(out.ImageUsageReports[0].ReportId))
}

// ---- Bug 6: DescribeVpcEndpointServices ----
//
// handleDescribeVpcEndpointServices used to ignore its url.Values entirely,
// dropping ServiceName.N even though it is a FlatKey list on the wire
// (awsEc2query_serializeOpDocumentDescribeVpcEndpointServicesInput).
func TestDescribeVpcEndpointServices_ServiceNameFilter_RealClient(t *testing.T) {
	t.Parallel()

	h := ec2.NewHandler(ec2.NewInMemoryBackend("000000000000", "us-east-1"))
	client := newTestEC2Client(t, h)

	out, err := client.DescribeVpcEndpointServices(t.Context(), &ec2sdk.DescribeVpcEndpointServicesInput{
		ServiceNames: []string{"com.amazonaws.us-east-1.s3"},
	})
	require.NoError(t, err)
	require.Len(t, out.ServiceNames, 1, "ServiceNames ignored -- expected exactly the requested service")
	assert.Equal(t, "com.amazonaws.us-east-1.s3", out.ServiceNames[0])
	require.Len(t, out.ServiceDetails, 1)
}

// ---- Bug 7: DescribeCustomerGateways ----
//
// handleDescribeCustomerGateways used to never read Filters at all
// (awsEc2query_serializeOpDocumentDescribeCustomerGatewaysInput declares
// it), so every customer gateway came back regardless of filter.
func TestDescribeCustomerGateways_Filter_RealClient(t *testing.T) {
	t.Parallel()

	h := ec2.NewHandler(ec2.NewInMemoryBackend("000000000000", "us-east-1"))
	client := newTestEC2Client(t, h)

	cgw1, err := client.CreateCustomerGateway(t.Context(), &ec2sdk.CreateCustomerGatewayInput{
		Type:      types.GatewayTypeIpsec1,
		IpAddress: aws.String("203.0.113.1"),
		BgpAsn:    aws.Int32(65001),
	})
	require.NoError(t, err)

	_, err = client.CreateCustomerGateway(t.Context(), &ec2sdk.CreateCustomerGatewayInput{
		Type:      types.GatewayTypeIpsec1,
		IpAddress: aws.String("203.0.113.2"),
		BgpAsn:    aws.Int32(65002),
	})
	require.NoError(t, err)

	out, err := client.DescribeCustomerGateways(t.Context(), &ec2sdk.DescribeCustomerGatewaysInput{
		Filters: []types.Filter{
			{
				Name:   aws.String("customer-gateway-id"),
				Values: []string{aws.ToString(cgw1.CustomerGateway.CustomerGatewayId)},
			},
		},
	})
	require.NoError(t, err)
	require.Len(t, out.CustomerGateways, 1, "Filters ignored -- expected exactly the requested customer gateway")
	assert.Equal(t, "203.0.113.1", aws.ToString(out.CustomerGateways[0].IpAddress))
}

// ---- Bug 8: DescribeVpnGateways ----
//
// handleDescribeVpnGateways used to never read Filters at all
// (awsEc2query_serializeOpDocumentDescribeVpnGatewaysInput declares it), so
// every VPN gateway came back regardless of filter.
func TestDescribeVpnGateways_Filter_RealClient(t *testing.T) {
	t.Parallel()

	h := ec2.NewHandler(ec2.NewInMemoryBackend("000000000000", "us-east-1"))
	client := newTestEC2Client(t, h)

	vgw1, err := client.CreateVpnGateway(t.Context(), &ec2sdk.CreateVpnGatewayInput{
		Type: types.GatewayTypeIpsec1,
	})
	require.NoError(t, err)

	_, err = client.CreateVpnGateway(t.Context(), &ec2sdk.CreateVpnGatewayInput{
		Type: types.GatewayTypeIpsec1,
	})
	require.NoError(t, err)

	out, err := client.DescribeVpnGateways(t.Context(), &ec2sdk.DescribeVpnGatewaysInput{
		Filters: []types.Filter{
			{Name: aws.String("vpn-gateway-id"), Values: []string{aws.ToString(vgw1.VpnGateway.VpnGatewayId)}},
		},
	})
	require.NoError(t, err)
	require.Len(t, out.VpnGateways, 1, "Filters ignored -- expected exactly the requested VPN gateway")
	assert.Equal(t, aws.ToString(vgw1.VpnGateway.VpnGatewayId), aws.ToString(out.VpnGateways[0].VpnGatewayId))
}

// ---- Confirmed correct below: real filter/ID assertions, not just err == nil ----

// DescribeAccountAttributes reads AttributeName.N correctly
// (awsEc2query_serializeOpDocumentDescribeAccountAttributesInput FlatKeys
// "AttributeName").
func TestDescribeAccountAttributes_AttributeNameFilter_RealClient(t *testing.T) {
	t.Parallel()

	h := ec2.NewHandler(ec2.NewInMemoryBackend("000000000000", "us-east-1"))
	client := newTestEC2Client(t, h)

	out, err := client.DescribeAccountAttributes(t.Context(), &ec2sdk.DescribeAccountAttributesInput{
		AttributeNames: []types.AccountAttributeName{types.AccountAttributeNameDefaultVpc},
	})
	require.NoError(t, err)
	require.Len(t, out.AccountAttributes, 1)
	assert.Equal(t, "default-vpc", aws.ToString(out.AccountAttributes[0].AttributeName))
}

// DescribeDeclarativePoliciesReports reads ReportId.N correctly
// (awsEc2query_serializeOpDocumentDescribeDeclarativePoliciesReportsInput
// FlatKeys "ReportId").
func TestDescribeDeclarativePoliciesReports_ReportIdFilter_RealClient(t *testing.T) {
	t.Parallel()

	h := ec2.NewHandler(ec2.NewInMemoryBackend("000000000000", "us-east-1"))
	client := newTestEC2Client(t, h)

	report1, err := client.StartDeclarativePoliciesReport(t.Context(), &ec2sdk.StartDeclarativePoliciesReportInput{
		S3Bucket: aws.String("sweep41-bucket"),
		TargetId: aws.String("000000000000"),
	})
	require.NoError(t, err)

	_, err = client.StartDeclarativePoliciesReport(t.Context(), &ec2sdk.StartDeclarativePoliciesReportInput{
		S3Bucket: aws.String("sweep41-bucket"),
		TargetId: aws.String("000000000000"),
	})
	require.NoError(t, err)

	out, err := client.DescribeDeclarativePoliciesReports(
		t.Context(),
		&ec2sdk.DescribeDeclarativePoliciesReportsInput{
			ReportIds: []string{aws.ToString(report1.ReportId)},
		},
	)
	require.NoError(t, err)
	require.Len(t, out.Reports, 1)
	assert.Equal(t, aws.ToString(report1.ReportId), aws.ToString(out.Reports[0].ReportId))
}

// DescribeVpcClassicLink reads the singular VpcId.N correctly
// (awsEc2query_serializeOpDocumentDescribeVpcClassicLinkInput FlatKeys
// "VpcId" -- singular, unlike DescribeVpcClassicLinkDnsSupport below).
func TestDescribeVpcClassicLink_VpcIdFilter_RealClient(t *testing.T) {
	t.Parallel()

	h := ec2.NewHandler(ec2.NewInMemoryBackend("000000000000", "us-east-1"))
	client := newTestEC2Client(t, h)

	vpc1, err := client.CreateVpc(t.Context(), &ec2sdk.CreateVpcInput{CidrBlock: aws.String("10.41.0.0/16")})
	require.NoError(t, err)
	vpc2, err := client.CreateVpc(t.Context(), &ec2sdk.CreateVpcInput{CidrBlock: aws.String("10.42.0.0/16")})
	require.NoError(t, err)

	for _, id := range []*string{vpc1.Vpc.VpcId, vpc2.Vpc.VpcId} {
		_, enableErr := client.EnableVpcClassicLink(t.Context(), &ec2sdk.EnableVpcClassicLinkInput{VpcId: id})
		require.NoError(t, enableErr)
	}

	out, err := client.DescribeVpcClassicLink(t.Context(), &ec2sdk.DescribeVpcClassicLinkInput{
		VpcIds: []string{aws.ToString(vpc1.Vpc.VpcId)},
	})
	require.NoError(t, err)
	require.Len(t, out.Vpcs, 1)
	assert.Equal(t, aws.ToString(vpc1.Vpc.VpcId), aws.ToString(out.Vpcs[0].VpcId))
	assert.True(t, aws.ToBool(out.Vpcs[0].ClassicLinkEnabled))
}

// DescribeVpcClassicLinkDnsSupport reads the plural VpcIds.N correctly
// (awsEc2query_serializeOpDocumentDescribeVpcClassicLinkDnsSupportInput
// FlatKeys "VpcIds" -- plural, the opposite of DescribeVpcClassicLink above.
// Confirms the field name does not predict the wire key either way, per
// this campaign's brief.)
func TestDescribeVpcClassicLinkDnsSupport_VpcIdsFilter_RealClient(t *testing.T) {
	t.Parallel()

	h := ec2.NewHandler(ec2.NewInMemoryBackend("000000000000", "us-east-1"))
	client := newTestEC2Client(t, h)

	vpc1, err := client.CreateVpc(t.Context(), &ec2sdk.CreateVpcInput{CidrBlock: aws.String("10.43.0.0/16")})
	require.NoError(t, err)
	vpc2, err := client.CreateVpc(t.Context(), &ec2sdk.CreateVpcInput{CidrBlock: aws.String("10.44.0.0/16")})
	require.NoError(t, err)

	for _, id := range []*string{vpc1.Vpc.VpcId, vpc2.Vpc.VpcId} {
		_, enableErr := client.EnableVpcClassicLinkDnsSupport(
			t.Context(), &ec2sdk.EnableVpcClassicLinkDnsSupportInput{VpcId: id},
		)
		require.NoError(t, enableErr)
	}

	out, err := client.DescribeVpcClassicLinkDnsSupport(
		t.Context(), &ec2sdk.DescribeVpcClassicLinkDnsSupportInput{
			VpcIds: []string{aws.ToString(vpc1.Vpc.VpcId)},
		},
	)
	require.NoError(t, err)
	require.Len(t, out.Vpcs, 1)
	assert.Equal(t, aws.ToString(vpc1.Vpc.VpcId), aws.ToString(out.Vpcs[0].VpcId))
	assert.True(t, aws.ToBool(out.Vpcs[0].ClassicLinkDnsSupported))
}

// DescribeVpcPeeringConnections reads VpcPeeringConnectionId.N correctly
// (awsEc2query_serializeOpDocumentDescribeVpcPeeringConnectionsInput
// FlatKeys "VpcPeeringConnectionId").
func TestDescribeVpcPeeringConnections_IdFilter_RealClient(t *testing.T) {
	t.Parallel()

	h := ec2.NewHandler(ec2.NewInMemoryBackend("000000000000", "us-east-1"))
	client := newTestEC2Client(t, h)

	vpc, err := client.CreateVpc(t.Context(), &ec2sdk.CreateVpcInput{CidrBlock: aws.String("10.45.0.0/16")})
	require.NoError(t, err)

	pcx, err := client.CreateVpcPeeringConnection(t.Context(), &ec2sdk.CreateVpcPeeringConnectionInput{
		VpcId:     vpc.Vpc.VpcId,
		PeerVpcId: aws.String("vpc-sweep41-peer"),
	})
	require.NoError(t, err)

	match, err := client.DescribeVpcPeeringConnections(t.Context(), &ec2sdk.DescribeVpcPeeringConnectionsInput{
		VpcPeeringConnectionIds: []string{aws.ToString(pcx.VpcPeeringConnection.VpcPeeringConnectionId)},
	})
	require.NoError(t, err)
	require.Len(t, match.VpcPeeringConnections, 1)

	miss, err := client.DescribeVpcPeeringConnections(t.Context(), &ec2sdk.DescribeVpcPeeringConnectionsInput{
		VpcPeeringConnectionIds: []string{"pcx-sweep41-nonexistent"},
	})
	require.NoError(t, err)
	assert.Empty(t, miss.VpcPeeringConnections)
}

// DescribeIpams reads IpamId.N correctly
// (awsEc2query_serializeOpDocumentDescribeIpamsInput FlatKeys "IpamId").
func TestDescribeIpams_IpamIdFilter_RealClient(t *testing.T) {
	t.Parallel()

	h := ec2.NewHandler(ec2.NewInMemoryBackend("000000000000", "us-east-1"))
	client := newTestEC2Client(t, h)

	ipam, err := client.CreateIpam(t.Context(), &ec2sdk.CreateIpamInput{})
	require.NoError(t, err)

	match, err := client.DescribeIpams(t.Context(), &ec2sdk.DescribeIpamsInput{
		IpamIds: []string{aws.ToString(ipam.Ipam.IpamId)},
	})
	require.NoError(t, err)
	require.Len(t, match.Ipams, 1)

	miss, err := client.DescribeIpams(t.Context(), &ec2sdk.DescribeIpamsInput{
		IpamIds: []string{"ipam-sweep41-nonexistent"},
	})
	require.NoError(t, err)
	assert.Empty(t, miss.Ipams)
}

// DescribeVpcEncryptionControls reads VpcEncryptionControlId.N correctly
// (awsEc2query_serializeOpDocumentDescribeVpcEncryptionControlsInput
// FlatKeys "VpcEncryptionControlId").
func TestDescribeVpcEncryptionControls_IdFilter_RealClient(t *testing.T) {
	t.Parallel()

	h := ec2.NewHandler(ec2.NewInMemoryBackend("000000000000", "us-east-1"))
	client := newTestEC2Client(t, h)

	vpc, err := client.CreateVpc(t.Context(), &ec2sdk.CreateVpcInput{CidrBlock: aws.String("10.46.0.0/16")})
	require.NoError(t, err)

	vec, err := client.CreateVpcEncryptionControl(t.Context(), &ec2sdk.CreateVpcEncryptionControlInput{
		VpcId: vpc.Vpc.VpcId,
	})
	require.NoError(t, err)

	match, err := client.DescribeVpcEncryptionControls(t.Context(), &ec2sdk.DescribeVpcEncryptionControlsInput{
		VpcEncryptionControlIds: []string{aws.ToString(vec.VpcEncryptionControl.VpcEncryptionControlId)},
	})
	require.NoError(t, err)
	require.Len(t, match.VpcEncryptionControls, 1)

	miss, err := client.DescribeVpcEncryptionControls(t.Context(), &ec2sdk.DescribeVpcEncryptionControlsInput{
		VpcEncryptionControlIds: []string{"vec-sweep41-nonexistent"},
	})
	require.NoError(t, err)
	assert.Empty(t, miss.VpcEncryptionControls)
}

// DescribeFpgaImages reads FpgaImageId.N correctly
// (awsEc2query_serializeOpDocumentDescribeFpgaImagesInput FlatKeys
// "FpgaImageId").
func TestDescribeFpgaImages_IdFilter_RealClient(t *testing.T) {
	t.Parallel()

	h := ec2.NewHandler(ec2.NewInMemoryBackend("000000000000", "us-east-1"))
	client := newTestEC2Client(t, h)

	img1, err := client.CreateFpgaImage(t.Context(), &ec2sdk.CreateFpgaImageInput{
		Name:                 aws.String("sweep41-afi1"),
		InputStorageLocation: &types.StorageLocation{Bucket: aws.String("sweep41-bucket"), Key: aws.String("afi1.tar")},
	})
	require.NoError(t, err)

	_, err = client.CreateFpgaImage(t.Context(), &ec2sdk.CreateFpgaImageInput{
		Name:                 aws.String("sweep41-afi2"),
		InputStorageLocation: &types.StorageLocation{Bucket: aws.String("sweep41-bucket"), Key: aws.String("afi2.tar")},
	})
	require.NoError(t, err)

	out, err := client.DescribeFpgaImages(t.Context(), &ec2sdk.DescribeFpgaImagesInput{
		FpgaImageIds: []string{aws.ToString(img1.FpgaImageId)},
	})
	require.NoError(t, err)
	require.Len(t, out.FpgaImages, 1, "FpgaImageIds ignored -- expected exactly the requested image")
	assert.Equal(t, "sweep41-afi1", aws.ToString(out.FpgaImages[0].Name))
}

// DescribeInstanceSqlHaStates reads InstanceId.N correctly
// (awsEc2query_serializeOpDocumentDescribeInstanceSqlHaStatesInput FlatKeys
// "InstanceId").
func TestDescribeInstanceSqlHaStates_InstanceIdFilter_RealClient(t *testing.T) {
	t.Parallel()

	h := ec2.NewHandler(ec2.NewInMemoryBackend("000000000000", "us-east-1"))
	client := newTestEC2Client(t, h)

	instanceIDs := make([]string, 0, 2)

	for range 2 {
		instOut, err := client.RunInstances(t.Context(), &ec2sdk.RunInstancesInput{
			ImageId:      aws.String("ami-sweep41e"),
			InstanceType: types.InstanceTypeT3Micro,
			MinCount:     aws.Int32(1),
			MaxCount:     aws.Int32(1),
		})
		require.NoError(t, err)
		require.Len(t, instOut.Instances, 1)
		instanceIDs = append(instanceIDs, aws.ToString(instOut.Instances[0].InstanceId))
	}

	_, err := client.EnableInstanceSqlHaStandbyDetections(
		t.Context(), &ec2sdk.EnableInstanceSqlHaStandbyDetectionsInput{InstanceIds: instanceIDs},
	)
	require.NoError(t, err)

	out, err := client.DescribeInstanceSqlHaStates(t.Context(), &ec2sdk.DescribeInstanceSqlHaStatesInput{
		InstanceIds: []string{instanceIDs[0]},
	})
	require.NoError(t, err)
	require.Len(t, out.Instances, 1, "InstanceIds ignored -- expected exactly the requested instance")
	assert.Equal(t, instanceIDs[0], aws.ToString(out.Instances[0].InstanceId))
}
